var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(e,u,w){if(null==e)throw new TypeError("The 'this' value for String.prototype."+w+" must not be null or undefined");if(u instanceof RegExp)throw new TypeError("First argument to String.prototype."+w+" must not be a regular expression");return e+""};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(e,u,w){e!=Array.prototype&&e!=Object.prototype&&(e[u]=w.value)};$jscomp.getGlobal=function(e){return"undefined"!=typeof window&&window===e?e:"undefined"!=typeof global&&null!=global?global:e};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(e,u,w,A){if(u){w=$jscomp.global;e=e.split(".");for(A=0;A<e.length-1;A++){var F=e[A];F in w||(w[F]={});w=w[F]}e=e[e.length-1];A=w[e];u=u(A);u!=A&&null!=u&&$jscomp.defineProperty(w,e,{configurable:!0,writable:!0,value:u})}};
$jscomp.polyfill("String.prototype.endsWith",function(e){return e?e:function(e,w){var u=$jscomp.checkStringArgs(this,e,"endsWith");e+="";void 0===w&&(w=u.length);w=Math.max(0,Math.min(w|0,u.length));for(var F=e.length;0<F&&0<w;)if(u[--w]!=e[--F])return!1;return 0>=F}},"es6-impl","es3");
$jscomp.polyfill("String.prototype.startsWith",function(e){return e?e:function(e,w){var u=$jscomp.checkStringArgs(this,e,"startsWith");e+="";var F=u.length,ua=e.length;w=Math.max(0,Math.min(w|0,u.length));for(var la=0;la<ua&&w<F;)if(u[w++]!=e[la++])return!1;return la>=ua}},"es6-impl","es3");
$jscomp.polyfill("String.prototype.repeat",function(e){return e?e:function(e){var u=$jscomp.checkStringArgs(this,null,"repeat");if(0>e||1342177279<e)throw new RangeError("Invalid count value");e|=0;for(var A="";e;)if(e&1&&(A+=u),e>>>=1)u+=u;return A}},"es6-impl","es3");
(function(){function e(a){function b(b){return function(d){return a(b,d)}}b.arity=2;b.func=a;return b}function u(a){function b(b){return function(d){return function(c){return a(b,d,c)}}}b.arity=3;b.func=a;return b}function w(a){function b(b){return function(d){return function(c){return function(f){return a(b,d,c,f)}}}}b.arity=4;b.func=a;return b}function A(a){function b(b){return function(d){return function(c){return function(f){return function(q){return a(b,d,c,f,q)}}}}}b.arity=5;b.func=a;return b}
function F(a){function b(b){return function(d){return function(c){return function(f){return function(q){return function(m){return a(b,d,c,f,q,m)}}}}}}b.arity=6;b.func=a;return b}function ua(a){function b(b){return function(d){return function(c){return function(f){return function(q){return function(m){return function(e){return a(b,d,c,f,q,m,e)}}}}}}}b.arity=7;b.func=a;return b}function la(a){function b(b){return function(d){return function(c){return function(f){return function(q){return function(m){return function(e){return function(k){return a(b,
d,c,f,q,m,e,k)}}}}}}}}b.arity=8;b.func=a;return b}function Gb(a){function b(b){return function(d){return function(c){return function(f){return function(q){return function(m){return function(e){return function(k){return function(n){return a(b,d,c,f,q,m,e,k,n)}}}}}}}}}b.arity=9;b.func=a;return b}function g(a,b,c){return 2===a.arity?a.func(b,c):a(b)(c)}function r(a,b,c,d){return 3===a.arity?a.func(b,c,d):a(b)(c)(d)}function Q(a,b,c,d,f){return 4===a.arity?a.func(b,c,d,f):a(b)(c)(d)(f)}function x(a,b,
c,d,f,q){return 5===a.arity?a.func(b,c,d,f,q):a(b)(c)(d)(f)(q)}var P=function(){function a(b,d,c){c=ga(c);if(0===c.height)c.table[b]=d;else{var k=x(b,c);0<k&&(b-=c.lengths[k-1]);c.table[k]=a(b,d,c.table[k])}return c}function b(a,c,d,k){if(0===c){var m=Array((k-d)%33);for(var n=0;n<m.length;n++)m[n]=a(d+n);return{ctor:"_Array",height:0,table:m}}var E=Math.pow(32,c);m=Array(Math.ceil((k-d)/E));for(var f=Array(m.length),n=0;n<m.length;n++)m[n]=b(a,c-1,d+n*E,Math.min(d+(n+1)*E,k)),f[n]=C(m[n])+(0<n?f[n-
1]:0);return{ctor:"_Array",height:c,table:m,lengths:f}}function c(a,b){var d=a.height;b.length===d&&b.push({ctor:"_Array",height:d+1,table:[],lengths:[]});b[d].table.push(a);a=C(a);0<b[d].lengths.length&&(a+=b[d].lengths[b[d].lengths.length-1]);b[d].lengths.push(a);32===b[d].table.length&&(c(b[d],b),b[d]={ctor:"_Array",height:d+1,table:[],lengths:[]})}function d(a,b){if(0===b.height)return 32>b.table.length?(b={ctor:"_Array",height:0,table:b.table.slice()},b.table.push(a),b):null;var c=d(a,b.table[b.table.length-
1]);return null!==c?(b=ga(b),b.table[b.table.length-1]=c,b.lengths[b.lengths.length-1]++,b):32>b.table.length?(a=w(a,b.height-1),b=ga(b),b.table.push(a),b.lengths.push(b.lengths[b.lengths.length-1]+C(a)),b):null}function f(a,b){for(var d=b.table.length-1;0<=d;d--)a=0===b.height?B.Cons(b.table[d],a):f(a,b.table[d]);return a}function q(a,b){var d={ctor:"_Array",height:b.height,table:Array(b.table.length)};0<b.height&&(d.lengths=b.lengths);for(var c=0;c<b.table.length;c++)d.table[c]=0===b.height?a(b.table[c]):
q(a,b.table[c]);return d}function fa(a,b,d){var c={ctor:"_Array",height:b.height,table:Array(b.table.length)};0<b.height&&(c.lengths=b.lengths);for(var k=0;k<b.table.length;k++)c.table[k]=0===b.height?g(a,d+k,b.table[k]):fa(a,b.table[k],0==k?d:d+b.lengths[k-1]);return c}function m(a,b,d){if(0===d.height)for(var c=0;c<d.table.length;c++)b=g(a,d.table[c],b);else for(c=0;c<d.table.length;c++)b=m(a,b,d.table[c]);return b}function Ta(a,b,d){if(0===d.height)for(var c=d.table.length;c--;)b=g(a,d.table[c],
b);else for(c=d.table.length;c--;)b=Ta(a,b,d.table[c]);return b}function k(a,b){if(a===C(b))return b;if(0===b.height){var d={ctor:"_Array",height:0};d.table=b.table.slice(0,a);return d}var c=x(a,b);a=k(a-(0<c?b.lengths[c-1]:0),b.table[c]);if(0===c)return a;d={ctor:"_Array",height:b.height,table:b.table.slice(0,c),lengths:b.lengths.slice(0,c)};0<a.table.length&&(d.table[c]=a,d.lengths[c]=C(a)+(0<c?d.lengths[c-1]:0));return d}function n(a,b){if(0===a)return b;if(0===b.height){var d={ctor:"_Array",height:0};
d.table=b.table.slice(a,b.table.length+1);return d}d=x(a,b);a=n(a-(0<d?b.lengths[d-1]:0),b.table[d]);if(d===b.table.length-1)return a;d={ctor:"_Array",height:b.height,table:b.table.slice(d,b.table.length+1),lengths:Array(b.table.length-d)};d.table[0]=a;for(a=b=0;a<d.table.length;a++)b+=C(d.table[a]),d.lengths[a]=b;return d}function ha(a,b){if(0===a.height&&0===b.height)return[a,b];if(1!==a.height||1!==b.height)if(a.height===b.height){a=ga(a);b=ga(b);var d=ha(a.table[a.table.length-1],b.table[0]);
h(a,d[1]);p(b,d[0])}else if(a.height>b.height)a=ga(a),d=ha(a.table[a.table.length-1],b),h(a,d[0]),b=z(d[1],d[1].height+1);else{b=ga(b);d=ha(a,b.table[0]);a=0===d[0].table.length?0:1;var c=0===a?1:0;p(b,d[a]);a=z(d[c],d[c].height+1)}if(0===a.table.length||0===b.table.length)return[a,b];d=t(a,b);return 2>=d?[a,b]:Ua(a,b,d)}function h(a,b){var d=a.table.length-1;a.table[d]=b;a.lengths[d]=C(b);a.lengths[d]+=0<d?a.lengths[d-1]:0}function p(a,b){if(0<b.table.length){a.table[0]=b;a.lengths[0]=C(b);b=C(a.table[0]);
for(var d=1;d<a.lengths.length;d++)b+=C(a.table[d]),a.lengths[d]=b}else{a.table.shift();for(d=1;d<a.lengths.length;d++)a.lengths[d]-=a.lengths[0];a.lengths.shift()}}function t(a,b){for(var d=0,c=0;c<a.table.length;c++)d+=a.table[c].table.length;for(c=0;c<b.table.length;c++)d+=b.table[c].table.length;return a.table.length+b.table.length-(Math.floor((d-1)/32)+1)}function r(a,b,d){return d<a.length?a[d]:b[d-a.length]}function va(a,b,d,c){d<a.length?a[d]=c:b[d-a.length]=c}function Ha(a,b,d,c){va(a.table,
b.table,d,c);var k=0===d||d===a.lengths.length?0:r(a.lengths,a.lengths,d-1);va(a.lengths,b.lengths,d,k+C(c))}function wa(a,b){0>b&&(b=0);var d={ctor:"_Array",height:a,table:Array(b)};0<a&&(d.lengths=Array(b));return d}function Ua(a,b,d){for(var c=wa(a.height,Math.min(32,a.table.length+b.table.length-d)),k=wa(a.height,c.table.length-(a.table.length+b.table.length-d)),m=0;0===r(a.table,b.table,m).table.length%32;)va(c.table,k.table,m,r(a.table,b.table,m)),va(c.lengths,k.lengths,m,r(a.lengths,b.lengths,
m)),m++;for(var n=m,f=new wa(a.height-1,0),l=0;m-n-(0<f.table.length?1:0)<d;){var v=r(a.table,b.table,m),q=Math.min(32-f.table.length,v.table.length);f.table=f.table.concat(v.table.slice(l,q));if(0<f.height)for(var e=f.lengths.length,ba=e;ba<e+q-l;ba++)f.lengths[ba]=C(f.table[ba]),f.lengths[ba]+=0<ba?f.lengths[ba-1]:0;l+=q;v.table.length<=q&&(m++,l=0);32===f.table.length&&(Ha(c,k,n,f),f=wa(a.height-1,0),n++)}0<f.table.length&&(Ha(c,k,n,f),n++);for(;m<a.table.length+b.table.length;)Ha(c,k,n,r(a.table,
b.table,m)),m++,n++;return[c,k]}function ga(a){var b={ctor:"_Array",height:a.height,table:a.table.slice()};0<a.height&&(b.lengths=a.lengths.slice());return b}function C(a){return 0===a.height?a.table.length:a.lengths[a.lengths.length-1]}function x(a,b){for(var d=a>>5*b.height;b.lengths[d]<=a;)d++;return d}function w(a,b){return 0===b?{ctor:"_Array",height:0,table:[a]}:{ctor:"_Array",height:b,table:[w(a,b-1)],lengths:[1]}}function z(a,b){return b===a.height?a:{ctor:"_Array",height:b,table:[z(a,b-1)],
lengths:[C(a)]}}function y(a,b){return{ctor:"_Array",height:a.height+1,table:[a,b],lengths:[C(a),C(a)+C(b)]}}function Va(a,b,d){for(var c=0;c<d.table.length;c++)0===d.height?a[b+c]=d.table[c]:Va(a,b+(0===c?0:d.lengths[c-1]),d.table[c])}function Wa(a,b,d,c){if(0===b)return{ctor:"_Array",height:0,table:a.slice(d,c)};for(var k=Math.pow(32,b),m=Array(Math.ceil((c-d)/k)),n=Array(m.length),f=0;f<m.length;f++)m[f]=Wa(a,b-1,d+f*k,Math.min(d+(f+1)*k,c)),n[f]=C(m[f])+(0<f?n[f-1]:0);return{ctor:"_Array",height:b,
table:m,lengths:n}}var A={ctor:"_Array",height:0,table:[]};return{empty:A,fromList:function(a){if("[]"===a.ctor)return A;var b=Array(32);for(var d=[],k=0;"[]"!==a.ctor;)b[k]=a._0,a=a._1,k++,32===k&&(b={ctor:"_Array",height:0,table:b},c(b,d),b=Array(32),k=0);0<k&&(b={ctor:"_Array",height:0,table:b.splice(0,k)},c(b,d));for(a=0;a<d.length-1;a++)0<d[a].table.length&&c(d[a],d);d=d[d.length-1];return 0<d.height&&1===d.table.length?d.table[0]:d},toList:function(a){return f(B.Nil,a)},initialize:e(function(a,
d){return 0>=a?A:b(d,Math.floor(Math.log(a)/Math.log(32)),0,a)}),append:e(function(a,b){if(0===a.table.length)return b;if(0===b.table.length)return a;var d=ha(a,b);if(32>=d[0].table.length+d[1].table.length){if(0===d[0].table.length)return d[1];if(0===d[1].table.length)return d[0];d[0].table=d[0].table.concat(d[1].table);if(0<d[0].height){a=C(d[0]);for(b=0;b<d[1].lengths.length;b++)d[1].lengths[b]+=a;d[0].lengths=d[0].lengths.concat(d[1].lengths)}return d[0]}0<d[0].height&&(a=t(a,b),2<a&&(d=Ua(d[0],
d[1],a)));return y(d[0],d[1])}),push:e(function(a,b){var c=d(a,b);if(null!==c)return c;a=w(a,b.height);return y(b,a)}),slice:u(function(a,b,d){0>a&&(a+=C(d));0>b&&(b+=C(d));return n(a,k(b,d))}),get:e(function(a,b){if(0>a||a>=C(b))throw Error("Index "+a+" is out of range. Check the length of your array first or use getMaybe or getWithDefault.");for(var d=b.height;0<d;d--){for(var c=a>>5*d;b.lengths[c]<=a;)c++;0<c&&(a-=b.lengths[c-1]);b=b.table[c]}return b.table[a]}),set:u(function(b,d,c){return 0>
b||C(c)<=b?c:a(b,d,c)}),map:e(q),indexedMap:e(function(a,b){return fa(a,b,0)}),foldl:u(m),foldr:u(Ta),length:C,toJSArray:function(a){var b=Array(C(a));Va(b,0,a);return b},fromJSArray:function(a){return 0===a.length?A:Wa(a,Math.floor(Math.log(a.length)/Math.log(32)),0,a.length)}}}(),H=function(){function a(b,d){if(0===d)throw Error("Cannot perform mod 0. Division by zero error.");var c=b%d;b=0===b?0:0<d?0<=b?c:c+d:-a(-b,-d);return b===d?0:b}var b=["LT","EQ","GT"];return{div:e(function(a,b){return a/
b|0}),rem:e(function(a,b){return a%b}),mod:e(a),pi:Math.PI,e:Math.E,cos:Math.cos,sin:Math.sin,tan:Math.tan,acos:Math.acos,asin:Math.asin,atan:Math.atan,atan2:e(Math.atan2),degrees:function(a){return a*Math.PI/180},turns:function(a){return 2*Math.PI*a},fromPolar:function(a){var b=a._0;a=a._1;return p.Tuple2(b*Math.cos(a),b*Math.sin(a))},toPolar:function(a){var b=a._0;a=a._1;return p.Tuple2(Math.sqrt(b*b+a*a),Math.atan2(a,b))},sqrt:Math.sqrt,logBase:e(function(a,b){return Math.log(b)/Math.log(a)}),
negate:function(a){return-a},abs:function(a){return 0>a?-a:a},min:e(function(a,b){return 0>p.cmp(a,b)?a:b}),max:e(function(a,b){return 0<p.cmp(a,b)?a:b}),clamp:u(function(a,b,f){return 0>p.cmp(f,a)?a:0<p.cmp(f,b)?b:f}),compare:e(function(a,d){return{ctor:b[p.cmp(a,d)+1]}}),xor:e(function(a,b){return a!==b}),not:function(a){return!a},truncate:function(a){return a|0},ceiling:Math.ceil,floor:Math.floor,round:Math.round,toFloat:function(a){return a},isNaN:isNaN,isInfinite:function(a){return Infinity===
a||-Infinity===a}}}(),p=function(){function a(b,d,c,n){if(100<c)return n.push({x:b,y:d}),!0;if(b===d)return!0;if("object"!==typeof b){if("function"===typeof b)throw Error('Trying to use `(\x3d\x3d)` on functions. There is no way to know if functions are "the same" in the Elm sense. Read more about this at http://package.elm-lang.org/packages/elm-lang/core/latest/Basics#\x3d\x3d which describes why it is this way and what the better version will look like.');return!1}if(null===b||null===d)return!1;
if(b instanceof Date)return b.getTime()===d.getTime();if(!("ctor"in b)){for(var k in b)if(!a(b[k],d[k],c+1,n))return!1;return!0}if("RBNode_elm_builtin"===b.ctor||"RBEmpty_elm_builtin"===b.ctor)b=xa(b),d=xa(d);"Set_elm_builtin"===b.ctor&&(b=_elm_lang$core$Set$toList(b),d=_elm_lang$core$Set$toList(d));if("::"===b.ctor){for(;"::"===b.ctor&&"::"===d.ctor;){if(!a(b._0,d._0,c+1,n))return!1;b=b._1;d=d._1}return b.ctor===d.ctor}if("_Array"===b.ctor){b=P.toJSArray(b);d=P.toJSArray(d);if(b.length!==d.length)return!1;
for(k=0;k<b.length;k++)if(!a(b[k],d[k],c+1,n))return!1;return!0}if(!a(b.ctor,d.ctor,c+1,n))return!1;for(k in b)if(!a(b[k],d[k],c+1,n))return!1;return!0}function b(a,d){if("object"!==typeof a)return a===d?0:a<d?-1:1;if(a instanceof String)return a=a.valueOf(),d=d.valueOf(),a===d?0:a<d?-1:1;if("::"===a.ctor||"[]"===a.ctor){for(;"::"===a.ctor&&"::"===d.ctor;){var c=b(a._0,d._0);if(0!==c)return c;a=a._1;d=d._1}return a.ctor===d.ctor?0:"[]"===a.ctor?-1:1}if("_Tuple"===a.ctor.slice(0,6)){var n=a.ctor.slice(6)-
0;if(0===n)return 0;if(1<=n){c=b(a._0,d._0);if(0!==c)return c;if(2<=n){c=b(a._1,d._1);if(0!==c)return c;if(3<=n){c=b(a._2,d._2);if(0!==c)return c;if(4<=n){c=b(a._3,d._3);if(0!==c)return c;if(5<=n){c=b(a._4,d._4);if(0!==c)return c;if(6<=n){c=b(a._5,d._5);if(0!==c)return c;if(7<=n)throw Error("Comparison error: cannot compare tuples with more than 6 elements.");}}}}}}return 0}throw Error("Comparison error: comparison is only defined on ints, floats, times, chars, strings, lists of comparable values, and tuples of comparable values.");
}function c(a){return a.start.line==a.end.line?"on line "+a.start.line:"between lines "+a.start.line+" and "+a.end.line}function d(a){var b=typeof a;if("function"===b)return"\x3cfunction\x3e";if("boolean"===b)return a?"True":"False";if("number"===b)return a+"";if(a instanceof String)return"'"+f(a,!0)+"'";if("string"===b)return'"'+f(a,!1)+'"';if(null===a)return"null";if("object"===b&&"ctor"in a){b=a.ctor.substring(0,5);if("_Tupl"===b){b=[];for(var c in a)"ctor"!==c&&b.push(d(a[c]));return"("+b.join(",")+
")"}if("_Task"===b)return"\x3ctask\x3e";if("_Array"===a.ctor)return a=Hb(a),"Array.fromList "+d(a);if("\x3cdecoder\x3e"===a.ctor)return"\x3cdecoder\x3e";if("_Process"===a.ctor)return"\x3cprocess:"+a.id+"\x3e";if("::"===a.ctor){b="["+d(a._0);for(a=a._1;"::"===a.ctor;)b+=","+d(a._0),a=a._1;return b+"]"}if("[]"===a.ctor)return"[]";if("Set_elm_builtin"===a.ctor)return"Set.fromList "+d(_elm_lang$core$Set$toList(a));if("RBNode_elm_builtin"===a.ctor||"RBEmpty_elm_builtin"===a.ctor)return"Dict.fromList "+
d(xa(a));b="";for(var n in a)if("ctor"!==n){c=d(a[n]);var q=c[0],q="{"===q||"("===q||"\x3c"===q||'"'===q||0>c.indexOf(" ");b+=" "+(q?c:"("+c+")")}return a.ctor+b}if("object"===b){if(a instanceof Date)return"\x3c"+a.toString()+"\x3e";if(a.elm_web_socket)return"\x3cwebsocket\x3e";b=[];for(c in a)b.push(c+" \x3d "+d(a[c]));return 0===b.length?"{}":"{ "+b.join(", ")+" }"}return"\x3cinternal structure\x3e"}function f(a,b){a=a.replace(/\\/g,"\\\\").replace(/\n/g,"\\n").replace(/\t/g,"\\t").replace(/\r/g,
"\\r").replace(/\v/g,"\\v").replace(/\0/g,"\\0");return b?a.replace(/\'/g,"\\'"):a.replace(/\"/g,'\\"')}var q=0,g={ctor:"[]"};return{eq:function(b,d){var c=[];b=a(b,d,0,c);for(var n;b&&(n=c.pop());)b=a(n.x,n.y,0,c);return b},cmp:b,Tuple0:{ctor:"_Tuple0"},Tuple2:function(a,b){return{ctor:"_Tuple2",_0:a,_1:b}},chr:function(a){return new String(a)},update:function(a,b){var d={},c;for(c in a)d[c]=a[c];for(c in b)d[c]=b[c];return d},guid:function(a){return q++},append:e(function(a,b){if("string"===typeof a)return a+
b;if("[]"===a.ctor)return b;var d={ctor:"::",_0:a._0,_1:g},c=d;for(a=a._1;"[]"!==a.ctor;)c._1={ctor:"::",_0:a._0,_1:g},a=a._1,c=c._1;c._1=b;return d}),crash:function(a,b){return function(d){throw Error("Ran into a `Debug.crash` in module `"+a+"` "+c(b)+"\nThe message provided by the code author is:\n\n    "+d);}},crashCase:function(a,b,k){return function(n){throw Error("Ran into a `Debug.crash` in module `"+a+"`\n\nThis was caused by the `case` expression "+c(b)+".\nOne of the branches ended with a crash and the following value got through:\n\n    "+
d(k)+"\n\nThe message provided by the code author is:\n\n    "+n);}},toString:d}}();e(function(a,b){return g(a,b._0,b._1)});u(function(a,b,c){return a({ctor:"_Tuple2",_0:b,_1:c})});var Ib=u(function(a,b,c){return g(a,c,b)}),ca=e(function(a,b){return a}),t=t||{};t["\x3c|"]=e(function(a,b){return a(b)});t=t||{};t["|\x3e"]=e(function(a,b){return b(a)});t=t||{};t["\x3e\x3e"]=u(function(a,b,c){return b(a(c))});t=t||{};t["\x3c\x3c"]=u(function(a,b,c){return a(b(c))});t=t||{};t["++"]=p.append;var Y=p.toString,
Jb=H.toFloat,Kb=H.round,t=t||{};t["||"]=H.or;t=t||{};t["\x26\x26"]=H.and;var Xa=H.compare,t=t||{};t["\x3e\x3d"]=H.ge;t=t||{};t["\x3c\x3d"]=H.le;t=t||{};t["\x3e"]=H.gt;t=t||{};t["\x3c"]=H.lt;t=t||{};t["/\x3d"]=H.neq;t=t||{};t["\x3d\x3d"]=H.eq;t=t||{};t["^"]=H.exp;t=t||{};t["%"]=H.mod;t=t||{};t["//"]=H.div;t=t||{};t["/"]=H.floatDiv;t=t||{};t["*"]=H.mul;t=t||{};t["-"]=H.sub;t=t||{};t["+"]=H.add;var Ya=e(function(a,b){return"Just"===b.ctor?b._0:a}),K={ctor:"Nothing"};e(function(a,b){return"Just"===b.ctor?
a(b._0):K});var L=function(a){return{ctor:"Just",_0:a}},Z=e(function(a,b){return"Just"===b.ctor?L(a(b._0)):K});u(function(a,b,c){return"Just"===b.ctor&&"Just"===c.ctor?L(g(a,b._0,c._0)):K});w(function(a,b,c,d){return"Just"===b.ctor&&"Just"===c.ctor&&"Just"===d.ctor?L(r(a,b._0,c._0,d._0)):K});A(function(a,b,c,d,f){return"Just"===b.ctor&&"Just"===c.ctor&&"Just"===d.ctor&&"Just"===f.ctor?L(Q(a,b._0,c._0,d._0,f._0)):K});F(function(a,b,c,d,f,q){return"Just"===b.ctor&&"Just"===c.ctor&&"Just"===d.ctor&&
"Just"===f.ctor&&"Just"===q.ctor?L(x(a,b._0,c._0,d._0,f._0,q._0)):K});var B=function(){function a(a,b){return{ctor:"::",_0:a,_1:b}}function b(b){for(var c=d,f=b.length;f--;)c=a(b[f],c);return c}function c(a){for(var b=[];"[]"!==a.ctor;)b.push(a._0),a=a._1;return b}var d={ctor:"[]"};return{Nil:d,Cons:a,cons:e(a),toArray:c,fromArray:b,foldr:u(function(a,b,d){d=c(d);for(var f=d.length;f--;)b=g(a,d[f],b);return b}),map2:u(function(a,d,c){for(var f=[];"[]"!==d.ctor&&"[]"!==c.ctor;)f.push(g(a,d._0,c._0)),
d=d._1,c=c._1;return b(f)}),map3:w(function(a,d,c,e){for(var f=[];"[]"!==d.ctor&&"[]"!==c.ctor&&"[]"!==e.ctor;)f.push(r(a,d._0,c._0,e._0)),d=d._1,c=c._1,e=e._1;return b(f)}),map4:A(function(a,d,c,e,g){for(var k=[];"[]"!==d.ctor&&"[]"!==c.ctor&&"[]"!==e.ctor&&"[]"!==g.ctor;)k.push(Q(a,d._0,c._0,e._0,g._0)),d=d._1,c=c._1,e=e._1,g=g._1;return b(k)}),map5:F(function(a,d,c,e,g,k){for(var n=[];"[]"!==d.ctor&&"[]"!==c.ctor&&"[]"!==e.ctor&&"[]"!==g.ctor&&"[]"!==k.ctor;)n.push(x(a,d._0,c._0,e._0,g._0,k._0)),
d=d._1,c=c._1,e=e._1,g=g._1,k=k._1;return b(n)}),sortBy:e(function(a,d){return b(c(d).sort(function(b,d){return p.cmp(a(b),a(d))}))}),sortWith:e(function(a,d){return b(c(d).sort(function(b,d){b=a(b)(d).ctor;return"EQ"===b?0:"LT"===b?-1:1}))})}}(),Lb=e(function(a,b){for(;;){if(1>p.cmp(a,0))return b;var c=b;if("[]"===c.ctor)return b;b=c._1;--a}}),Mb=B.map2,Za=e(function(a,b){for(;;){if("[]"===b.ctor)return!1;if(a(b._0))return!0;b=b._1}});e(function(a,b){return!g(Za,function(b){return!a(b)},b)});var S=
B.foldr,na=u(function(a,b,c){for(;;){var d=c;if("[]"===d.ctor)return b;c=a;b=g(a,d._0,b);d=d._1;a=c;c=d}}),Nb=function(a){return r(na,e(function(a,c){return c+1}),0,a)},Ob=function(a){return r(na,e(function(a,c){return a+c}),0,a)};e(function(a,b){return g(Za,function(b){return p.eq(b,a)},b)});var $a=$a||{};$a["::"]=B.cons;var Ia=e(function(a,b){return r(S,e(function(b,d){return{ctor:"::",_0:a(b),_1:d}}),{ctor:"[]"},b)}),Pb=e(function(a,b){var c=e(function(b,c){return a(b)?{ctor:"::",_0:b,_1:c}:c});
return r(S,c,{ctor:"[]"},b)}),Qb=u(function(a,b,c){a=a(b);return"Just"===a.ctor?{ctor:"::",_0:a._0,_1:c}:c});e(function(a,b){return r(S,Qb(a),{ctor:"[]"},b)});var ab=function(a){return r(na,e(function(a,c){return{ctor:"::",_0:a,_1:c}}),{ctor:"[]"},a)};u(function(a,b,c){var d=e(function(b,d){return"::"===d.ctor?{ctor:"::",_0:g(a,b,d._0),_1:d}:{ctor:"[]"}});return ab(r(na,d,{ctor:"::",_0:b,_1:{ctor:"[]"}},c))});var Rb=e(function(a,b){return"[]"===b.ctor?a:r(S,e(function(a,b){return{ctor:"::",_0:a,_1:b}}),
b,a)});e(function(a,b){return r(S,Rb,{ctor:"[]"},g(Ia,a,b))});e(function(a,b){var c=e(function(b,c){var d=c._0;c=c._1;return a(b)?{ctor:"_Tuple2",_0:{ctor:"::",_0:b,_1:d},_1:c}:{ctor:"_Tuple2",_0:d,_1:{ctor:"::",_0:b,_1:c}}});return r(S,c,{ctor:"_Tuple2",_0:{ctor:"[]"},_1:{ctor:"[]"}},b)});e(function(a,b){if("[]"===b.ctor)return{ctor:"[]"};var c=e(function(b,c){return{ctor:"::",_0:a,_1:{ctor:"::",_0:b,_1:c}}}),c=r(S,c,{ctor:"[]"},b._1);return{ctor:"::",_0:b._0,_1:c}});var Sb=u(function(a,b,c){for(;;){if(1>
p.cmp(a,0))return c;var d=b;if("[]"===d.ctor)return c;b=d._1;c={ctor:"::",_0:d._0,_1:c};--a}}),Tb=e(function(a,b){return ab(r(Sb,a,b,{ctor:"[]"}))}),bb=u(function(a,b,c){if(1>p.cmp(b,0))return{ctor:"[]"};a:do{b:do{if("[]"===c.ctor)return c;if("::"===c._1.ctor)switch(b){case 1:break b;case 2:return{ctor:"::",_0:c._0,_1:{ctor:"::",_0:c._1._0,_1:{ctor:"[]"}}};case 3:if("::"===c._1._1.ctor)return{ctor:"::",_0:c._0,_1:{ctor:"::",_0:c._1._0,_1:{ctor:"::",_0:c._1._1._0,_1:{ctor:"[]"}}}};break a;default:if("::"===
c._1._1.ctor&&"::"===c._1._1._1.ctor){var d=c._1._1._0,f=c._1._0,e=c._0,fa=c._1._1._1._0;c=c._1._1._1._1;return 0<p.cmp(a,1E3)?{ctor:"::",_0:e,_1:{ctor:"::",_0:f,_1:{ctor:"::",_0:d,_1:{ctor:"::",_0:fa,_1:g(Tb,b-4,c)}}}}:{ctor:"::",_0:e,_1:{ctor:"::",_0:f,_1:{ctor:"::",_0:d,_1:{ctor:"::",_0:fa,_1:r(bb,a+1,b-4,c)}}}}}break a}else if(1===b)break b;else break a}while(0);return{ctor:"::",_0:c._0,_1:{ctor:"[]"}}}while(0);return c}),Ub=e(function(a,b){return r(bb,0,a,b)}),Vb=u(function(a,b,c){for(;;){if(1>
p.cmp(b,0))return a;--b;var d=c;a={ctor:"::",_0:c,_1:a};c=d}});e(function(a,b){return r(Vb,{ctor:"[]"},a,b)});var Wb=u(function(a,b,c){for(;;)if(1>p.cmp(a,b))c={ctor:"::",_0:b,_1:c},--b;else return c}),Xb=e(function(a,b){return r(Wb,a,b,{ctor:"[]"})}),cb=e(function(a,b){return r(Mb,a,g(Xb,0,Nb(b)-1),b)});e(function(a,b){return 1>p.cmp(0,a)&&0>p.cmp(a,P.length(b))?L(g(P.get,a,b)):K});e(function(a,b){var c=e(function(b,c){return a(b)?g(P.push,b,c):c});return r(P.foldl,c,P.empty,b)});var Hb=P.toList,
Yb=P.initialize;e(function(a,b){return g(Yb,a,ca(b))});var Ja=function(){return{fromCode:function(a){return p.chr(String.fromCharCode(a))},toCode:function(a){return a.charCodeAt(0)},toUpper:function(a){return p.chr(a.toUpperCase())},toLower:function(a){return p.chr(a.toLowerCase())},toLocaleUpper:function(a){return p.chr(a.toLocaleUpperCase())},toLocaleLower:function(a){return p.chr(a.toLocaleLowerCase())}}}().toCode,ya=u(function(a,b,c){c=Ja(c);return-1<p.cmp(c,Ja(a))&&1>p.cmp(c,Ja(b))});g(ya,p.chr("A"),
p.chr("Z"));g(ya,p.chr("a"),p.chr("z"));g(ya,p.chr("0"),p.chr("9"));g(ya,p.chr("0"),p.chr("7"));var z=function(){function a(a){return{ctor:"_Task_succeed",value:a}}function b(a){return{ctor:"_Task_nativeBinding",callback:a,cancel:null}}function c(a){a={ctor:"_Process",id:p.guid(),root:a,stack:null,mailbox:[]};q(a);return a}function d(a,b){a.mailbox.push(b);q(a)}function f(a,b){for(;1E4>a;){var d=b.root.ctor;if("_Task_succeed"===d){for(;b.stack&&"_Task_onError"===b.stack.ctor;)b.stack=b.stack.rest;
if(null===b.stack)break;b.root=b.stack.callback(b.root.value);b.stack=b.stack.rest;++a}else if("_Task_fail"===d){for(;b.stack&&"_Task_andThen"===b.stack.ctor;)b.stack=b.stack.rest;if(null===b.stack)break;b.root=b.stack.callback(b.root.value);b.stack=b.stack.rest;++a}else if("_Task_andThen"===d)b.stack={ctor:"_Task_andThen",callback:b.root.callback,rest:b.stack},b.root=b.root.task,++a;else if("_Task_onError"===d)b.stack={ctor:"_Task_onError",callback:b.root.callback,rest:b.stack},b.root=b.root.task,
++a;else{if("_Task_nativeBinding"===d){b.root.cancel=b.root.callback(function(a){b.root=a;q(b)});break}if("_Task_receive"===d){d=b.mailbox;if(0===d.length)break;b.root=b.root.callback(d.shift());++a}else throw Error(d);}}if(1E4>a)return a+1;q(b);return a}function q(a){h.push(a);m||(setTimeout(g,0),m=!0)}function g(){for(var a=0,b;1E4>a&&(b=h.shift());)b.root&&(a=f(a,b));b?setTimeout(g,0):m=!1}var m=!1,h=[];return{succeed:a,fail:function(a){return{ctor:"_Task_fail",value:a}},nativeBinding:b,andThen:e(function(a,
b){return{ctor:"_Task_andThen",callback:a,task:b}}),onError:e(function(a,b){return{ctor:"_Task_onError",callback:a,task:b}}),receive:function(a){return{ctor:"_Task_receive",callback:a}},spawn:function(d){return b(function(b){var f=c(d);b(a(f))})},kill:function(d){return b(function(b){var c=d.root;"_Task_nativeBinding"===c.ctor&&c.cancel&&c.cancel();d.root=null;b(a(p.Tuple0))})},sleep:function(d){return b(function(b){var c=setTimeout(function(){b(a(p.Tuple0))},d);return function(){clearTimeout(c)}})},
send:e(function(c,f){return b(function(b){d(c,f);b(a(p.Tuple0))})}),rawSpawn:c,rawSend:d}}(),T=function(){function a(a,b){return function(a){}}function b(a,b,d,k){function e(a){z.rawSend(fa,a)}var n={},q,h=z.nativeBinding(function(b){var c=a._0;q=k(e,c);var f=a._1,g=d(c);m(n,f,g);b(z.succeed(c))}),fa=f(h,function(a,c){return z.nativeBinding(function(f){var k=g(b,a,c);c=k._0;q(c);var k=k._1,e=d(c);m(n,k,e);f(z.succeed(c))})});return(h=c(n,e))?{ports:h}:{}}function c(a,b){var c;for(c in O){var f=O[c];
if(f.isForeign){var k=k||{};k[c]="cmd"===f.tag?ha(c):Ga(c,b)}a[c]=d(f,b)}return k}function d(a,b){var d={main:b,self:void 0},c=a.tag,k=a.onEffects,e=a.onSelfMsg;a=f(a.init,function(a,b){if("self"===a.ctor)return r(e,d,a._0,b);a=a._0;switch(c){case "cmd":return r(k,d,a.cmds,b);case "sub":return r(k,d,a.subs,b);case "fx":return Q(k,d,a.cmds,a.subs,b)}});return d.self=a}function f(a,b){function d(a){var f=z.receive(function(d){return b(d,a)});return g(c,d,f)}var c=z.andThen;a=g(c,d,a);return z.rawSpawn(a)}
function q(a){return function(b){return{type:"leaf",home:a,value:b}}}function h(a){return{type:"node",branches:a}}function m(a,b,d){var c={};t(!0,b,c,null);t(!1,d,c,null);for(var f in a)z.rawSend(a[f],{ctor:"fx",_0:f in c?c[f]:{cmds:B.Nil,subs:B.Nil}})}function t(a,b,d,c){switch(b.type){case "leaf":var f=b.home;c=k(a,f,c,b.value);b=(b=d[f])||{cmds:B.Nil,subs:B.Nil};a?b.cmds=B.Cons(c,b.cmds):b.subs=B.Cons(c,b.subs);d[f]=b;break;case "node":for(f=b.branches;"[]"!==f.ctor;)t(a,f._0,d,c),f=f._1;break;
case "map":t(a,b.tree,d,{tagger:b.tagger,rest:c})}}function k(a,b,d,c){return g(a?O[b].cmdMap:O[b].subMap,function(a){for(var b=d;b;)a=b.tagger(a),b=b.rest;return a},c)}function n(a){if(a in O)throw Error("There can only be one port named `"+a+"`, but your program has multiple.");}function ha(a){var b=[],d=O[a].converter,c=z.succeed(null);O[a].init=c;O[a].onEffects=u(function(a,f,k){for(;"[]"!==f.ctor;){a=b;k=d(f._0);for(var e=0;e<a.length;e++)a[e](k);f=f._1}return c});return{subscribe:function(a){b.push(a)},
unsubscribe:function(a){b=b.slice();a=b.indexOf(a);0<=a&&b.splice(a,1)}}}function Ga(a,b){function d(a,b,d){k=b;return m}function c(a){for(var d=k;"[]"!==d.ctor;)b(d._0(a)),d=d._1}var f=[],k=B.Nil,e=O[a].converter,n=function(a,b,k){a=d(a,b,k);for(b=0;b<f.length;b++)c(f[b]);f=null;q=c;n=d;return a},q=function(a){f.push(a)},m=z.succeed(null);O[a].init=m;O[a].onEffects=u(function(a,b,d){return n(a,b,d)});return{send:function(b){b=g(Ka,e,b);if("Err"===b.ctor)throw Error("Trying to send an unexpected type of value through port `"+
a+"`:\n"+b._0);q(b._0)}}}var O={},x=e(function(a,b){return b}),w=e(function(a,b){return function(d){return a(b(d))}});return{sendToApp:e(function(a,b){return z.nativeBinding(function(d){a.main(b);d(z.succeed(p.Tuple0))})}),sendToSelf:e(function(a,b){return g(z.send,a.self,{ctor:"self",_0:b})}),effectManagers:O,outgoingPort:function(a,b){n(a);O[a]={tag:"cmd",cmdMap:x,converter:b,isForeign:!0};return q(a)},incomingPort:function(a,b){n(a);O[a]={tag:"sub",subMap:w,converter:b,isForeign:!0};return q(a)},
htmlToProgram:function(a){var b=h(B.Nil),d=p.Tuple2(p.Tuple0,b);return g(aa.program,db,{init:d,view:function(a){return main},update:e(function(a,b){return d}),subscriptions:function(a){return b}})},program:function(d){return function(c){return function(c,f){c.worker=function(c){if("undefined"!==typeof c)throw Error("The `"+f+"` module does not need flags.\nCall "+f+".worker() with no arguments and you should be all set!");return b(d.init,d.update,d.subscriptions,a)}}}},programWithFlags:function(d){return function(c){return function(f,
k){f.worker=function(f){if("undefined"===typeof c)throw Error("Are you trying to sneak a Never value into Elm? Trickster!\nIt looks like "+k+".main is defined with `programWithFlags` but has type `Program Never`.\nUse `program` instead if you do not want flags.");f=g(M.run,c,f);if("Err"===f.ctor)throw Error(k+".worker(...) was called with an unexpected argument.\nI tried to convert it to an Elm value, but ran into this problem:\n\n"+f._0);return b(d.init(f._0),d.update,d.subscriptions,a)}}}},initialize:b,
leaf:q,batch:h,map:e(function(a,b){return{type:"map",tagger:a,tree:b}})}}(),eb=T.batch,da=eb({ctor:"[]"}),fb=fb||{};fb["!"]=e(function(a,b){return{ctor:"_Tuple2",_0:a,_1:eb(b)}});var Zb=T.batch,gb=Zb({ctor:"[]"}),$b=T.sendToApp;e(function(a,b){return"Ok"===b.ctor?b._0:a});var y=function(a){return{ctor:"Err",_0:a}};e(function(a,b){return"Ok"===b.ctor?a(b._0):y(b._0)});var N=function(a){return{ctor:"Ok",_0:a}};e(function(a,b){return"Ok"===b.ctor?N(a(b._0)):y(b._0)});u(function(a,b,c){return"Ok"===b.ctor?
"Ok"===c.ctor?N(g(a,b._0,c._0)):y(c._0):y(b._0)});w(function(a,b,c,d){return"Ok"===b.ctor?"Ok"===c.ctor?"Ok"===d.ctor?N(r(a,b._0,c._0,d._0)):y(d._0):y(c._0):y(b._0)});A(function(a,b,c,d,f){return"Ok"===b.ctor?"Ok"===c.ctor?"Ok"===d.ctor?"Ok"===f.ctor?N(Q(a,b._0,c._0,d._0,f._0)):y(f._0):y(d._0):y(c._0):y(b._0)});F(function(a,b,c,d,f,e){return"Ok"===b.ctor?"Ok"===c.ctor?"Ok"===d.ctor?"Ok"===f.ctor?"Ok"===e.ctor?N(x(a,b._0,c._0,d._0,f._0,e._0)):y(e._0):y(f._0):y(d._0):y(c._0):y(b._0)});e(function(a,
b){return"Ok"===b.ctor?N(b._0):y(a(b._0))});e(function(a,b){return"Just"===b.ctor?N(b._0):y(a)});var hb=z.onError,I=z.andThen,ac=e(function(a,b){return z.spawn(g(I,$b(a),b._0))}),bc=z.fail;e(function(a,b){return g(hb,function(b){return bc(a(b))},b)});var R=z.succeed,La=e(function(a,b){return g(I,function(b){return R(a(b))},b)}),cc=u(function(a,b,c){return g(I,function(b){return g(I,function(d){return R(g(a,b,d))},c)},b)});w(function(a,b,c,d){return g(I,function(b){return g(I,function(c){return g(I,
function(d){return R(r(a,b,c,d))},d)},c)},b)});A(function(a,b,c,d,f){return g(I,function(b){return g(I,function(c){return g(I,function(d){return g(I,function(f){return R(Q(a,b,c,d,f))},f)},d)},c)},b)});F(function(a,b,c,d,f,e){return g(I,function(b){return g(I,function(c){return g(I,function(d){return g(I,function(f){return g(I,function(k){return R(x(a,b,c,d,f,k))},e)},f)},d)},c)},b)});var ib=function(a){return"[]"===a.ctor?R({ctor:"[]"}):r(cc,e(function(a,c){return{ctor:"::",_0:a,_1:c}}),a._0,ib(a._1))},
dc=u(function(a,b,c){return g(La,function(a){return{ctor:"_Tuple0"}},ib(g(Ia,ac(a),b)))}),ec=R({ctor:"_Tuple0"}),fc=u(function(a,b,c){return R({ctor:"_Tuple0"})}),jb=T.leaf("Task");e(function(a,b){return jb({ctor:"Perform",_0:g(La,a,b)})});var gc=e(function(a,b){return jb({ctor:"Perform",_0:g(hb,function(b){return R(a(y(b)))},g(I,function(b){return R(a(N(b)))},b))})}),hc=e(function(a,b){return{ctor:"Perform",_0:g(La,a,b._0)}});T.effectManagers.Task={pkg:"elm-lang/core",init:ec,onEffects:dc,onSelfMsg:fc,
tag:"cmd",cmdMap:hc};var oa=function(){return{crash:function(a){throw Error(a);},log:e(function(a,b){a=a+": "+p.toString(b);var c=c||{};c.stdout?c.stdout.write(a):console.log(a);return b})}}(),ea=function(){function a(a,b){for(var d="";0<a;)a&1&&(d+=b),a>>=1,b+=b;return d}function b(a){return y("could not convert string '"+a+"' to an Int")}function c(a){return y("could not convert string '"+a+"' to a Float")}return{isEmpty:function(a){return 0===a.length},cons:e(function(a,b){return a+b}),uncons:function(a){var b=
a[0];return b?L(p.Tuple2(p.chr(b),a.slice(1))):K},append:e(function(a,b){return a+b}),concat:function(a){return B.toArray(a).join("")},length:function(a){return a.length},map:e(function(a,b){b=b.split("");for(var d=b.length;d--;)b[d]=a(p.chr(b[d]));return b.join("")}),filter:e(function(a,b){return b.split("").map(p.chr).filter(a).join("")}),reverse:function(a){return a.split("").reverse().join("")},foldl:u(function(a,b,c){for(var d=c.length,f=0;f<d;++f)b=g(a,p.chr(c[f]),b);return b}),foldr:u(function(a,
b,c){for(var d=c.length;d--;)b=g(a,p.chr(c[d]),b);return b}),split:e(function(a,b){return B.fromArray(b.split(a))}),join:e(function(a,b){return B.toArray(b).join(a)}),repeat:e(a),slice:u(function(a,b,c){return c.slice(a,b)}),left:e(function(a,b){return 1>a?"":b.slice(0,a)}),right:e(function(a,b){return 1>a?"":b.slice(-a)}),dropLeft:e(function(a,b){return 1>a?b:b.slice(a)}),dropRight:e(function(a,b){return 1>a?b:b.slice(0,-a)}),pad:u(function(b,c,e){b=(b-e.length)/2;return a(Math.ceil(b),c)+e+a(b|
0,c)}),padLeft:u(function(b,c,e){return a(b-e.length,c)+e}),padRight:u(function(b,c,e){return e+a(b-e.length,c)}),trim:function(a){return a.trim()},trimLeft:function(a){return a.replace(/^\s+/,"")},trimRight:function(a){return a.replace(/\s+$/,"")},words:function(a){return B.fromArray(a.trim().split(/\s+/g))},lines:function(a){return B.fromArray(a.split(/\r\n|\r|\n/g))},toUpper:function(a){return a.toUpperCase()},toLower:function(a){return a.toLowerCase()},any:e(function(a,b){for(var d=b.length;d--;)if(a(p.chr(b[d])))return!0;
return!1}),all:e(function(a,b){for(var d=b.length;d--;)if(!a(p.chr(b[d])))return!1;return!0}),contains:e(function(a,b){return-1<b.indexOf(a)}),startsWith:e(function(a,b){return 0===b.indexOf(a)}),endsWith:e(function(a,b){return b.length>=a.length&&b.lastIndexOf(a)===b.length-a.length}),indexes:e(function(a,b){var d=a.length;if(1>d)return B.Nil;for(var c=0,e=[];-1<(c=b.indexOf(a,c));)e.push(c),c+=d;return B.fromArray(e)}),toInt:function(a){var d=a.length;if(0===d)return b(a);var c=a[0];if("0"===c&&
"x"===a[1]){for(var e=2;e<d;++e)if(c=a[e],!("0"<=c&&"9">=c||"A"<=c&&"F">=c||"a"<=c&&"f">=c))return b(a);return N(parseInt(a,16))}if("9"<c||"0">c&&"-"!==c&&"+"!==c)return b(a);for(e=1;e<d;++e)if(c=a[e],"0">c||"9"<c)return b(a);return N(parseInt(a,10))},toFloat:function(a){if(0===a.length||/[\sxbo]/.test(a))return c(a);var b=+a;return b===b?N(b):c(a)},toList:function(a){return B.fromArray(a.split("").map(p.chr))},fromList:function(a){return B.toArray(a).join("")}}}(),ic=ea.toFloat,jc=ea.contains,kb=
ea.toLower,kc=ea.length,lc=ea.concat,mc=ea.append,lb=u(function(a,b,c){for(;;){var d=c;if("RBEmpty_elm_builtin"===d.ctor)return b;c=a;b=r(a,d._1,d._2,r(lb,a,b,d._4));d=d._3;a=c;c=d}}),xa=function(a){return r(lb,u(function(a,c,d){return{ctor:"::",_0:{ctor:"_Tuple2",_0:a,_1:c},_1:d}}),{ctor:"[]"},a)},ia=u(function(a,b,c){for(;;){var d=c;if("RBEmpty_elm_builtin"===d.ctor)return b;c=a;b=r(a,d._1,d._2,r(ia,a,b,d._3));d=d._4;a=c;c=d}});F(function(a,b,c,d,f,g){var q=u(function(d,e,k){for(;;){var f=k;k=f._1;
var g=f._0,q=g;if("[]"===q.ctor)return{ctor:"_Tuple2",_0:g,_1:r(c,d,e,k)};var f=q._1,m=q._0._1,q=q._0._0;if(0>p.cmp(q,d))k={ctor:"_Tuple2",_0:f,_1:r(a,q,m,k)};else return 0<p.cmp(q,d)?{ctor:"_Tuple2",_0:g,_1:r(c,d,e,k)}:{ctor:"_Tuple2",_0:f,_1:Q(b,q,m,e,k)}}});f=r(ia,q,{ctor:"_Tuple2",_0:xa(d),_1:g},f);d=f._0;f=f._1;return r(na,e(function(b,d){return r(a,b._0,b._1,d)}),f,d)});var mb=w(function(a,b,c,d){return oa.crash(lc({ctor:"::",_0:"Internal red-black tree invariant violated, expected ",_1:{ctor:"::",
_0:a,_1:{ctor:"::",_0:" and got ",_1:{ctor:"::",_0:Y(b),_1:{ctor:"::",_0:"/",_1:{ctor:"::",_0:c,_1:{ctor:"::",_0:"/",_1:{ctor:"::",_0:d,_1:{ctor:"::",_0:"\nPlease report this bug to \x3chttps://github.com/elm-lang/core/issues\x3e",_1:{ctor:"[]"}}}}}}}}}}))}),nb=function(a){a:do{if("RBNode_elm_builtin"===a.ctor){if("BBlack"===a._0.ctor)return!0}else if("LBBlack"===a._0.ctor)return!0;break a}while(0);return!1},nc=e(function(a,b){for(;;){if("RBEmpty_elm_builtin"===b.ctor)return a;a=g(nc,a+1,b._4);b=
b._3}}),oc=e(function(a,b){a:for(;;){if("RBEmpty_elm_builtin"===b.ctor)return K;switch(g(Xa,a,b._1).ctor){case "LT":b=b._3;continue a;case "EQ":return L(b._2);default:b=b._4}}}),pc=e(function(a,b){return"Just"===g(oc,a,b).ctor?!0:!1}),qc=u(function(a,b,c){for(;;){if("RBEmpty_elm_builtin"===c.ctor)return{ctor:"_Tuple2",_0:a,_1:b};b=c._2;var d=c._4;a=c._1;c=d}}),rc={ctor:"NBlack"},ob={ctor:"BBlack"},J={ctor:"Black"},za={ctor:"Red"},sc=function(a){switch(a.ctor){case "Black":return ob;case "Red":return J;
case "NBlack":return za;default:return oa.crash("Can't make a double black node more black!")}},pb=function(a){switch(a.ctor){case "BBlack":return J;case "Black":return za;case "Red":return rc;default:return oa.crash("Can't make a negative black node less black!")}},tc={ctor:"LBBlack"},pa={ctor:"LBlack"},ja=function(a){return{ctor:"RBEmpty_elm_builtin",_0:a}},W=ja(pa),D=A(function(a,b,c,d,e){return{ctor:"RBNode_elm_builtin",_0:a,_1:b,_2:c,_3:d,_4:e}}),uc=function(a){return"RBNode_elm_builtin"===a.ctor&&
"Red"===a._0.ctor?x(D,J,a._1,a._2,a._3,a._4):a},qb=function(a){return"RBNode_elm_builtin"===a.ctor?x(D,pb(a._0),a._1,a._2,a._3,a._4):ja(pa)},Aa=function(a){return function(b){return function(c){return function(d){return function(e){return function(f){return function(g){return function(q){return function(m){return function(k){return function(n){return x(D,pb(a),d,e,x(D,J,b,c,q,m),x(D,J,f,g,k,n))}}}}}}}}}}},vc=function(a){return"RBEmpty_elm_builtin"===a.ctor?ja(pa):x(D,J,a._1,a._2,a._3,a._4)},rb=function(a){return"RBEmpty_elm_builtin"===
a.ctor?oa.crash("can't make a Leaf red"):x(D,za,a._1,a._2,a._3,a._4)},wc=function(a){a:do{b:do{c:do{d:do{e:do{f:do{g:do if("RBNode_elm_builtin"===a.ctor)if("RBNode_elm_builtin"===a._3.ctor)if("RBNode_elm_builtin"===a._4.ctor)switch(a._3._0.ctor){case "Red":switch(a._4._0.ctor){case "Red":if("RBNode_elm_builtin"===a._3._3.ctor&&"Red"===a._3._3._0.ctor)break g;else if("RBNode_elm_builtin"===a._3._4.ctor&&"Red"===a._3._4._0.ctor)break f;else if("RBNode_elm_builtin"===a._4._3.ctor&&"Red"===a._4._3._0.ctor)break e;
else if("RBNode_elm_builtin"===a._4._4.ctor&&"Red"===a._4._4._0.ctor)break d;else break a;case "NBlack":if("RBNode_elm_builtin"===a._3._3.ctor&&"Red"===a._3._3._0.ctor)break g;else if("RBNode_elm_builtin"===a._3._4.ctor&&"Red"===a._3._4._0.ctor)break f;else if("BBlack"===a._0.ctor&&"RBNode_elm_builtin"===a._4._3.ctor&&"Black"===a._4._3._0.ctor&&"RBNode_elm_builtin"===a._4._4.ctor&&"Black"===a._4._4._0.ctor)break c;else break a;default:if("RBNode_elm_builtin"===a._3._3.ctor&&"Red"===a._3._3._0.ctor)break g;
else if("RBNode_elm_builtin"===a._3._4.ctor&&"Red"===a._3._4._0.ctor)break f;else break a}case "NBlack":switch(a._4._0.ctor){case "Red":if("RBNode_elm_builtin"===a._4._3.ctor&&"Red"===a._4._3._0.ctor)break e;else if("RBNode_elm_builtin"===a._4._4.ctor&&"Red"===a._4._4._0.ctor)break d;else if("BBlack"===a._0.ctor&&"RBNode_elm_builtin"===a._3._3.ctor&&"Black"===a._3._3._0.ctor&&"RBNode_elm_builtin"===a._3._4.ctor&&"Black"===a._3._4._0.ctor)break b;else break a;case "NBlack":if("BBlack"===a._0.ctor)if("RBNode_elm_builtin"===
a._4._3.ctor&&"Black"===a._4._3._0.ctor&&"RBNode_elm_builtin"===a._4._4.ctor&&"Black"===a._4._4._0.ctor)break c;else if("RBNode_elm_builtin"===a._3._3.ctor&&"Black"===a._3._3._0.ctor&&"RBNode_elm_builtin"===a._3._4.ctor&&"Black"===a._3._4._0.ctor)break b;else break a;else break a;default:if("BBlack"===a._0.ctor&&"RBNode_elm_builtin"===a._3._3.ctor&&"Black"===a._3._3._0.ctor&&"RBNode_elm_builtin"===a._3._4.ctor&&"Black"===a._3._4._0.ctor)break b;else break a}default:switch(a._4._0.ctor){case "Red":if("RBNode_elm_builtin"===
a._4._3.ctor&&"Red"===a._4._3._0.ctor)break e;else if("RBNode_elm_builtin"===a._4._4.ctor&&"Red"===a._4._4._0.ctor)break d;else break a;case "NBlack":if("BBlack"===a._0.ctor&&"RBNode_elm_builtin"===a._4._3.ctor&&"Black"===a._4._3._0.ctor&&"RBNode_elm_builtin"===a._4._4.ctor&&"Black"===a._4._4._0.ctor)break c;else break a;default:break a}}else switch(a._3._0.ctor){case "Red":if("RBNode_elm_builtin"===a._3._3.ctor&&"Red"===a._3._3._0.ctor)break g;else if("RBNode_elm_builtin"===a._3._4.ctor&&"Red"===
a._3._4._0.ctor)break f;else break a;case "NBlack":if("BBlack"===a._0.ctor&&"RBNode_elm_builtin"===a._3._3.ctor&&"Black"===a._3._3._0.ctor&&"RBNode_elm_builtin"===a._3._4.ctor&&"Black"===a._3._4._0.ctor)break b;else break a;default:break a}else if("RBNode_elm_builtin"===a._4.ctor)switch(a._4._0.ctor){case "Red":if("RBNode_elm_builtin"===a._4._3.ctor&&"Red"===a._4._3._0.ctor)break e;else if("RBNode_elm_builtin"===a._4._4.ctor&&"Red"===a._4._4._0.ctor)break d;else break a;case "NBlack":if("BBlack"===
a._0.ctor&&"RBNode_elm_builtin"===a._4._3.ctor&&"Black"===a._4._3._0.ctor&&"RBNode_elm_builtin"===a._4._4.ctor&&"Black"===a._4._4._0.ctor)break c;else break a;default:break a}else break a;else break a;while(0);return Aa(a._0)(a._3._3._1)(a._3._3._2)(a._3._1)(a._3._2)(a._1)(a._2)(a._3._3._3)(a._3._3._4)(a._3._4)(a._4)}while(0);return Aa(a._0)(a._3._1)(a._3._2)(a._3._4._1)(a._3._4._2)(a._1)(a._2)(a._3._3)(a._3._4._3)(a._3._4._4)(a._4)}while(0);return Aa(a._0)(a._1)(a._2)(a._4._3._1)(a._4._3._2)(a._4._1)(a._4._2)(a._3)(a._4._3._3)(a._4._3._4)(a._4._4)}while(0);
return Aa(a._0)(a._1)(a._2)(a._4._1)(a._4._2)(a._4._4._1)(a._4._4._2)(a._3)(a._4._3)(a._4._4._3)(a._4._4._4)}while(0);return x(D,J,a._4._3._1,a._4._3._2,x(D,J,a._1,a._2,a._3,a._4._3._3),x(qa,J,a._4._1,a._4._2,a._4._3._4,rb(a._4._4)))}while(0);return x(D,J,a._3._4._1,a._3._4._2,x(qa,J,a._3._1,a._3._2,rb(a._3._3),a._3._4._3),x(D,J,a._1,a._2,a._3._4._4,a._4))}while(0);return a},qa=A(function(a,b,c,d,e){a=x(D,a,b,c,d,e);"RBNode_elm_builtin"===a.ctor?(b=a._0,b=p.eq(b,J)||p.eq(b,ob)):b=!0;return b?wc(a):
a}),Ba=A(function(a,b,c,d,e){return nb(d)||nb(e)?x(qa,sc(a),b,c,qb(d),qb(e)):x(D,a,b,c,d,e)}),tb=A(function(a,b,c,d,e){return"RBEmpty_elm_builtin"===e.ctor?r(sb,a,d,e):x(Ba,a,b,c,d,x(tb,e._0,e._1,e._2,e._3,e._4))}),sb=u(function(a,b,c){if("RBEmpty_elm_builtin"===b.ctor)if("RBEmpty_elm_builtin"===c.ctor)switch(a.ctor){case "Red":return ja(pa);case "Black":return ja(tc);default:return oa.crash("cannot have bblack or nblack nodes at this point")}else{var d=c._0;b=b._0;return"Black"===a.ctor&&"LBlack"===
b.ctor&&"Red"===d.ctor?x(D,J,c._1,c._2,c._3,c._4):Q(mb,"Black/LBlack/Red",a,Y(b),Y(d))}else{if("RBEmpty_elm_builtin"===c.ctor)return c=c._0,d=b._0,"Black"===a.ctor&&"Red"===d.ctor&&"LBlack"===c.ctor?x(D,J,b._1,b._2,b._3,b._4):Q(mb,"Black/Red/LBlack",a,Y(d),Y(c));var d=b._2,e=b._4,g=b._1;b=x(tb,b._0,g,d,b._3,e);d=r(qc,g,d,e);return x(Ba,a,d._0,d._1,b,c)}}),ub=e(function(a,b){if("RBEmpty_elm_builtin"===b.ctor)return ja(pa);var c=b._1;return x(D,b._0,c,g(a,c,b._2),g(ub,a,b._3),g(ub,a,b._4))}),Ca={ctor:"Same"},
Ma={ctor:"Remove"},Na={ctor:"Insert"},vb=u(function(a,b,c){var d=function(c){if("RBEmpty_elm_builtin"===c.ctor){var e=b(K);return"Nothing"===e.ctor?{ctor:"_Tuple2",_0:Ca,_1:W}:{ctor:"_Tuple2",_0:Na,_1:x(D,za,a,e._0,W,W)}}var f=c._2,h=c._4,k=c._3,e=c._1;c=c._0;switch(g(Xa,a,e).ctor){case "EQ":return f=b(L(f)),"Nothing"===f.ctor?{ctor:"_Tuple2",_0:Ma,_1:r(sb,c,k,h)}:{ctor:"_Tuple2",_0:Ca,_1:x(D,c,e,f._0,k,h)};case "LT":var k=d(k),n=k._0,k=k._1;switch(n.ctor){case "Same":return{ctor:"_Tuple2",_0:Ca,
_1:x(D,c,e,f,k,h)};case "Insert":return{ctor:"_Tuple2",_0:Na,_1:x(qa,c,e,f,k,h)};default:return{ctor:"_Tuple2",_0:Ma,_1:x(Ba,c,e,f,k,h)}}default:switch(h=d(h),n=h._0,h=h._1,n.ctor){case "Same":return{ctor:"_Tuple2",_0:Ca,_1:x(D,c,e,f,k,h)};case "Insert":return{ctor:"_Tuple2",_0:Na,_1:x(qa,c,e,f,k,h)};default:return{ctor:"_Tuple2",_0:Ma,_1:x(Ba,c,e,f,k,h)}}}};c=d(c);var e=c._1;switch(c._0.ctor){case "Same":return e;case "Insert":return uc(e);default:return vc(e)}}),ra=u(function(a,b,c){return r(vb,
a,ca(L(b)),c)});e(function(a,b){return r(ra,a,b,W)});e(function(a,b){return r(ia,ra,b,a)});var xc=e(function(a,b){var c=u(function(b,c,e){return g(a,b,c)?r(ra,b,c,e):e});return r(ia,c,W,b)});e(function(a,b){return g(xc,e(function(a,d){return g(pc,a,b)}),a)});e(function(a,b){var c=u(function(b,c,e){var d=e._1;e=e._0;return g(a,b,c)?{ctor:"_Tuple2",_0:r(ra,b,c,e),_1:d}:{ctor:"_Tuple2",_0:e,_1:r(ra,b,c,d)}});return r(ia,c,{ctor:"_Tuple2",_0:W,_1:W},b)});var yc=e(function(a,b){return r(vb,a,ca(K),b)});
e(function(a,b){return r(ia,u(function(a,b,e){return g(yc,a,e)}),a,b)});var M=function(){function a(a,b){return{ctor:"\x3cdecoder\x3e",tag:"map-many",func:a,decoders:b}}function b(a){return{tag:"ok",value:a}}function c(a,b){return{tag:"primitive",type:a,value:b}}function d(a,b){return{tag:"index",index:a,rest:b}}function d(a,b){return{tag:"index",index:a,rest:b}}function f(a){for(var b="_";a;)switch(a.tag){case "primitive":return b="Expecting "+a.type+("_"===b?"":" at "+b)+" but instead got: ",a=
a.value,a=void 0===a?"undefined":JSON.stringify(a),b+a;case "index":b+="["+a.index+"]";a=a.rest;break;case "field":b+="."+a.field;a=a.rest;break;case "oneOf":a=a.problems;for(var c=0;c<a.length;c++)a[c]=f(a[c]);return"I ran into the following problems"+("_"===b?"":" at "+b)+":\n\n"+a.join("\n");case "fail":return"I ran into a `fail` decoder"+("_"===b?"":" at "+b)+": "+a.msg}}function g(a,b){a=h(a,b);return"ok"===a.tag?N(a.value):y(f(a))}function h(a,e){switch(a.tag){case "bool":return"boolean"===
typeof e?b(e):c("a Bool",e);case "int":return"number"!==typeof e?c("an Int",e):-2147483647<e&&2147483647>e&&(e|0)===e||isFinite(e)&&!(e%1)?b(e):c("an Int",e);case "float":return"number"===typeof e?b(e):c("a Float",e);case "string":return"string"===typeof e?b(e):e instanceof String?b(e+""):c("a String",e);case "null":return null===e?b(a.value):c("null",e);case "value":return b(e);case "list":if(!(e instanceof Array))return c("a List",e);for(var f=B.Nil,k=e.length;k--;){var g=h(a.decoder,e[k]);if("ok"!==
g.tag)return d(k,g);f=B.Cons(g.value,f)}return b(f);case "array":if(!(e instanceof Array))return c("an Array",e);g=e.length;f=Array(g);for(k=g;k--;){g=h(a.decoder,e[k]);if("ok"!==g.tag)return d(k,g);f[k]=g.value}return b(P.fromJSArray(f));case "maybe":return g=h(a.decoder,e),"ok"===g.tag?b(L(g.value)):b(K);case "field":k=a.field;if("object"!==typeof e||null===e||!(k in e))return c("an object with a field named `"+k+"`",e);g=h(a.decoder,e[k]);return"ok"===g.tag?g:{tag:"field",field:k,rest:g};case "index":k=
a.index;if(!(e instanceof Array))return c("an array",e);if(k>=e.length)return c("a longer array. Need index "+k+" but there are only "+e.length+" entries",e);g=h(a.decoder,e[k]);return"ok"===g.tag?g:d(k,g);case "key-value":if("object"!==typeof e||null===e||e instanceof Array)return c("an object",e);k=B.Nil;for(f in e){g=h(a.decoder,e[f]);if("ok"!==g.tag)return{tag:"field",field:f,rest:g};g=p.Tuple2(f,g.value);k=B.Cons(g,k)}return b(k);case "map-many":f=a.func;a=a.decoders;for(k=0;k<a.length;k++){g=
h(a[k],e);if("ok"!==g.tag)return g;f=f(g.value)}return b(f);case "andThen":return g=h(a.decoder,e),"ok"!==g.tag?g:h(a.callback(g.value),e);case "oneOf":k=[];for(a=a.decoders;"[]"!==a.ctor;){g=h(a._0,e);if("ok"===g.tag)return g;k.push(g);a=a._1}return{tag:"oneOf",problems:k};case "fail":return{tag:"fail",msg:a.msg};case "succeed":return b(a.msg)}}function m(a,b){if(a===b)return!0;if(a.tag!==b.tag)return!1;switch(a.tag){case "succeed":case "fail":return a.msg===b.msg;case "bool":case "int":case "float":case "string":case "value":return!0;
case "null":return a.value===b.value;case "list":case "array":case "maybe":case "key-value":return m(a.decoder,b.decoder);case "field":return a.field===b.field&&m(a.decoder,b.decoder);case "index":return a.index===b.index&&m(a.decoder,b.decoder);case "map-many":return a.func!==b.func?!1:t(a.decoders,b.decoders);case "andThen":return a.callback===b.callback&&m(a.decoder,b.decoder);case "oneOf":return t(a.decoders,b.decoders)}}function t(a,b){var c=a.length;if(c!==b.length)return!1;for(var d=0;d<c;d++)if(!m(a[d],
b[d]))return!1;return!0}return{encode:e(function(a,b){return JSON.stringify(b,null,a)}),runOnString:e(function(a,b){try{var c=JSON.parse(b)}catch(Ga){return y("Given an invalid JSON: "+Ga.message)}return g(a,c)}),run:e(g),decodeNull:function(a){return{ctor:"\x3cdecoder\x3e",tag:"null",value:a}},decodePrimitive:function(a){return{ctor:"\x3cdecoder\x3e",tag:a}},decodeContainer:e(function(a,b){return{ctor:"\x3cdecoder\x3e",tag:a,decoder:b}}),decodeField:e(function(a,b){return{ctor:"\x3cdecoder\x3e",
tag:"field",field:a,decoder:b}}),decodeIndex:e(function(a,b){return{ctor:"\x3cdecoder\x3e",tag:"index",index:a,decoder:b}}),map1:e(function(b,c){return a(b,[c])}),map2:u(function(b,c,d){return a(b,[c,d])}),map3:w(function(b,c,d,e){return a(b,[c,d,e])}),map4:A(function(b,c,d,e,f){return a(b,[c,d,e,f])}),map5:F(function(b,c,d,e,f,g){return a(b,[c,d,e,f,g])}),map6:ua(function(b,c,d,e,f,g,h){return a(b,[c,d,e,f,g,h])}),map7:la(function(b,c,d,e,f,g,h,m){return a(b,[c,d,e,f,g,h,m])}),map8:Gb(function(b,
c,d,e,f,g,h,m,q){return a(b,[c,d,e,f,g,h,m,q])}),decodeKeyValuePairs:function(a){return{ctor:"\x3cdecoder\x3e",tag:"key-value",decoder:a}},andThen:e(function(a,b){return{ctor:"\x3cdecoder\x3e",tag:"andThen",decoder:b,callback:a}}),fail:function(a){return{ctor:"\x3cdecoder\x3e",tag:"fail",msg:a}},succeed:function(a){return{ctor:"\x3cdecoder\x3e",tag:"succeed",msg:a}},oneOf:function(a){return{ctor:"\x3cdecoder\x3e",tag:"oneOf",decoders:a}},identity:function(a){return a},encodeNull:null,encodeArray:P.toJSArray,
encodeList:B.toArray,encodeObject:function(a){for(var b={};"[]"!==a.ctor;){var c=a._0;b[c._0]=c._1;a=a._1}return b},equality:m}}(),zc=M.identity,Ac=M.identity,Bc=M.decodePrimitive("value"),Cc=M.succeed,Ka=M.run,Dc=M.map2,Oa=M.map1,sa=M.decodeField,wb=e(function(a,b){return r(S,sa,b,a)}),Ec=M.decodePrimitive("float"),Fc=M.decodePrimitive("int"),Gc=M.decodePrimitive("bool"),xb=M.decodePrimitive("string");e(function(a,b){return{ctor:"_Tuple2",_0:b._0,_1:a(b._1)}});e(function(a,b){return{ctor:"_Tuple2",
_0:a(b._0),_1:b._1}});var Hc=function(){function a(a){return function(b,c,d){return z.nativeBinding(function(e){function f(a){a=g(Ka,c,a);"Ok"===a.ctor&&z.rawSpawn(d(a._0))}a.addEventListener(b,f);return function(){a.removeEventListener(b,f)}})}}function b(a,b){return z.nativeBinding(function(c){f(function(){var d=document.getElementById(a);null===d?c(z.fail({ctor:"NotFound",_0:a})):c(z.succeed(b(d)))})})}var c={addEventListener:function(){},removeEventListener:function(){}},d=a("undefined"!==typeof document?
document:c),c=a("undefined"!==typeof window?window:c),f="undefined"!==typeof requestAnimationFrame?requestAnimationFrame:function(a){a()};return{onDocument:u(d),onWindow:u(c),focus:function(a){return b(a,function(a){a.focus();return p.Tuple0})},blur:function(a){return b(a,function(a){a.blur();return p.Tuple0})},getScrollTop:function(a){return b(a,function(a){return a.scrollTop})},setScrollTop:e(function(a,c){return b(a,function(a){a.scrollTop=c;return p.Tuple0})}),getScrollLeft:function(a){return b(a,
function(a){return a.scrollLeft})},setScrollLeft:e(function(a,c){return b(a,function(a){a.scrollLeft=c;return p.Tuple0})}),toBottom:function(a){return b(a,function(a){a.scrollTop=a.scrollHeight;return p.Tuple0})},toRight:function(a){return b(a,function(a){a.scrollLeft=a.scrollWidth;return p.Tuple0})},height:e(function(a,c){return b(c,function(b){switch(a.ctor){case "Content":return b.scrollHeight;case "VisibleContent":return b.clientHeight;case "VisibleContentWithBorders":return b.offsetHeight;case "VisibleContentWithBordersAndMargins":return b=
b.getBoundingClientRect(),b.bottom-b.top}})}),width:e(function(a,c){return b(c,function(b){switch(a.ctor){case "Content":return b.scrollWidth;case "VisibleContent":return b.clientWidth;case "VisibleContentWithBorders":return b.offsetWidth;case "VisibleContentWithBordersAndMargins":return b=b.getBoundingClientRect(),b.right-b.left}})})}}().focus,db,aa=function(){function a(a,b,c){return{type:"thunk",func:a,args:b,thunk:c,node:void 0}}function b(a){for(var b,c={};"[]"!==a.ctor;){var d=a._0,e=d.key;
if("ATTR"===e||"ATTR_NS"===e||"EVENT"===e){var l=c[e]||{};l[d.realKey]=d.value;c[e]=l}else if("STYLE"===e){l=c[e]||{};for(d=d.value;"[]"!==d.ctor;){var f=d._0;l[f._0]=f._1;d=d._1}c[e]=l}else"namespace"===e?b=d.value:"className"===e?(l=c[e],c[e]="undefined"===typeof l?d.value:l+" "+d.value):c[e]=d.value;a=a._1}return{facts:c,namespace:b}}function c(a,b,c){return{key:"EVENT",realKey:a,value:{options:b,decoder:c}}}function d(a,b){switch(a.type){case "thunk":return a.node||(a.node=a.thunk()),d(a.node,
b);case "tagger":var c=a.node;for(a=a.tagger;"tagger"===c.type;)"object"!==typeof a?a=[a,c.tagger]:a.push(c.tagger),c=c.node;b={tagger:a,parent:b};c=d(c,b);c.elm_event_node_ref=b;return c;case "text":return E.createTextNode(a.text);case "node":c=a.namespace?E.createElementNS(a.namespace,a.tag):E.createElement(a.tag);f(c,b,a.facts);a=a.children;for(var e=0;e<a.length;e++)c.appendChild(d(a[e],b));return c;case "keyed-node":c=a.namespace?E.createElementNS(a.namespace,a.tag):E.createElement(a.tag);f(c,
b,a.facts);a=a.children;for(e=0;e<a.length;e++)c.appendChild(d(a[e]._1,b));return c;case "custom":return c=a.impl.render(a.model),f(c,b,a.facts),c}}function f(a,b,c){for(var d in c){var e=c[d];switch(d){case "STYLE":var f=void 0,g=a.style;for(f in e)g[f]=e[f];break;case "EVENT":var f=void 0,g=a,l=b,v=e,k=g.elm_handlers||{};for(f in v){var e=k[f],G=v[f];"undefined"===typeof G?(g.removeEventListener(f,e),k[f]=void 0):"undefined"===typeof e?(e=h(l,G),g.addEventListener(f,e),k[f]=e):e.info=G}g.elm_handlers=
k;break;case "ATTR":f=void 0;g=a;for(f in e)l=e[f],"undefined"===typeof l?g.removeAttribute(f):g.setAttribute(f,l);break;case "ATTR_NS":f=void 0;g=a;for(f in e)v=e[f],l=v.namespace,v=v.value,"undefined"===typeof v?g.removeAttributeNS(l,f):g.setAttributeNS(l,f,v);break;case "value":a[d]!==e&&(a[d]=e);break;default:a[d]=e}}}function h(a,b){function c(b){var d=c.info,e=g(M.run,d.decoder,b);if("Ok"===e.ctor)for(d=d.options,d.stopPropagation&&b.stopPropagation(),d.preventDefault&&b.preventDefault(),b=
e._0,e=a;e;){d=e.tagger;if("function"===typeof d)b=d(b);else for(var f=d.length;f--;)b=d[f](b);e=e.parent}}c.info=b;return c}function t(a,b){var c=[];x(a,b,c,0);return c}function m(a,b,c){return{index:b,type:a,data:c,domNode:void 0,eventNode:void 0}}function x(a,b,c,d){if(a!==b){var e=b.type;if(a.type!==e)c.push(m("p-redraw",d,b));else switch(e){case "thunk":for(var f=a.args,g=b.args,l=f.length,v=a.func===b.func&&l===g.length;v&&l--;)v=f[l]===g[l];if(v){b.node=a.node;break}b.node=b.thunk();f=[];x(a.node,
b.node,f,0);0<f.length&&c.push(m("p-thunk",d,f));break;case "tagger":for(var v=a.tagger,f=b.tagger,h=!1,g=a.node;"tagger"===g.type;)h=!0,"object"!==typeof v?v=[v,g.tagger]:v.push(g.tagger),g=g.node;for(l=b.node;"tagger"===l.type;)h=!0,"object"!==typeof f?f=[f,l.tagger]:f.push(l.tagger),l=l.node;if(h&&v.length!==f.length){c.push(m("p-redraw",d,b));break}if(h){a:{for(h=0;h<v.length;h++)if(v[h]!==f[h]){v=!1;break a}v=!0}v=!v}else v=v!==f;v&&c.push(m("p-tagger",d,f));x(g,l,c,d+1);break;case "text":a.text!==
b.text&&c.push(m("p-text",d,b.text));break;case "node":if(a.tag!==b.tag||a.namespace!==b.namespace){c.push(m("p-redraw",d,b));break}e=k(a.facts,b.facts);"undefined"!==typeof e&&c.push(m("p-facts",d,e));f=a.children;g=b.children;l=f.length;v=g.length;l>v?c.push(m("p-remove-last",d,l-v)):l<v&&c.push(m("p-append",d,g.slice(l)));l=l<v?l:v;for(v=0;v<l;v++)d++,h=f[v],x(h,g[v],c,d),d+=h.descendantsCount||0;break;case "keyed-node":if(a.tag!==b.tag||a.namespace!==b.namespace){c.push(m("p-redraw",d,b));break}e=
k(a.facts,b.facts);"undefined"!==typeof e&&c.push(m("p-facts",d,e));var e=[],G={},ma=[];a=a.children;for(var p=b.children,t=a.length,u=p.length,q=0,r=0,w=d;q<t&&r<u;){var y=a[q];var z=p[r];var A=y._0,C=z._0;b=y._1;z=z._1;if(A===C)w++,x(b,z,e,w),w+=b.descendantsCount||0,q++,r++;else{y=q+1<t;var D=r+1<u;if(y){var F=a[q+1];g=F._0;var E=F._1;F=C===g}D&&(v=p[r+1],f=v._0,h=v._1,v=A===f);if(y&&D&&v&&F)w++,x(b,h,e,w),n(G,e,A,z,r,ma),w+=b.descendantsCount||0,w++,B(G,e,A,E,w),w+=E.descendantsCount||0,q+=2,
r+=2;else if(D&&v)w++,n(G,e,C,z,r,ma),x(b,h,e,w),w+=b.descendantsCount||0,q+=1,r+=2;else if(y&&F)w++,B(G,e,A,b,w),w+=b.descendantsCount||0,w++,x(E,z,e,w),w+=E.descendantsCount||0,q+=2,r+=1;else if(y&&D&&g===f)w++,B(G,e,A,b,w),n(G,e,C,z,r,ma),w+=b.descendantsCount||0,w++,x(E,h,e,w),w+=E.descendantsCount||0,q+=2,r+=2;else break}}for(;q<t;)w++,y=a[q],b=y._1,B(G,e,y._0,b,w),w+=b.descendantsCount||0,q++;for(;r<u;)l=l||[],z=p[r],n(G,e,z._0,z._1,void 0,l),r++;(0<e.length||0<ma.length||"undefined"!==typeof l)&&
c.push(m("p-reorder",d,{patches:e,inserts:ma,endInserts:l}));break;case "custom":a.impl!==b.impl?c.push(m("p-redraw",d,b)):(e=k(a.facts,b.facts),"undefined"!==typeof e&&c.push(m("p-facts",d,e)),(f=b.impl.diff(a,b))&&c.push(m("p-custom",d,f)))}}}function k(a,b,c){var d;for(d in a)if("STYLE"===d||"EVENT"===d||"ATTR"===d||"ATTR_NS"===d){var e=k(a[d],b[d]||{},d);if(e){var f=f||{};f[d]=e}}else if(d in b){var e=a[d],g=b[d],l;!(l=e===g&&"value"!==d)&&(l="EVENT"===c)&&(l=e.options===g.options||e.options.stopPropagation===
g.options.stopPropagation&&e.options.preventDefault===g.options.preventDefault?M.equality(e.decoder,g.decoder):!1);l||(f=f||{},f[d]=g)}else f=f||{},f[d]="undefined"===typeof c?"string"===typeof a[d]?"":null:"STYLE"===c?"":"EVENT"===c||"ATTR"===c?void 0:{namespace:a[d].namespace,value:void 0};for(var v in b)v in a||(f=f||{},f[v]=b[v]);return f}function n(a,b,c,d,e,f){var g=a[c];"undefined"===typeof g?(g={tag:"insert",vnode:d,index:e,data:void 0},f.push({index:e,entry:g}),a[c]=g):"remove"===g.tag?(f.push({index:e,
entry:g}),g.tag="move",a=[],x(g.vnode,d,a,g.index),g.index=e,g.data.data={patches:a,entry:g}):n(a,b,c+W,d,e,f)}function B(a,b,c,d,e){var f=a[c];"undefined"===typeof f?(f=m("p-remove",e,void 0),b.push(f),a[c]={tag:"remove",vnode:d,index:e,data:f}):"insert"===f.tag?(f.tag="move",a=[],x(d,f.vnode,a,e),f=m("p-remove",e,{patches:a,entry:f}),b.push(f)):B(a,b,c+W,d,e)}function y(a,b,c,d,e,f,g){for(var l,v=c[d],h=v.index;h===e;)if(l=v.type,"p-thunk"===l?(l=b.node,y(a,l,v.data,0,0,l.descendantsCount,g)):"p-reorder"===
l?(v.domNode=a,v.eventNode=g,l=v.data.patches,0<l.length&&y(a,b,l,0,e,f,g)):"p-remove"===l?(v.domNode=a,v.eventNode=g,l=v.data,"undefined"!==typeof l&&(l.entry.data=a,l=l.patches,0<l.length&&y(a,b,l,0,e,f,g))):(v.domNode=a,v.eventNode=g),d++,!(v=c[d])||(h=v.index)>f)return d;switch(b.type){case "tagger":for(g=b.node;"tagger"===g.type;)g=g.node;return y(a,g,c,d,e+1,f,a.elm_event_node_ref);case "node":b=b.children;for(var k=a.childNodes,G=0;G<b.length;G++){e++;l=b[G];a=e+(l.descendantsCount||0);if(e<=
h&&h<=a&&(d=y(k[G],l,c,d,e,a,g),!(v=c[d])||(h=v.index)>f))break;e=a}return d;case "keyed-node":b=b.children;k=a.childNodes;for(G=0;G<b.length;G++){e++;l=b[G]._1;a=e+(l.descendantsCount||0);if(e<=h&&h<=a&&(d=y(k[G],l,c,d,e,a,g),!(v=c[d])||(h=v.index)>f))break;e=a}return d;case "text":case "thunk":throw Error("should never traverse `text` or `thunk` nodes like this");}}function A(a,b,c,d){if(0===c.length)return a;y(a,b,c,0,0,b.descendantsCount,d);return D(a,c)}function D(a,b){for(var c=0;c<b.length;c++){var d=
b[c],e=d.domNode,d=H(e,d);e===a&&(a=d)}return a}function H(a,b){switch(b.type){case "p-redraw":var c=a.parentNode;b=d(b.data,b.eventNode);"undefined"===typeof b.elm_event_node_ref&&(b.elm_event_node_ref=a.elm_event_node_ref);c&&b!==a&&c.replaceChild(b,a);return b;case "p-facts":return f(a,b.eventNode,b.data),a;case "p-text":return a.replaceData(0,a.length,b.data),a;case "p-thunk":return D(a,b.data);case "p-tagger":return"undefined"!==typeof a.elm_event_node_ref?a.elm_event_node_ref.tagger=b.data:
a.elm_event_node_ref={tagger:b.data,parent:b.eventNode},a;case "p-remove-last":for(c=b.data;c--;)a.removeChild(a.lastChild);return a;case "p-append":for(var e=b.data,c=0;c<e.length;c++)a.appendChild(d(e[c],b.eventNode));return a;case "p-remove":b=b.data;if("undefined"===typeof b)return a.parentNode.removeChild(a),a;c=b.entry;"undefined"!==typeof c.index&&a.parentNode.removeChild(a);c.data=D(a,b.patches);return a;case "p-reorder":e=b.data;c=e.endInserts;if("undefined"!==typeof c){for(var g=E.createDocumentFragment(),
h=0;h<c.length;h++){var l=c[h].entry;g.appendChild("move"===l.tag?l.data:d(l.vnode,b.eventNode))}c=g}else c=void 0;a=D(a,e.patches);e=e.inserts;for(g=0;g<e.length;g++)h=e[g],l=h.entry,l="move"===l.tag?l.data:d(l.vnode,b.eventNode),a.insertBefore(l,a.childNodes[h.index]);"undefined"!==typeof c&&a.appendChild(c);return a;case "p-custom":return b=b.data,b.applyPatch(a,b.data);default:throw Error("Ran into an unknown patch!");}}function I(a){return e(function(b,c){return function(d){return function(e,
f,h){var l=a(d,f);"undefined"===typeof h?K(c,e,f,l):C(g(b,h,c),e,f,l)}}})}function F(a,b){b&&(b.innerHTML='\x3cdiv style\x3d"padding-left:1em;"\x3e\x3ch2 style\x3d"font-weight:normal;"\x3e\x3cb\x3eOops!\x3c/b\x3e Something went wrong when starting your Elm program.\x3c/h2\x3e\x3cpre style\x3d"padding-left:1em;"\x3e'+a+"\x3c/pre\x3e\x3c/div\x3e");throw Error(a);}function K(a,b,c,d){b.embed=function(b,c){for(;b.lastChild;)b.removeChild(b.lastChild);return T.initialize(d(a.init,c,b),a.update,a.subscriptions,
J(b,a.view))};b.fullscreen=function(b){return T.initialize(d(a.init,b,document.body),a.update,a.subscriptions,J(document.body,a.view))}}function J(a,b){return function(c,e){c={tagger:c,parent:void 0};e=b(e);var f=d(e,c);a.appendChild(f);return L(f,b,e,c)}}function L(a,b,c,d){function e(){switch(f){case "NO_REQUEST":throw Error("Unexpected draw callback.\nPlease report this to \x3chttps://github.com/elm-lang/virtual-dom/issues\x3e.");case "PENDING_REQUEST":Y(e);f="EXTRA_REQUEST";var c=b(h),k=t(g,c);
a=A(a,g,k,d);g=c;break;case "EXTRA_REQUEST":f="NO_REQUEST"}}var f="NO_REQUEST",g=c,h;return function(a){"NO_REQUEST"===f&&Y(e);f="PENDING_REQUEST";h=a}}function C(a,b,c,d){b.fullscreen=function(b){var e={doc:void 0};return T.initialize(d(a.init,b,document.body),a.update(N(e)),a.subscriptions,P(c,document.body,e,a.view,a.viewIn,a.viewOut))};b.embed=function(b,e){var f={doc:void 0};return T.initialize(d(a.init,e,b),a.update(N(f)),a.subscriptions,P(c,b,f,a.view,a.viewIn,a.viewOut))}}function N(a){return z.nativeBinding(function(b){var c=
a.doc;c&&(c=c.getElementsByClassName("debugger-sidebar-messages")[0])&&(c.scrollTop=c.scrollHeight);b(z.succeed(p.Tuple0))})}function P(a,b,c,e,f,g){return function(h,k){var l={tagger:h,parent:void 0};h={tagger:h,parent:void 0};var v=e(k),m=d(v,l);b.appendChild(m);var q=L(m,e,v,l),v=f(k)._1,m=d(v,h);b.appendChild(m);var l=S(l,m,f),n=L(m,l,v,h),p=Q(k,g,h,b,a,c);return function(a){q(a);n(a);p(a)}}}function Q(a,b,c,d,e,f){var g,h;return function(a){if(a.isDebuggerOpen)if(f.doc){E=f.doc;a=b(a);var d=
t(g,a);h=A(h,g,d,c);g=a;E=document}else g=b(a),h=R(e,f,g,c)}}function R(a,b,c,e){function f(){b.doc=void 0;g.close()}var g=window.open("","","width\x3d900,height\x3d360,left\x3d"+(screen.width-900)+",top\x3d"+(screen.height-360));E=g.document;b.doc=E;E.title="Debugger - "+a;E.body.style.margin="0";E.body.style.padding="0";a=d(c,e);E.body.appendChild(a);E.addEventListener("keydown",function(a){a.metaKey&&82===a.which&&window.location.reload();38===a.which&&(e.tagger({ctor:"Up"}),a.preventDefault());
40===a.which&&(e.tagger({ctor:"Down"}),a.preventDefault())});window.addEventListener("unload",f);g.addEventListener("unload",function(){b.doc=void 0;window.removeEventListener("unload",f);e.tagger({ctor:"Close"})});E=document;return a}function S(a,b,c){var d=aa(b),e="Normal",f,g=a.tagger,h=function(){};return function(b){b=c(b);var k=b._0.ctor;a.tagger="Normal"===k?g:h;e!==k&&(U("removeEventListener",d,e),U("addEventListener",d,k),"Normal"===e&&(f=document.body.style.overflow,document.body.style.overflow=
"hidden"),"Normal"===k&&(document.body.style.overflow=f),e=k);return b._1}}function U(a,b,c){switch(c){case "Pause":return V(a,b,Z);case "Message":return V(a,b,ea)}}function V(a,b,c){for(var d=0;d<c.length;d++)document.body[a](c[d],b,!0)}function aa(a){return function(b){if("keydown"!==b.type||!b.metaKey||82!==b.which){for(var c="scroll"===b.type||"wheel"===b.type,d=b.target;null!==d;){if("elm-overlay-message-details"===d.className&&c||d===a&&!c)return;d=d.parentNode}b.stopPropagation();b.preventDefault()}}}
var E="undefined"!==typeof document?document:{},W="_elmW6BL",X=I(function(a,b){return function(a,c,d){if("undefined"===typeof c)return a;F("The `"+b+"` module does not need flags.\nInitialize it with no arguments and you should be all set!",d)}}),ca=I(function(a,b){return function(c,d,e){if("undefined"===typeof a){var f="Are you trying to sneak a Never value into Elm? Trickster!\nIt looks like "+b+".main is defined with `programWithFlags` but has type `Program Never`.\nUse `program` instead if you do not want flags.";
F(f,e)}d=g(M.run,a,d);if("Ok"===d.ctor)return c(d._0);f="Trying to initialize the `"+b+"` module with an unexpected flag.\nI tried to convert it to an Elm value, but ran into this problem:\n\n"+d._0;F(f,e)}}),Y="undefined"!==typeof requestAnimationFrame?requestAnimationFrame:function(a){setTimeout(a,1E3/60)},Z="click dblclick mousemove mouseup mousedown mouseenter mouseleave touchstart touchend touchcancel touchmove pointerdown pointerup pointerover pointerout pointerenter pointerleave pointermove pointercancel dragstart drag dragend dragenter dragover dragleave drop keyup keydown keypress input change focus blur".split(" "),
ea=Z.concat("wheel","scroll");return{node:function(a){return e(function(c,d){var e=b(c);c=e.namespace;for(var e=e.facts,f=[],g=0;"[]"!==d.ctor;){var h=d._0,g=g+(h.descendantsCount||0);f.push(h);d=d._1}g+=f.length;return{type:"node",tag:a,facts:e,children:f,namespace:c,descendantsCount:g}})},text:function(a){return{type:"text",text:a}},custom:function(a,c,d){return{type:"custom",facts:b(a).facts,model:c,impl:d}},map:e(function(a,b){return{type:"tagger",tagger:a,node:b,descendantsCount:1+(b.descendantsCount||
0)}}),on:u(c),style:function(a){return{key:"STYLE",value:a}},property:e(function(a,b){return{key:a,value:b}}),attribute:e(function(a,b){return{key:"ATTR",realKey:a,value:b}}),attributeNS:u(function(a,b,c){return{key:"ATTR_NS",realKey:b,value:{value:c,namespace:a}}}),mapProperty:e(function(a,b){return"EVENT"!==b.key?b:c(b.realKey,b.value.options,g(Oa,a,b.value.decoder))}),lazy:e(function(b,c){return a(b,[c],function(){return b(c)})}),lazy2:u(function(b,c,d){return a(b,[c,d],function(){return g(b,c,
d)})}),lazy3:w(function(b,c,d,e){return a(b,[c,d,e],function(){return r(b,c,d,e)})}),keyedNode:u(function(a,c,d){var e=b(c);c=e.namespace;for(var e=e.facts,f=[],g=0;"[]"!==d.ctor;){var h=d._0,g=g+(h._1.descendantsCount||0);f.push(h);d=d._1}g+=f.length;return{type:"keyed-node",tag:a,facts:e,children:f,namespace:c,descendantsCount:g}}),program:X,programWithFlags:ca,staticProgram:function(a){var b=p.Tuple2(p.Tuple0,da);return g(X,db,{init:b,view:function(){return a},update:e(function(){return b}),subscriptions:function(){return gb}})()}}}(),
yb={stopPropagation:!1,preventDefault:!1},Ic=aa.on,Pa=e(function(a,b){return r(Ic,a,yb,b)}),Qa=aa.style,zb=aa.property,X=aa.text,h=aa.node;e(function(a,b){return{stopPropagation:a,preventDefault:b}});h("body");h("section");h("nav");h("article");h("aside");h("h1");h("h2");h("h3");h("h4");h("h5");h("h6");h("header");h("footer");h("address");h("main");h("p");h("hr");h("pre");h("blockquote");h("ol");var Jc=h("ul"),Kc=h("li");h("dl");h("dt");h("dd");h("figure");h("figcaption");var ta=h("div");h("a");h("em");
h("strong");h("small");h("s");h("cite");h("q");h("dfn");h("abbr");h("time");h("code");h("var");h("samp");h("kbd");h("sub");h("sup");h("i");h("b");h("u");h("mark");h("ruby");h("rt");h("rp");h("bdi");h("bdo");h("span");h("br");h("wbr");h("ins");h("del");h("img");h("iframe");h("embed");h("object");h("param");h("video");h("audio");h("source");h("track");h("canvas");h("math");var Lc=h("table");h("caption");h("colgroup");h("col");var Mc=h("tbody"),Nc=h("thead"),Oc=h("tfoot"),Ra=h("tr"),Ab=h("td"),Da=h("th");
h("form");h("fieldset");h("legend");h("label");var Bb=h("input"),Pc=h("button");h("select");h("datalist");h("optgroup");h("option");h("textarea");h("keygen");h("output");h("progress");h("meter");h("details");h("summary");h("menuitem");h("menu");var ka=e(function(a,b){return g(zb,a,Ac(b))}),U=function(a){return g(ka,"className",a)};e(function(a,b){return g(zb,a,zc(b))});g(sa,"keyCode",Fc);g(wb,{ctor:"::",_0:"target",_1:{ctor:"::",_0:"checked",_1:{ctor:"[]"}}},Gc);var Cb=g(wb,{ctor:"::",_0:"target",
_1:{ctor:"::",_0:"value",_1:{ctor:"[]"}}},xb);p.update(yb,{preventDefault:!0});var Ea=function(a){return g(Pa,"click",Cc(a))};e(function(a,b){return{stopPropagation:a,preventDefault:b}});var Qc=function(a){var b=e(function(b,d){b=a(b);return"Nothing"===b.ctor?K:g(Z,e(function(a,b){return{ctor:"::",_0:a,_1:b}})(b._0),d)});return g(S,b,L({ctor:"[]"}))},Rc=e(function(a,b){return g(jc,kb(a),kb(b.name))});T.outgoingPort("remember",function(a){return[a._0,a._1]});T.outgoingPort("forget",function(a){return a});
var Db=w(function(a,b,c,d){return{foods:a,ingredients:b,input:c,sidebarOpen:d}}),Sc=e(function(a,b){return{name:a,carbs:b}}),Tc=r(Dc,Sc,g(sa,"name",xb),g(sa,"carbs",Ec)),Uc=e(function(a,b){return{ctor:"UpdateIngredient",_0:a,_1:b}}),Vc=e(function(a,b){return g(Ra,{ctor:"[]"},{ctor:"::",_0:g(Ab,{ctor:"::",_0:Ea({ctor:"RemoveIngredient",_0:a}),_1:{ctor:"[]"}},{ctor:"::",_0:X(b._0.name),_1:{ctor:"[]"}}),_1:{ctor:"::",_0:g(Ab,{ctor:"[]"},{ctor:"::",_0:g(ta,{ctor:"::",_0:U(g(Ya,"has-error",g(Z,ca(""),
b._2))),_1:{ctor:"[]"}},{ctor:"::",_0:g(Bb,{ctor:"::",_0:g(ka,"type","number"),_1:{ctor:"::",_0:U("form-control"),_1:{ctor:"::",_0:g(ka,"value",b._1),_1:{ctor:"::",_0:g(Pa,"input",g(Oa,Uc(a),Cb)),_1:{ctor:"[]"}}}}},{ctor:"[]"}),_1:{ctor:"[]"}}),_1:{ctor:"[]"}}),_1:{ctor:"[]"}}})}),Wc=function(a){var b=g(Ya,"Nepp",g(Z,function(a){return r(Ib,mc,"g",Y(a))},g(Z,function(a){return Jb(Kb(10*a))/10},g(Z,Ob,g(Qc,function(a){return g(Z,function(b){return a._0.carbs*b/100},a._2)},a)))));return g(Lc,{ctor:"::",
_0:U("table"),_1:{ctor:"[]"}},{ctor:"::",_0:g(Nc,{ctor:"[]"},{ctor:"::",_0:g(Ra,{ctor:"[]"},{ctor:"::",_0:g(Da,{ctor:"[]"},{ctor:"::",_0:X("Ingredienser"),_1:{ctor:"[]"}}),_1:{ctor:"::",_0:g(Da,{ctor:"::",_0:Qa({ctor:"::",_0:{ctor:"_Tuple2",_0:"width",_1:"100px"},_1:{ctor:"[]"}}),_1:{ctor:"[]"}},{ctor:"::",_0:X("Vikt (g)"),_1:{ctor:"[]"}}),_1:{ctor:"[]"}}}),_1:{ctor:"[]"}}),_1:{ctor:"::",_0:g(Mc,{ctor:"[]"},g(cb,Vc,a)),_1:{ctor:"::",_0:g(Oc,{ctor:"[]"},{ctor:"::",_0:g(Ra,{ctor:"[]"},{ctor:"::",_0:g(Da,
{ctor:"[]"},{ctor:"::",_0:X("Kolhydrater"),_1:{ctor:"[]"}}),_1:{ctor:"::",_0:g(Da,{ctor:"[]"},{ctor:"::",_0:X(b),_1:{ctor:"[]"}}),_1:{ctor:"[]"}}}),_1:{ctor:"[]"}}),_1:{ctor:"[]"}}}})},Eb={ctor:"ToggleSidebar"},Xc=function(a){return{ctor:"UpdateInput",_0:a}},Yc=function(a){var b=a.sidebarOpen,c=a.input,d=function(a){return g(Kc,{ctor:"::",_0:U("list-group-item"),_1:{ctor:"::",_0:Ea({ctor:"AddIngredient",_0:{ctor:"_Tuple3",_0:a,_1:"",_2:K}}),_1:{ctor:"[]"}}},{ctor:"::",_0:X(a.name),_1:{ctor:"[]"}})};
return g(ta,{ctor:"[]"},{ctor:"::",_0:g(ta,{ctor:"::",_0:Qa({ctor:"::",_0:{ctor:"_Tuple2",_0:"position",_1:"fixed"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"top",_1:"0"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"left",_1:"0"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"right",_1:"0"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"bottom",_1:b?"0":"auto"},_1:{ctor:"[]"}}}}}}),_1:{ctor:"::",_0:Ea(Eb),_1:{ctor:"[]"}}},{ctor:"[]"}),_1:{ctor:"::",_0:g(ta,{ctor:"::",_0:Qa({ctor:"::",_0:{ctor:"_Tuple2",_0:"position",_1:"fixed"},
_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"top",_1:"0"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"right",_1:"0"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"bottom",_1:"0"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"width",_1:"200px"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"margin-bottom",_1:"0"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"overflow-y",_1:"scroll"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"transform",_1:b?"none":"translateX(200px)"},_1:{ctor:"[]"}}}}}}}}}),_1:{ctor:"::",_0:U("panel panel-default"),_1:{ctor:"[]"}}},{ctor:"::",
_0:g(Bb,{ctor:"::",_0:U("form-control"),_1:{ctor:"::",_0:g(ka,"id","search"),_1:{ctor:"::",_0:g(Pa,"input",g(Oa,Xc,Cb)),_1:{ctor:"::",_0:g(ka,"placeholder","Skriv f\u00f6r att s\u00f6ka"),_1:{ctor:"::",_0:g(ka,"value",c),_1:{ctor:"[]"}}}}}},{ctor:"[]"}),_1:{ctor:"::",_0:g(Jc,{ctor:"::",_0:U("list-group"),_1:{ctor:"[]"}},0<p.cmp(kc(c),1)?g(Ia,d,g(Pb,Rc(c),a.foods)):{ctor:"[]"}),_1:{ctor:"[]"}}}),_1:{ctor:"[]"}}})},Zc={ctor:"Noop"},Fb=g(aa.programWithFlags,void 0,{init:function(a){a=g(Ka,g(sa,"food",
g(M.decodeContainer,"list",Tc)),a);return"Ok"===a.ctor?{ctor:"_Tuple2",_0:Q(Db,a._0,{ctor:"[]"},"",!0),_1:da}:{ctor:"_Tuple2",_0:Q(Db,{ctor:"[]"},{ctor:"[]"},"",!0),_1:da}},update:e(function(a,b){switch(a.ctor){case "Noop":return{ctor:"_Tuple2",_0:b,_1:da};case "UpdateInput":return{ctor:"_Tuple2",_0:p.update(b,{input:a._0}),_1:da};case "AddIngredient":return{ctor:"_Tuple2",_0:p.update(b,{input:"",ingredients:{ctor:"::",_0:a._0,_1:b.ingredients}}),_1:g(gc,ca(Zc),Hc("search"))};case "ToggleSidebar":return{ctor:"_Tuple2",
_0:p.update(b,{sidebarOpen:!b.sidebarOpen}),_1:da};case "UpdateIngredient":var c=a._1,d=e(function(b,d){var e=d._0;p.eq(b,a._0)?(b=ic(c),b="Ok"===b.ctor?L(b._0):K,e={ctor:"_Tuple3",_0:e,_1:c,_2:b}):e={ctor:"_Tuple3",_0:e,_1:d._1,_2:d._2};return e}),d=g(cb,d,b.ingredients);return{ctor:"_Tuple2",_0:p.update(b,{ingredients:d}),_1:da};default:return d=a._0,d=g(t["++"],g(Ub,d,b.ingredients),g(Lb,d+1,b.ingredients)),{ctor:"_Tuple2",_0:p.update(b,{ingredients:d}),_1:da}}}),view:function(a){return g(ta,{ctor:"[]"},
{ctor:"::",_0:g(Pc,{ctor:"::",_0:U("btn btn-success btn-lg btn-block"),_1:{ctor:"::",_0:Ea(Eb),_1:{ctor:"[]"}}},{ctor:"::",_0:X("L\u00e4gg till ingrediens"),_1:{ctor:"[]"}}),_1:{ctor:"::",_0:Wc(a.ingredients),_1:{ctor:"::",_0:Yc(a),_1:{ctor:"[]"}}}})},subscriptions:ca(gb)})(Bc),V={};V.Main=V.Main||{};"undefined"!==typeof Fb&&Fb(V.Main,"Main",void 0);if("function"===typeof define&&define.amd)define([],function(){return V});else if("object"===typeof module)module.exports=V;else{var Sa=this.Elm;if("undefined"===
typeof Sa)this.Elm=V;else for(var Fa in V){if(Fa in Sa)throw Error("There are two Elm modules called `"+Fa+"` on this page! Rename one of them.");Sa[Fa]=V[Fa]}}}).call(this);
