var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(e,t,w){if(null==e)throw new TypeError("The 'this' value for String.prototype."+w+" must not be null or undefined");if(t instanceof RegExp)throw new TypeError("First argument to String.prototype."+w+" must not be a regular expression");return e+""};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(e,t,w){e!=Array.prototype&&e!=Object.prototype&&(e[t]=w.value)};$jscomp.getGlobal=function(e){return"undefined"!=typeof window&&window===e?e:"undefined"!=typeof global&&null!=global?global:e};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(e,t,w,y){if(t){w=$jscomp.global;e=e.split(".");for(y=0;y<e.length-1;y++){var F=e[y];F in w||(w[F]={});w=w[F]}e=e[e.length-1];y=w[e];t=t(y);t!=y&&null!=t&&$jscomp.defineProperty(w,e,{configurable:!0,writable:!0,value:t})}};
$jscomp.polyfill("String.prototype.endsWith",function(e){return e?e:function(e,w){var t=$jscomp.checkStringArgs(this,e,"endsWith");e+="";void 0===w&&(w=t.length);w=Math.max(0,Math.min(w|0,t.length));for(var F=e.length;0<F&&0<w;)if(t[--w]!=e[--F])return!1;return 0>=F}},"es6-impl","es3");
$jscomp.polyfill("String.prototype.startsWith",function(e){return e?e:function(e,w){var t=$jscomp.checkStringArgs(this,e,"startsWith");e+="";var F=t.length,ta=e.length;w=Math.max(0,Math.min(w|0,t.length));for(var ka=0;ka<ta&&w<F;)if(t[w++]!=e[ka++])return!1;return ka>=ta}},"es6-impl","es3");
$jscomp.polyfill("String.prototype.repeat",function(e){return e?e:function(e){var t=$jscomp.checkStringArgs(this,null,"repeat");if(0>e||1342177279<e)throw new RangeError("Invalid count value");e|=0;for(var y="";e;)if(e&1&&(y+=t),e>>>=1)t+=t;return y}},"es6-impl","es3");
(function(){function e(a){function b(b){return function(d){return a(b,d)}}b.arity=2;b.func=a;return b}function t(a){function b(b){return function(d){return function(c){return a(b,d,c)}}}b.arity=3;b.func=a;return b}function w(a){function b(b){return function(d){return function(c){return function(g){return a(b,d,c,g)}}}}b.arity=4;b.func=a;return b}function y(a){function b(b){return function(d){return function(c){return function(g){return function(v){return a(b,d,c,g,v)}}}}}b.arity=5;b.func=a;return b}
function F(a){function b(b){return function(d){return function(c){return function(g){return function(v){return function(p){return a(b,d,c,g,v,p)}}}}}}b.arity=6;b.func=a;return b}function ta(a){function b(b){return function(d){return function(c){return function(g){return function(v){return function(p){return function(e){return a(b,d,c,g,v,p,e)}}}}}}}b.arity=7;b.func=a;return b}function ka(a){function b(b){return function(d){return function(c){return function(g){return function(v){return function(p){return function(e){return function(k){return a(b,
d,c,g,v,p,e,k)}}}}}}}}b.arity=8;b.func=a;return b}function Ib(a){function b(b){return function(d){return function(c){return function(g){return function(v){return function(p){return function(e){return function(k){return function(m){return a(b,d,c,g,v,p,e,k,m)}}}}}}}}}b.arity=9;b.func=a;return b}function f(a,b,c){return 2===a.arity?a.func(b,c):a(b)(c)}function r(a,b,c,d){return 3===a.arity?a.func(b,c,d):a(b)(c)(d)}function S(a,b,c,d,g){return 4===a.arity?a.func(b,c,d,g):a(b)(c)(d)(g)}function x(a,b,
c,d,g,v){return 5===a.arity?a.func(b,c,d,g,v):a(b)(c)(d)(g)(v)}var P=function(){function a(b,d,c){c=fa(c);if(0===c.height)c.table[b]=d;else{var k=x(b,c);0<k&&(b-=c.lengths[k-1]);c.table[k]=a(b,d,c.table[k])}return c}function b(a,d,c,k){if(0===d){var p=Array((k-c)%33);for(var m=0;m<p.length;m++)p[m]=a(c+m);return{ctor:"_Array",height:0,table:p}}var E=Math.pow(32,d);p=Array(Math.ceil((k-c)/E));for(var g=Array(p.length),m=0;m<p.length;m++)p[m]=b(a,d-1,c+m*E,Math.min(c+(m+1)*E,k)),g[m]=C(p[m])+(0<m?g[m-
1]:0);return{ctor:"_Array",height:d,table:p,lengths:g}}function c(a,b){var d=a.height;b.length===d&&b.push({ctor:"_Array",height:d+1,table:[],lengths:[]});b[d].table.push(a);a=C(a);0<b[d].lengths.length&&(a+=b[d].lengths[b[d].lengths.length-1]);b[d].lengths.push(a);32===b[d].table.length&&(c(b[d],b),b[d]={ctor:"_Array",height:d+1,table:[],lengths:[]})}function d(a,b){if(0===b.height)return 32>b.table.length?(b={ctor:"_Array",height:0,table:b.table.slice()},b.table.push(a),b):null;var c=d(a,b.table[b.table.length-
1]);return null!==c?(b=fa(b),b.table[b.table.length-1]=c,b.lengths[b.lengths.length-1]++,b):32>b.table.length?(a=w(a,b.height-1),b=fa(b),b.table.push(a),b.lengths.push(b.lengths[b.lengths.length-1]+C(a)),b):null}function g(a,b){for(var d=b.table.length-1;0<=d;d--)a=0===b.height?B.Cons(b.table[d],a):g(a,b.table[d]);return a}function v(a,b){var d={ctor:"_Array",height:b.height,table:Array(b.table.length)};0<b.height&&(d.lengths=b.lengths);for(var c=0;c<b.table.length;c++)d.table[c]=0===b.height?a(b.table[c]):
v(a,b.table[c]);return d}function ua(a,b,d){var c={ctor:"_Array",height:b.height,table:Array(b.table.length)};0<b.height&&(c.lengths=b.lengths);for(var k=0;k<b.table.length;k++)c.table[k]=0===b.height?f(a,d+k,b.table[k]):ua(a,b.table[k],0==k?d:d+b.lengths[k-1]);return c}function p(a,b,d){if(0===d.height)for(var c=0;c<d.table.length;c++)b=f(a,d.table[c],b);else for(c=0;c<d.table.length;c++)b=p(a,b,d.table[c]);return b}function Wa(a,b,d){if(0===d.height)for(var c=d.table.length;c--;)b=f(a,d.table[c],
b);else for(c=d.table.length;c--;)b=Wa(a,b,d.table[c]);return b}function k(a,b){if(a===C(b))return b;if(0===b.height){var d={ctor:"_Array",height:0};d.table=b.table.slice(0,a);return d}var c=x(a,b);a=k(a-(0<c?b.lengths[c-1]:0),b.table[c]);if(0===c)return a;d={ctor:"_Array",height:b.height,table:b.table.slice(0,c),lengths:b.lengths.slice(0,c)};0<a.table.length&&(d.table[c]=a,d.lengths[c]=C(a)+(0<c?d.lengths[c-1]:0));return d}function m(a,b){if(0===a)return b;if(0===b.height){var d={ctor:"_Array",height:0};
d.table=b.table.slice(a,b.table.length+1);return d}d=x(a,b);a=m(a-(0<d?b.lengths[d-1]:0),b.table[d]);if(d===b.table.length-1)return a;d={ctor:"_Array",height:b.height,table:b.table.slice(d,b.table.length+1),lengths:Array(b.table.length-d)};d.table[0]=a;for(a=b=0;a<d.table.length;a++)b+=C(d.table[a]),d.lengths[a]=b;return d}function ga(a,b){if(0===a.height&&0===b.height)return[a,b];if(1!==a.height||1!==b.height)if(a.height===b.height){a=fa(a);b=fa(b);var d=ga(a.table[a.table.length-1],b.table[0]);
h(a,d[1]);n(b,d[0])}else if(a.height>b.height)a=fa(a),d=ga(a.table[a.table.length-1],b),h(a,d[0]),b=z(d[1],d[1].height+1);else{b=fa(b);d=ga(a,b.table[0]);a=0===d[0].table.length?0:1;var c=0===a?1:0;n(b,d[a]);a=z(d[c],d[c].height+1)}if(0===a.table.length||0===b.table.length)return[a,b];d=q(a,b);return 2>=d?[a,b]:Xa(a,b,d)}function h(a,b){var d=a.table.length-1;a.table[d]=b;a.lengths[d]=C(b);a.lengths[d]+=0<d?a.lengths[d-1]:0}function n(a,b){if(0<b.table.length){a.table[0]=b;a.lengths[0]=C(b);b=C(a.table[0]);
for(var d=1;d<a.lengths.length;d++)b+=C(a.table[d]),a.lengths[d]=b}else{a.table.shift();for(d=1;d<a.lengths.length;d++)a.lengths[d]-=a.lengths[0];a.lengths.shift()}}function q(a,b){for(var d=0,c=0;c<a.table.length;c++)d+=a.table[c].table.length;for(c=0;c<b.table.length;c++)d+=b.table[c].table.length;return a.table.length+b.table.length-(Math.floor((d-1)/32)+1)}function r(a,b,d){return d<a.length?a[d]:b[d-a.length]}function va(a,b,d,c){d<a.length?a[d]=c:b[d-a.length]=c}function Ja(a,b,d,c){va(a.table,
b.table,d,c);var k=0===d||d===a.lengths.length?0:r(a.lengths,a.lengths,d-1);va(a.lengths,b.lengths,d,k+C(c))}function wa(a,b){0>b&&(b=0);var d={ctor:"_Array",height:a,table:Array(b)};0<a&&(d.lengths=Array(b));return d}function Xa(a,b,d){for(var c=wa(a.height,Math.min(32,a.table.length+b.table.length-d)),k=wa(a.height,c.table.length-(a.table.length+b.table.length-d)),p=0;0===r(a.table,b.table,p).table.length%32;)va(c.table,k.table,p,r(a.table,b.table,p)),va(c.lengths,k.lengths,p,r(a.lengths,b.lengths,
p)),p++;for(var m=p,g=new wa(a.height-1,0),l=0;p-m-(0<g.table.length?1:0)<d;){var u=r(a.table,b.table,p),v=Math.min(32-g.table.length,u.table.length);g.table=g.table.concat(u.table.slice(l,v));if(0<g.height)for(var e=g.lengths.length,da=e;da<e+v-l;da++)g.lengths[da]=C(g.table[da]),g.lengths[da]+=0<da?g.lengths[da-1]:0;l+=v;u.table.length<=v&&(p++,l=0);32===g.table.length&&(Ja(c,k,m,g),g=wa(a.height-1,0),m++)}0<g.table.length&&(Ja(c,k,m,g),m++);for(;p<a.table.length+b.table.length;)Ja(c,k,m,r(a.table,
b.table,p)),p++,m++;return[c,k]}function fa(a){var b={ctor:"_Array",height:a.height,table:a.table.slice()};0<a.height&&(b.lengths=a.lengths.slice());return b}function C(a){return 0===a.height?a.table.length:a.lengths[a.lengths.length-1]}function x(a,b){for(var d=a>>5*b.height;b.lengths[d]<=a;)d++;return d}function w(a,b){return 0===b?{ctor:"_Array",height:0,table:[a]}:{ctor:"_Array",height:b,table:[w(a,b-1)],lengths:[1]}}function z(a,b){return b===a.height?a:{ctor:"_Array",height:b,table:[z(a,b-1)],
lengths:[C(a)]}}function A(a,b){return{ctor:"_Array",height:a.height+1,table:[a,b],lengths:[C(a),C(a)+C(b)]}}function Ya(a,b,d){for(var c=0;c<d.table.length;c++)0===d.height?a[b+c]=d.table[c]:Ya(a,b+(0===c?0:d.lengths[c-1]),d.table[c])}function Za(a,b,d,c){if(0===b)return{ctor:"_Array",height:0,table:a.slice(d,c)};for(var k=Math.pow(32,b),p=Array(Math.ceil((c-d)/k)),m=Array(p.length),g=0;g<p.length;g++)p[g]=Za(a,b-1,d+g*k,Math.min(d+(g+1)*k,c)),m[g]=C(p[g])+(0<g?m[g-1]:0);return{ctor:"_Array",height:b,
table:p,lengths:m}}var y={ctor:"_Array",height:0,table:[]};return{empty:y,fromList:function(a){if("[]"===a.ctor)return y;var b=Array(32);for(var d=[],k=0;"[]"!==a.ctor;)b[k]=a._0,a=a._1,k++,32===k&&(b={ctor:"_Array",height:0,table:b},c(b,d),b=Array(32),k=0);0<k&&(b={ctor:"_Array",height:0,table:b.splice(0,k)},c(b,d));for(a=0;a<d.length-1;a++)0<d[a].table.length&&c(d[a],d);d=d[d.length-1];return 0<d.height&&1===d.table.length?d.table[0]:d},toList:function(a){return g(B.Nil,a)},initialize:e(function(a,
d){return 0>=a?y:b(d,Math.floor(Math.log(a)/Math.log(32)),0,a)}),append:e(function(a,b){if(0===a.table.length)return b;if(0===b.table.length)return a;var d=ga(a,b);if(32>=d[0].table.length+d[1].table.length){if(0===d[0].table.length)return d[1];if(0===d[1].table.length)return d[0];d[0].table=d[0].table.concat(d[1].table);if(0<d[0].height){a=C(d[0]);for(b=0;b<d[1].lengths.length;b++)d[1].lengths[b]+=a;d[0].lengths=d[0].lengths.concat(d[1].lengths)}return d[0]}0<d[0].height&&(a=q(a,b),2<a&&(d=Xa(d[0],
d[1],a)));return A(d[0],d[1])}),push:e(function(a,b){var c=d(a,b);if(null!==c)return c;a=w(a,b.height);return A(b,a)}),slice:t(function(a,b,d){0>a&&(a+=C(d));0>b&&(b+=C(d));return m(a,k(b,d))}),get:e(function(a,b){if(0>a||a>=C(b))throw Error("Index "+a+" is out of range. Check the length of your array first or use getMaybe or getWithDefault.");for(var d=b.height;0<d;d--){for(var c=a>>5*d;b.lengths[c]<=a;)c++;0<c&&(a-=b.lengths[c-1]);b=b.table[c]}return b.table[a]}),set:t(function(b,d,c){return 0>
b||C(c)<=b?c:a(b,d,c)}),map:e(v),indexedMap:e(function(a,b){return ua(a,b,0)}),foldl:t(p),foldr:t(Wa),length:C,toJSArray:function(a){var b=Array(C(a));Ya(b,0,a);return b},fromJSArray:function(a){return 0===a.length?y:Za(a,Math.floor(Math.log(a.length)/Math.log(32)),0,a.length)}}}(),H=function(){function a(b,d){if(0===d)throw Error("Cannot perform mod 0. Division by zero error.");var c=b%d;b=0===b?0:0<d?0<=b?c:c+d:-a(-b,-d);return b===d?0:b}var b=["LT","EQ","GT"];return{div:e(function(a,b){return a/
b|0}),rem:e(function(a,b){return a%b}),mod:e(a),pi:Math.PI,e:Math.E,cos:Math.cos,sin:Math.sin,tan:Math.tan,acos:Math.acos,asin:Math.asin,atan:Math.atan,atan2:e(Math.atan2),degrees:function(a){return a*Math.PI/180},turns:function(a){return 2*Math.PI*a},fromPolar:function(a){var b=a._0;a=a._1;return n.Tuple2(b*Math.cos(a),b*Math.sin(a))},toPolar:function(a){var b=a._0;a=a._1;return n.Tuple2(Math.sqrt(b*b+a*a),Math.atan2(a,b))},sqrt:Math.sqrt,logBase:e(function(a,b){return Math.log(b)/Math.log(a)}),
negate:function(a){return-a},abs:function(a){return 0>a?-a:a},min:e(function(a,b){return 0>n.cmp(a,b)?a:b}),max:e(function(a,b){return 0<n.cmp(a,b)?a:b}),clamp:t(function(a,b,g){return 0>n.cmp(g,a)?a:0<n.cmp(g,b)?b:g}),compare:e(function(a,d){return{ctor:b[n.cmp(a,d)+1]}}),xor:e(function(a,b){return a!==b}),not:function(a){return!a},truncate:function(a){return a|0},ceiling:Math.ceil,floor:Math.floor,round:Math.round,toFloat:function(a){return a},isNaN:isNaN,isInfinite:function(a){return Infinity===
a||-Infinity===a}}}(),n=function(){function a(b,d,c,m){if(100<c)return m.push({x:b,y:d}),!0;if(b===d)return!0;if("object"!==typeof b){if("function"===typeof b)throw Error('Trying to use `(\x3d\x3d)` on functions. There is no way to know if functions are "the same" in the Elm sense. Read more about this at http://package.elm-lang.org/packages/elm-lang/core/latest/Basics#\x3d\x3d which describes why it is this way and what the better version will look like.');return!1}if(null===b||null===d)return!1;
if(b instanceof Date)return b.getTime()===d.getTime();if(!("ctor"in b)){for(var k in b)if(!a(b[k],d[k],c+1,m))return!1;return!0}if("RBNode_elm_builtin"===b.ctor||"RBEmpty_elm_builtin"===b.ctor)b=xa(b),d=xa(d);"Set_elm_builtin"===b.ctor&&(b=_elm_lang$core$Set$toList(b),d=_elm_lang$core$Set$toList(d));if("::"===b.ctor){for(;"::"===b.ctor&&"::"===d.ctor;){if(!a(b._0,d._0,c+1,m))return!1;b=b._1;d=d._1}return b.ctor===d.ctor}if("_Array"===b.ctor){b=P.toJSArray(b);d=P.toJSArray(d);if(b.length!==d.length)return!1;
for(k=0;k<b.length;k++)if(!a(b[k],d[k],c+1,m))return!1;return!0}if(!a(b.ctor,d.ctor,c+1,m))return!1;for(k in b)if(!a(b[k],d[k],c+1,m))return!1;return!0}function b(a,d){if("object"!==typeof a)return a===d?0:a<d?-1:1;if(a instanceof String)return a=a.valueOf(),d=d.valueOf(),a===d?0:a<d?-1:1;if("::"===a.ctor||"[]"===a.ctor){for(;"::"===a.ctor&&"::"===d.ctor;){var c=b(a._0,d._0);if(0!==c)return c;a=a._1;d=d._1}return a.ctor===d.ctor?0:"[]"===a.ctor?-1:1}if("_Tuple"===a.ctor.slice(0,6)){var m=a.ctor.slice(6)-
0;if(0===m)return 0;if(1<=m){c=b(a._0,d._0);if(0!==c)return c;if(2<=m){c=b(a._1,d._1);if(0!==c)return c;if(3<=m){c=b(a._2,d._2);if(0!==c)return c;if(4<=m){c=b(a._3,d._3);if(0!==c)return c;if(5<=m){c=b(a._4,d._4);if(0!==c)return c;if(6<=m){c=b(a._5,d._5);if(0!==c)return c;if(7<=m)throw Error("Comparison error: cannot compare tuples with more than 6 elements.");}}}}}}return 0}throw Error("Comparison error: comparison is only defined on ints, floats, times, chars, strings, lists of comparable values, and tuples of comparable values.");
}function c(a){return a.start.line==a.end.line?"on line "+a.start.line:"between lines "+a.start.line+" and "+a.end.line}function d(a){var b=typeof a;if("function"===b)return"\x3cfunction\x3e";if("boolean"===b)return a?"True":"False";if("number"===b)return a+"";if(a instanceof String)return"'"+g(a,!0)+"'";if("string"===b)return'"'+g(a,!1)+'"';if(null===a)return"null";if("object"===b&&"ctor"in a){b=a.ctor.substring(0,5);if("_Tupl"===b){b=[];for(var c in a)"ctor"!==c&&b.push(d(a[c]));return"("+b.join(",")+
")"}if("_Task"===b)return"\x3ctask\x3e";if("_Array"===a.ctor)return a=Jb(a),"Array.fromList "+d(a);if("\x3cdecoder\x3e"===a.ctor)return"\x3cdecoder\x3e";if("_Process"===a.ctor)return"\x3cprocess:"+a.id+"\x3e";if("::"===a.ctor){b="["+d(a._0);for(a=a._1;"::"===a.ctor;)b+=","+d(a._0),a=a._1;return b+"]"}if("[]"===a.ctor)return"[]";if("Set_elm_builtin"===a.ctor)return"Set.fromList "+d(_elm_lang$core$Set$toList(a));if("RBNode_elm_builtin"===a.ctor||"RBEmpty_elm_builtin"===a.ctor)return"Dict.fromList "+
d(xa(a));b="";for(var m in a)if("ctor"!==m){c=d(a[m]);var v=c[0],v="{"===v||"("===v||"\x3c"===v||'"'===v||0>c.indexOf(" ");b+=" "+(v?c:"("+c+")")}return a.ctor+b}if("object"===b){if(a instanceof Date)return"\x3c"+a.toString()+"\x3e";if(a.elm_web_socket)return"\x3cwebsocket\x3e";b=[];for(c in a)b.push(c+" \x3d "+d(a[c]));return 0===b.length?"{}":"{ "+b.join(", ")+" }"}return"\x3cinternal structure\x3e"}function g(a,b){a=a.replace(/\\/g,"\\\\").replace(/\n/g,"\\n").replace(/\t/g,"\\t").replace(/\r/g,
"\\r").replace(/\v/g,"\\v").replace(/\0/g,"\\0");return b?a.replace(/\'/g,"\\'"):a.replace(/\"/g,'\\"')}var v=0,f={ctor:"[]"};return{eq:function(b,d){var c=[];b=a(b,d,0,c);for(var m;b&&(m=c.pop());)b=a(m.x,m.y,0,c);return b},cmp:b,Tuple0:{ctor:"_Tuple0"},Tuple2:function(a,b){return{ctor:"_Tuple2",_0:a,_1:b}},chr:function(a){return new String(a)},update:function(a,b){var d={},c;for(c in a)d[c]=a[c];for(c in b)d[c]=b[c];return d},guid:function(a){return v++},append:e(function(a,b){if("string"===typeof a)return a+
b;if("[]"===a.ctor)return b;var d={ctor:"::",_0:a._0,_1:f},c=d;for(a=a._1;"[]"!==a.ctor;)c._1={ctor:"::",_0:a._0,_1:f},a=a._1,c=c._1;c._1=b;return d}),crash:function(a,b){return function(d){throw Error("Ran into a `Debug.crash` in module `"+a+"` "+c(b)+"\nThe message provided by the code author is:\n\n    "+d);}},crashCase:function(a,b,k){return function(m){throw Error("Ran into a `Debug.crash` in module `"+a+"`\n\nThis was caused by the `case` expression "+c(b)+".\nOne of the branches ended with a crash and the following value got through:\n\n    "+
d(k)+"\n\nThe message provided by the code author is:\n\n    "+m);}},toString:d}}();e(function(a,b){return f(a,b._0,b._1)});t(function(a,b,c){return a({ctor:"_Tuple2",_0:b,_1:c})});var Kb=t(function(a,b,c){return f(a,c,b)}),ba=e(function(a,b){return a}),q=q||{};q["\x3c|"]=e(function(a,b){return a(b)});q=q||{};q["|\x3e"]=e(function(a,b){return b(a)});q=q||{};q["\x3e\x3e"]=t(function(a,b,c){return b(a(c))});q=q||{};q["\x3c\x3c"]=t(function(a,b,c){return a(b(c))});q=q||{};q["++"]=n.append;var ea=n.toString,
Lb=H.toFloat,Mb=H.round,q=q||{};q["||"]=H.or;q=q||{};q["\x26\x26"]=H.and;var $a=H.compare,q=q||{};q["\x3e\x3d"]=H.ge;q=q||{};q["\x3c\x3d"]=H.le;q=q||{};q["\x3e"]=H.gt;q=q||{};q["\x3c"]=H.lt;q=q||{};q["/\x3d"]=H.neq;q=q||{};q["\x3d\x3d"]=H.eq;q=q||{};q["^"]=H.exp;q=q||{};q["%"]=H.mod;q=q||{};q["//"]=H.div;q=q||{};q["/"]=H.floatDiv;q=q||{};q["*"]=H.mul;q=q||{};q["-"]=H.sub;q=q||{};q["+"]=H.add;var Ka=e(function(a,b){return"Just"===b.ctor?b._0:a}),K={ctor:"Nothing"};e(function(a,b){return"Just"===b.ctor?
a(b._0):K});var L=function(a){return{ctor:"Just",_0:a}},T=e(function(a,b){return"Just"===b.ctor?L(a(b._0)):K});t(function(a,b,c){return"Just"===b.ctor&&"Just"===c.ctor?L(f(a,b._0,c._0)):K});w(function(a,b,c,d){return"Just"===b.ctor&&"Just"===c.ctor&&"Just"===d.ctor?L(r(a,b._0,c._0,d._0)):K});y(function(a,b,c,d,g){return"Just"===b.ctor&&"Just"===c.ctor&&"Just"===d.ctor&&"Just"===g.ctor?L(S(a,b._0,c._0,d._0,g._0)):K});F(function(a,b,c,d,g,v){return"Just"===b.ctor&&"Just"===c.ctor&&"Just"===d.ctor&&
"Just"===g.ctor&&"Just"===v.ctor?L(x(a,b._0,c._0,d._0,g._0,v._0)):K});var B=function(){function a(a,b){return{ctor:"::",_0:a,_1:b}}function b(b){for(var c=d,g=b.length;g--;)c=a(b[g],c);return c}function c(a){for(var b=[];"[]"!==a.ctor;)b.push(a._0),a=a._1;return b}var d={ctor:"[]"};return{Nil:d,Cons:a,cons:e(a),toArray:c,fromArray:b,foldr:t(function(a,b,d){d=c(d);for(var g=d.length;g--;)b=f(a,d[g],b);return b}),map2:t(function(a,d,c){for(var g=[];"[]"!==d.ctor&&"[]"!==c.ctor;)g.push(f(a,d._0,c._0)),
d=d._1,c=c._1;return b(g)}),map3:w(function(a,d,c,e){for(var g=[];"[]"!==d.ctor&&"[]"!==c.ctor&&"[]"!==e.ctor;)g.push(r(a,d._0,c._0,e._0)),d=d._1,c=c._1,e=e._1;return b(g)}),map4:y(function(a,d,c,e,f){for(var k=[];"[]"!==d.ctor&&"[]"!==c.ctor&&"[]"!==e.ctor&&"[]"!==f.ctor;)k.push(S(a,d._0,c._0,e._0,f._0)),d=d._1,c=c._1,e=e._1,f=f._1;return b(k)}),map5:F(function(a,d,c,e,f,k){for(var m=[];"[]"!==d.ctor&&"[]"!==c.ctor&&"[]"!==e.ctor&&"[]"!==f.ctor&&"[]"!==k.ctor;)m.push(x(a,d._0,c._0,e._0,f._0,k._0)),
d=d._1,c=c._1,e=e._1,f=f._1,k=k._1;return b(m)}),sortBy:e(function(a,d){return b(c(d).sort(function(b,d){return n.cmp(a(b),a(d))}))}),sortWith:e(function(a,d){return b(c(d).sort(function(b,d){b=a(b)(d).ctor;return"EQ"===b?0:"LT"===b?-1:1}))})}}(),Nb=e(function(a,b){for(;;){if(1>n.cmp(a,0))return b;var c=b;if("[]"===c.ctor)return b;b=c._1;--a}}),Ob=B.map2,ab=e(function(a,b){for(;;){if("[]"===b.ctor)return!1;if(a(b._0))return!0;b=b._1}});e(function(a,b){return!f(ab,function(b){return!a(b)},b)});var U=
B.foldr,ma=t(function(a,b,c){for(;;){var d=c;if("[]"===d.ctor)return b;c=a;b=f(a,d._0,b);d=d._1;a=c;c=d}}),Pb=function(a){return r(ma,e(function(a,c){return c+1}),0,a)},Qb=function(a){return r(ma,e(function(a,c){return a+c}),0,a)};e(function(a,b){return f(ab,function(b){return n.eq(b,a)},b)});var bb=bb||{};bb["::"]=B.cons;var La=e(function(a,b){return r(U,e(function(b,d){return{ctor:"::",_0:a(b),_1:d}}),{ctor:"[]"},b)}),Rb=e(function(a,b){var c=e(function(b,c){return a(b)?{ctor:"::",_0:b,_1:c}:c});
return r(U,c,{ctor:"[]"},b)}),Sb=t(function(a,b,c){a=a(b);return"Just"===a.ctor?{ctor:"::",_0:a._0,_1:c}:c});e(function(a,b){return r(U,Sb(a),{ctor:"[]"},b)});var cb=function(a){return r(ma,e(function(a,c){return{ctor:"::",_0:a,_1:c}}),{ctor:"[]"},a)};t(function(a,b,c){var d=e(function(b,d){return"::"===d.ctor?{ctor:"::",_0:f(a,b,d._0),_1:d}:{ctor:"[]"}});return cb(r(ma,d,{ctor:"::",_0:b,_1:{ctor:"[]"}},c))});var Tb=e(function(a,b){return"[]"===b.ctor?a:r(U,e(function(a,b){return{ctor:"::",_0:a,_1:b}}),
b,a)});e(function(a,b){return r(U,Tb,{ctor:"[]"},f(La,a,b))});e(function(a,b){var c=e(function(b,c){var d=c._0;c=c._1;return a(b)?{ctor:"_Tuple2",_0:{ctor:"::",_0:b,_1:d},_1:c}:{ctor:"_Tuple2",_0:d,_1:{ctor:"::",_0:b,_1:c}}});return r(U,c,{ctor:"_Tuple2",_0:{ctor:"[]"},_1:{ctor:"[]"}},b)});e(function(a,b){if("[]"===b.ctor)return{ctor:"[]"};var c=e(function(b,c){return{ctor:"::",_0:a,_1:{ctor:"::",_0:b,_1:c}}}),c=r(U,c,{ctor:"[]"},b._1);return{ctor:"::",_0:b._0,_1:c}});var Ub=t(function(a,b,c){for(;;){if(1>
n.cmp(a,0))return c;var d=b;if("[]"===d.ctor)return c;b=d._1;c={ctor:"::",_0:d._0,_1:c};--a}}),Vb=e(function(a,b){return cb(r(Ub,a,b,{ctor:"[]"}))}),db=t(function(a,b,c){if(1>n.cmp(b,0))return{ctor:"[]"};a:do{b:do{if("[]"===c.ctor)return c;if("::"===c._1.ctor)switch(b){case 1:break b;case 2:return{ctor:"::",_0:c._0,_1:{ctor:"::",_0:c._1._0,_1:{ctor:"[]"}}};case 3:if("::"===c._1._1.ctor)return{ctor:"::",_0:c._0,_1:{ctor:"::",_0:c._1._0,_1:{ctor:"::",_0:c._1._1._0,_1:{ctor:"[]"}}}};break a;default:if("::"===
c._1._1.ctor&&"::"===c._1._1._1.ctor){var d=c._1._1._0,g=c._1._0,e=c._0,h=c._1._1._1._0;c=c._1._1._1._1;return 0<n.cmp(a,1E3)?{ctor:"::",_0:e,_1:{ctor:"::",_0:g,_1:{ctor:"::",_0:d,_1:{ctor:"::",_0:h,_1:f(Vb,b-4,c)}}}}:{ctor:"::",_0:e,_1:{ctor:"::",_0:g,_1:{ctor:"::",_0:d,_1:{ctor:"::",_0:h,_1:r(db,a+1,b-4,c)}}}}}break a}else if(1===b)break b;else break a}while(0);return{ctor:"::",_0:c._0,_1:{ctor:"[]"}}}while(0);return c}),Wb=e(function(a,b){return r(db,0,a,b)}),Xb=t(function(a,b,c){for(;;){if(1>
n.cmp(b,0))return a;--b;var d=c;a={ctor:"::",_0:c,_1:a};c=d}});e(function(a,b){return r(Xb,{ctor:"[]"},a,b)});var Yb=t(function(a,b,c){for(;;)if(1>n.cmp(a,b))c={ctor:"::",_0:b,_1:c},--b;else return c}),Zb=e(function(a,b){return r(Yb,a,b,{ctor:"[]"})}),eb=e(function(a,b){return r(Ob,a,f(Zb,0,Pb(b)-1),b)});e(function(a,b){return 1>n.cmp(0,a)&&0>n.cmp(a,P.length(b))?L(f(P.get,a,b)):K});e(function(a,b){var c=e(function(b,c){return a(b)?f(P.push,b,c):c});return r(P.foldl,c,P.empty,b)});var Jb=P.toList,
$b=P.initialize;e(function(a,b){return f($b,a,ba(b))});var Ma=function(){return{fromCode:function(a){return n.chr(String.fromCharCode(a))},toCode:function(a){return a.charCodeAt(0)},toUpper:function(a){return n.chr(a.toUpperCase())},toLower:function(a){return n.chr(a.toLowerCase())},toLocaleUpper:function(a){return n.chr(a.toLocaleUpperCase())},toLocaleLower:function(a){return n.chr(a.toLocaleLowerCase())}}}().toCode,ya=t(function(a,b,c){c=Ma(c);return-1<n.cmp(c,Ma(a))&&1>n.cmp(c,Ma(b))});f(ya,n.chr("A"),
n.chr("Z"));f(ya,n.chr("a"),n.chr("z"));f(ya,n.chr("0"),n.chr("9"));f(ya,n.chr("0"),n.chr("7"));var z=function(){function a(a){return{ctor:"_Task_succeed",value:a}}function b(a){return{ctor:"_Task_nativeBinding",callback:a,cancel:null}}function c(a){a={ctor:"_Process",id:n.guid(),root:a,stack:null,mailbox:[]};v(a);return a}function d(a,b){a.mailbox.push(b);v(a)}function g(a,b){for(;1E4>a;){var d=b.root.ctor;if("_Task_succeed"===d){for(;b.stack&&"_Task_onError"===b.stack.ctor;)b.stack=b.stack.rest;
if(null===b.stack)break;b.root=b.stack.callback(b.root.value);b.stack=b.stack.rest;++a}else if("_Task_fail"===d){for(;b.stack&&"_Task_andThen"===b.stack.ctor;)b.stack=b.stack.rest;if(null===b.stack)break;b.root=b.stack.callback(b.root.value);b.stack=b.stack.rest;++a}else if("_Task_andThen"===d)b.stack={ctor:"_Task_andThen",callback:b.root.callback,rest:b.stack},b.root=b.root.task,++a;else if("_Task_onError"===d)b.stack={ctor:"_Task_onError",callback:b.root.callback,rest:b.stack},b.root=b.root.task,
++a;else{if("_Task_nativeBinding"===d){b.root.cancel=b.root.callback(function(a){b.root=a;v(b)});break}if("_Task_receive"===d){d=b.mailbox;if(0===d.length)break;b.root=b.root.callback(d.shift());++a}else throw Error(d);}}if(1E4>a)return a+1;v(b);return a}function v(a){h.push(a);p||(setTimeout(f,0),p=!0)}function f(){for(var a=0,b;1E4>a&&(b=h.shift());)b.root&&(a=g(a,b));b?setTimeout(f,0):p=!1}var p=!1,h=[];return{succeed:a,fail:function(a){return{ctor:"_Task_fail",value:a}},nativeBinding:b,andThen:e(function(a,
b){return{ctor:"_Task_andThen",callback:a,task:b}}),onError:e(function(a,b){return{ctor:"_Task_onError",callback:a,task:b}}),receive:function(a){return{ctor:"_Task_receive",callback:a}},spawn:function(d){return b(function(b){var g=c(d);b(a(g))})},kill:function(d){return b(function(b){var c=d.root;"_Task_nativeBinding"===c.ctor&&c.cancel&&c.cancel();d.root=null;b(a(n.Tuple0))})},sleep:function(d){return b(function(b){var c=setTimeout(function(){b(a(n.Tuple0))},d);return function(){clearTimeout(c)}})},
send:e(function(c,g){return b(function(b){d(c,g);b(a(n.Tuple0))})}),rawSpawn:c,rawSend:d}}(),V=function(){function a(a,b){return function(a){}}function b(a,b,d,k){function e(a){z.rawSend(ua,a)}var m={},v,h=z.nativeBinding(function(b){var c=a._0;v=k(e,c);var g=a._1,f=d(c);p(m,g,f);b(z.succeed(c))}),ua=g(h,function(a,c){return z.nativeBinding(function(g){var k=f(b,a,c);c=k._0;v(c);var k=k._1,e=d(c);p(m,k,e);g(z.succeed(c))})});return(h=c(m,e))?{ports:h}:{}}function c(a,b){var c;for(c in O){var g=O[c];
if(g.isForeign){var k=k||{};k[c]="cmd"===g.tag?ga(c):Ia(c,b)}a[c]=d(g,b)}return k}function d(a,b){var d={main:b,self:void 0},c=a.tag,k=a.onEffects,e=a.onSelfMsg;a=g(a.init,function(a,b){if("self"===a.ctor)return r(e,d,a._0,b);a=a._0;switch(c){case "cmd":return r(k,d,a.cmds,b);case "sub":return r(k,d,a.subs,b);case "fx":return S(k,d,a.cmds,a.subs,b)}});return d.self=a}function g(a,b){function d(a){var g=z.receive(function(d){return b(d,a)});return f(c,d,g)}var c=z.andThen;a=f(c,d,a);return z.rawSpawn(a)}
function v(a){return function(b){return{type:"leaf",home:a,value:b}}}function h(a){return{type:"node",branches:a}}function p(a,b,d){var c={};q(!0,b,c,null);q(!1,d,c,null);for(var g in a)z.rawSend(a[g],{ctor:"fx",_0:g in c?c[g]:{cmds:B.Nil,subs:B.Nil}})}function q(a,b,d,c){switch(b.type){case "leaf":var g=b.home;c=k(a,g,c,b.value);b=(b=d[g])||{cmds:B.Nil,subs:B.Nil};a?b.cmds=B.Cons(c,b.cmds):b.subs=B.Cons(c,b.subs);d[g]=b;break;case "node":for(g=b.branches;"[]"!==g.ctor;)q(a,g._0,d,c),g=g._1;break;
case "map":q(a,b.tree,d,{tagger:b.tagger,rest:c})}}function k(a,b,d,c){return f(a?O[b].cmdMap:O[b].subMap,function(a){for(var b=d;b;)a=b.tagger(a),b=b.rest;return a},c)}function m(a){if(a in O)throw Error("There can only be one port named `"+a+"`, but your program has multiple.");}function ga(a){var b=[],d=O[a].converter,c=z.succeed(null);O[a].init=c;O[a].onEffects=t(function(a,g,k){for(;"[]"!==g.ctor;){a=b;k=d(g._0);for(var e=0;e<a.length;e++)a[e](k);g=g._1}return c});return{subscribe:function(a){b.push(a)},
unsubscribe:function(a){b=b.slice();a=b.indexOf(a);0<=a&&b.splice(a,1)}}}function Ia(a,b){function d(a,b,d){k=b;return p}function c(a){for(var d=k;"[]"!==d.ctor;)b(d._0(a)),d=d._1}var g=[],k=B.Nil,e=O[a].converter,m=function(a,b,k){a=d(a,b,k);for(b=0;b<g.length;b++)c(g[b]);g=null;v=c;m=d;return a},v=function(a){g.push(a)},p=z.succeed(null);O[a].init=p;O[a].onEffects=t(function(a,b,d){return m(a,b,d)});return{send:function(b){b=f(Na,e,b);if("Err"===b.ctor)throw Error("Trying to send an unexpected type of value through port `"+
a+"`:\n"+b._0);v(b._0)}}}var O={},x=e(function(a,b){return b}),w=e(function(a,b){return function(d){return a(b(d))}});return{sendToApp:e(function(a,b){return z.nativeBinding(function(d){a.main(b);d(z.succeed(n.Tuple0))})}),sendToSelf:e(function(a,b){return f(z.send,a.self,{ctor:"self",_0:b})}),effectManagers:O,outgoingPort:function(a,b){m(a);O[a]={tag:"cmd",cmdMap:x,converter:b,isForeign:!0};return v(a)},incomingPort:function(a,b){m(a);O[a]={tag:"sub",subMap:w,converter:b,isForeign:!0};return v(a)},
htmlToProgram:function(a){var b=h(B.Nil),d=n.Tuple2(n.Tuple0,b);return f(Y.program,fb,{init:d,view:function(a){return main},update:e(function(a,b){return d}),subscriptions:function(a){return b}})},program:function(d){return function(c){return function(c,g){c.worker=function(c){if("undefined"!==typeof c)throw Error("The `"+g+"` module does not need flags.\nCall "+g+".worker() with no arguments and you should be all set!");return b(d.init,d.update,d.subscriptions,a)}}}},programWithFlags:function(d){return function(c){return function(g,
k){g.worker=function(g){if("undefined"===typeof c)throw Error("Are you trying to sneak a Never value into Elm? Trickster!\nIt looks like "+k+".main is defined with `programWithFlags` but has type `Program Never`.\nUse `program` instead if you do not want flags.");g=f(M.run,c,g);if("Err"===g.ctor)throw Error(k+".worker(...) was called with an unexpected argument.\nI tried to convert it to an Elm value, but ran into this problem:\n\n"+g._0);return b(d.init(g._0),d.update,d.subscriptions,a)}}}},initialize:b,
leaf:v,batch:h,map:e(function(a,b){return{type:"map",tagger:a,tree:b}})}}(),gb=V.batch,ca=gb({ctor:"[]"}),hb=hb||{};hb["!"]=e(function(a,b){return{ctor:"_Tuple2",_0:a,_1:gb(b)}});var ac=V.batch,ib=ac({ctor:"[]"}),bc=V.sendToApp,jb=function(a){return"Ok"===a.ctor?L(a._0):K},cc=e(function(a,b){return"Ok"===b.ctor?b._0:a}),A=function(a){return{ctor:"Err",_0:a}};e(function(a,b){return"Ok"===b.ctor?a(b._0):A(b._0)});var N=function(a){return{ctor:"Ok",_0:a}};e(function(a,b){return"Ok"===b.ctor?N(a(b._0)):
A(b._0)});t(function(a,b,c){return"Ok"===b.ctor?"Ok"===c.ctor?N(f(a,b._0,c._0)):A(c._0):A(b._0)});w(function(a,b,c,d){return"Ok"===b.ctor?"Ok"===c.ctor?"Ok"===d.ctor?N(r(a,b._0,c._0,d._0)):A(d._0):A(c._0):A(b._0)});y(function(a,b,c,d,g){return"Ok"===b.ctor?"Ok"===c.ctor?"Ok"===d.ctor?"Ok"===g.ctor?N(S(a,b._0,c._0,d._0,g._0)):A(g._0):A(d._0):A(c._0):A(b._0)});F(function(a,b,c,d,g,e){return"Ok"===b.ctor?"Ok"===c.ctor?"Ok"===d.ctor?"Ok"===g.ctor?"Ok"===e.ctor?N(x(a,b._0,c._0,d._0,g._0,e._0)):A(e._0):
A(g._0):A(d._0):A(c._0):A(b._0)});e(function(a,b){return"Ok"===b.ctor?N(b._0):A(a(b._0))});e(function(a,b){return"Just"===b.ctor?N(b._0):A(a)});var kb=z.onError,I=z.andThen,dc=e(function(a,b){return z.spawn(f(I,bc(a),b._0))}),ec=z.fail;e(function(a,b){return f(kb,function(b){return ec(a(b))},b)});var Q=z.succeed,Oa=e(function(a,b){return f(I,function(b){return Q(a(b))},b)}),fc=t(function(a,b,c){return f(I,function(b){return f(I,function(d){return Q(f(a,b,d))},c)},b)});w(function(a,b,c,d){return f(I,
function(b){return f(I,function(c){return f(I,function(d){return Q(r(a,b,c,d))},d)},c)},b)});y(function(a,b,c,d,g){return f(I,function(b){return f(I,function(c){return f(I,function(d){return f(I,function(g){return Q(S(a,b,c,d,g))},g)},d)},c)},b)});F(function(a,b,c,d,g,e){return f(I,function(b){return f(I,function(c){return f(I,function(d){return f(I,function(g){return f(I,function(k){return Q(x(a,b,c,d,g,k))},e)},g)},d)},c)},b)});var lb=function(a){return"[]"===a.ctor?Q({ctor:"[]"}):r(fc,e(function(a,
c){return{ctor:"::",_0:a,_1:c}}),a._0,lb(a._1))},gc=t(function(a,b,c){return f(Oa,function(a){return{ctor:"_Tuple0"}},lb(f(La,dc(a),b)))}),hc=Q({ctor:"_Tuple0"}),ic=t(function(a,b,c){return Q({ctor:"_Tuple0"})}),mb=V.leaf("Task");e(function(a,b){return mb({ctor:"Perform",_0:f(Oa,a,b)})});var jc=e(function(a,b){return mb({ctor:"Perform",_0:f(kb,function(b){return Q(a(A(b)))},f(I,function(b){return Q(a(N(b)))},b))})}),kc=e(function(a,b){return{ctor:"Perform",_0:f(Oa,a,b._0)}});V.effectManagers.Task=
{pkg:"elm-lang/core",init:hc,onEffects:gc,onSelfMsg:ic,tag:"cmd",cmdMap:kc};var na=function(){return{crash:function(a){throw Error(a);},log:e(function(a,b){a=a+": "+n.toString(b);var c=c||{};c.stdout?c.stdout.write(a):console.log(a);return b})}}(),ha=function(){function a(a,b){for(var d="";0<a;)a&1&&(d+=b),a>>=1,b+=b;return d}function b(a){return A("could not convert string '"+a+"' to an Int")}function c(a){return A("could not convert string '"+a+"' to a Float")}return{isEmpty:function(a){return 0===
a.length},cons:e(function(a,b){return a+b}),uncons:function(a){var b=a[0];return b?L(n.Tuple2(n.chr(b),a.slice(1))):K},append:e(function(a,b){return a+b}),concat:function(a){return B.toArray(a).join("")},length:function(a){return a.length},map:e(function(a,b){b=b.split("");for(var d=b.length;d--;)b[d]=a(n.chr(b[d]));return b.join("")}),filter:e(function(a,b){return b.split("").map(n.chr).filter(a).join("")}),reverse:function(a){return a.split("").reverse().join("")},foldl:t(function(a,b,c){for(var d=
c.length,g=0;g<d;++g)b=f(a,n.chr(c[g]),b);return b}),foldr:t(function(a,b,c){for(var d=c.length;d--;)b=f(a,n.chr(c[d]),b);return b}),split:e(function(a,b){return B.fromArray(b.split(a))}),join:e(function(a,b){return B.toArray(b).join(a)}),repeat:e(a),slice:t(function(a,b,c){return c.slice(a,b)}),left:e(function(a,b){return 1>a?"":b.slice(0,a)}),right:e(function(a,b){return 1>a?"":b.slice(-a)}),dropLeft:e(function(a,b){return 1>a?b:b.slice(a)}),dropRight:e(function(a,b){return 1>a?b:b.slice(0,-a)}),
pad:t(function(b,c,e){b=(b-e.length)/2;return a(Math.ceil(b),c)+e+a(b|0,c)}),padLeft:t(function(b,c,e){return a(b-e.length,c)+e}),padRight:t(function(b,c,e){return e+a(b-e.length,c)}),trim:function(a){return a.trim()},trimLeft:function(a){return a.replace(/^\s+/,"")},trimRight:function(a){return a.replace(/\s+$/,"")},words:function(a){return B.fromArray(a.trim().split(/\s+/g))},lines:function(a){return B.fromArray(a.split(/\r\n|\r|\n/g))},toUpper:function(a){return a.toUpperCase()},toLower:function(a){return a.toLowerCase()},
any:e(function(a,b){for(var d=b.length;d--;)if(a(n.chr(b[d])))return!0;return!1}),all:e(function(a,b){for(var d=b.length;d--;)if(!a(n.chr(b[d])))return!1;return!0}),contains:e(function(a,b){return-1<b.indexOf(a)}),startsWith:e(function(a,b){return 0===b.indexOf(a)}),endsWith:e(function(a,b){return b.length>=a.length&&b.lastIndexOf(a)===b.length-a.length}),indexes:e(function(a,b){var d=a.length;if(1>d)return B.Nil;for(var c=0,e=[];-1<(c=b.indexOf(a,c));)e.push(c),c+=d;return B.fromArray(e)}),toInt:function(a){var d=
a.length;if(0===d)return b(a);var c=a[0];if("0"===c&&"x"===a[1]){for(var e=2;e<d;++e)if(c=a[e],!("0"<=c&&"9">=c||"A"<=c&&"F">=c||"a"<=c&&"f">=c))return b(a);return N(parseInt(a,16))}if("9"<c||"0">c&&"-"!==c&&"+"!==c)return b(a);for(e=1;e<d;++e)if(c=a[e],"0">c||"9"<c)return b(a);return N(parseInt(a,10))},toFloat:function(a){if(0===a.length||/[\sxbo]/.test(a))return c(a);var b=+a;return b===b?N(b):c(a)},toList:function(a){return B.fromArray(a.split("").map(n.chr))},fromList:function(a){return B.toArray(a).join("")}}}(),
Pa=ha.toFloat,lc=ha.contains,nb=ha.toLower,mc=ha.length,nc=ha.concat,oc=ha.append,ob=t(function(a,b,c){for(;;){var d=c;if("RBEmpty_elm_builtin"===d.ctor)return b;c=a;b=r(a,d._1,d._2,r(ob,a,b,d._4));d=d._3;a=c;c=d}}),xa=function(a){return r(ob,t(function(a,c,d){return{ctor:"::",_0:{ctor:"_Tuple2",_0:a,_1:c},_1:d}}),{ctor:"[]"},a)},ia=t(function(a,b,c){for(;;){var d=c;if("RBEmpty_elm_builtin"===d.ctor)return b;c=a;b=r(a,d._1,d._2,r(ia,a,b,d._3));d=d._4;a=c;c=d}});F(function(a,b,c,d,g,f){var v=t(function(d,
e,k){for(;;){var m=k;k=m._1;var g=m._0,f=g;if("[]"===f.ctor)return{ctor:"_Tuple2",_0:g,_1:r(c,d,e,k)};var m=f._1,v=f._0._1,f=f._0._0;if(0>n.cmp(f,d))k={ctor:"_Tuple2",_0:m,_1:r(a,f,v,k)};else return 0<n.cmp(f,d)?{ctor:"_Tuple2",_0:g,_1:r(c,d,e,k)}:{ctor:"_Tuple2",_0:m,_1:S(b,f,v,e,k)}}});g=r(ia,v,{ctor:"_Tuple2",_0:xa(d),_1:f},g);d=g._0;g=g._1;return r(ma,e(function(b,d){return r(a,b._0,b._1,d)}),g,d)});var pb=w(function(a,b,c,d){return na.crash(nc({ctor:"::",_0:"Internal red-black tree invariant violated, expected ",
_1:{ctor:"::",_0:a,_1:{ctor:"::",_0:" and got ",_1:{ctor:"::",_0:ea(b),_1:{ctor:"::",_0:"/",_1:{ctor:"::",_0:c,_1:{ctor:"::",_0:"/",_1:{ctor:"::",_0:d,_1:{ctor:"::",_0:"\nPlease report this bug to \x3chttps://github.com/elm-lang/core/issues\x3e",_1:{ctor:"[]"}}}}}}}}}}))}),qb=function(a){a:do{if("RBNode_elm_builtin"===a.ctor){if("BBlack"===a._0.ctor)return!0}else if("LBBlack"===a._0.ctor)return!0;break a}while(0);return!1},pc=e(function(a,b){for(;;){if("RBEmpty_elm_builtin"===b.ctor)return a;a=f(pc,
a+1,b._4);b=b._3}}),qc=e(function(a,b){a:for(;;){if("RBEmpty_elm_builtin"===b.ctor)return K;switch(f($a,a,b._1).ctor){case "LT":b=b._3;continue a;case "EQ":return L(b._2);default:b=b._4}}}),rc=e(function(a,b){return"Just"===f(qc,a,b).ctor?!0:!1}),sc=t(function(a,b,c){for(;;){if("RBEmpty_elm_builtin"===c.ctor)return{ctor:"_Tuple2",_0:a,_1:b};b=c._2;var d=c._4;a=c._1;c=d}}),tc={ctor:"NBlack"},rb={ctor:"BBlack"},J={ctor:"Black"},za={ctor:"Red"},uc=function(a){switch(a.ctor){case "Black":return rb;case "Red":return J;
case "NBlack":return za;default:return na.crash("Can't make a double black node more black!")}},sb=function(a){switch(a.ctor){case "BBlack":return J;case "Black":return za;case "Red":return tc;default:return na.crash("Can't make a negative black node less black!")}},vc={ctor:"LBBlack"},oa={ctor:"LBlack"},ja=function(a){return{ctor:"RBEmpty_elm_builtin",_0:a}},Z=ja(oa),D=y(function(a,b,c,d,e){return{ctor:"RBNode_elm_builtin",_0:a,_1:b,_2:c,_3:d,_4:e}}),wc=function(a){return"RBNode_elm_builtin"===a.ctor&&
"Red"===a._0.ctor?x(D,J,a._1,a._2,a._3,a._4):a},tb=function(a){return"RBNode_elm_builtin"===a.ctor?x(D,sb(a._0),a._1,a._2,a._3,a._4):ja(oa)},Aa=function(a){return function(b){return function(c){return function(d){return function(e){return function(g){return function(f){return function(v){return function(h){return function(k){return function(m){return x(D,sb(a),d,e,x(D,J,b,c,v,h),x(D,J,g,f,k,m))}}}}}}}}}}},xc=function(a){return"RBEmpty_elm_builtin"===a.ctor?ja(oa):x(D,J,a._1,a._2,a._3,a._4)},ub=function(a){return"RBEmpty_elm_builtin"===
a.ctor?na.crash("can't make a Leaf red"):x(D,za,a._1,a._2,a._3,a._4)},yc=function(a){a:do{b:do{c:do{d:do{e:do{f:do{g:do if("RBNode_elm_builtin"===a.ctor)if("RBNode_elm_builtin"===a._3.ctor)if("RBNode_elm_builtin"===a._4.ctor)switch(a._3._0.ctor){case "Red":switch(a._4._0.ctor){case "Red":if("RBNode_elm_builtin"===a._3._3.ctor&&"Red"===a._3._3._0.ctor)break g;else if("RBNode_elm_builtin"===a._3._4.ctor&&"Red"===a._3._4._0.ctor)break f;else if("RBNode_elm_builtin"===a._4._3.ctor&&"Red"===a._4._3._0.ctor)break e;
else if("RBNode_elm_builtin"===a._4._4.ctor&&"Red"===a._4._4._0.ctor)break d;else break a;case "NBlack":if("RBNode_elm_builtin"===a._3._3.ctor&&"Red"===a._3._3._0.ctor)break g;else if("RBNode_elm_builtin"===a._3._4.ctor&&"Red"===a._3._4._0.ctor)break f;else if("BBlack"===a._0.ctor&&"RBNode_elm_builtin"===a._4._3.ctor&&"Black"===a._4._3._0.ctor&&"RBNode_elm_builtin"===a._4._4.ctor&&"Black"===a._4._4._0.ctor)break c;else break a;default:if("RBNode_elm_builtin"===a._3._3.ctor&&"Red"===a._3._3._0.ctor)break g;
else if("RBNode_elm_builtin"===a._3._4.ctor&&"Red"===a._3._4._0.ctor)break f;else break a}case "NBlack":switch(a._4._0.ctor){case "Red":if("RBNode_elm_builtin"===a._4._3.ctor&&"Red"===a._4._3._0.ctor)break e;else if("RBNode_elm_builtin"===a._4._4.ctor&&"Red"===a._4._4._0.ctor)break d;else if("BBlack"===a._0.ctor&&"RBNode_elm_builtin"===a._3._3.ctor&&"Black"===a._3._3._0.ctor&&"RBNode_elm_builtin"===a._3._4.ctor&&"Black"===a._3._4._0.ctor)break b;else break a;case "NBlack":if("BBlack"===a._0.ctor)if("RBNode_elm_builtin"===
a._4._3.ctor&&"Black"===a._4._3._0.ctor&&"RBNode_elm_builtin"===a._4._4.ctor&&"Black"===a._4._4._0.ctor)break c;else if("RBNode_elm_builtin"===a._3._3.ctor&&"Black"===a._3._3._0.ctor&&"RBNode_elm_builtin"===a._3._4.ctor&&"Black"===a._3._4._0.ctor)break b;else break a;else break a;default:if("BBlack"===a._0.ctor&&"RBNode_elm_builtin"===a._3._3.ctor&&"Black"===a._3._3._0.ctor&&"RBNode_elm_builtin"===a._3._4.ctor&&"Black"===a._3._4._0.ctor)break b;else break a}default:switch(a._4._0.ctor){case "Red":if("RBNode_elm_builtin"===
a._4._3.ctor&&"Red"===a._4._3._0.ctor)break e;else if("RBNode_elm_builtin"===a._4._4.ctor&&"Red"===a._4._4._0.ctor)break d;else break a;case "NBlack":if("BBlack"===a._0.ctor&&"RBNode_elm_builtin"===a._4._3.ctor&&"Black"===a._4._3._0.ctor&&"RBNode_elm_builtin"===a._4._4.ctor&&"Black"===a._4._4._0.ctor)break c;else break a;default:break a}}else switch(a._3._0.ctor){case "Red":if("RBNode_elm_builtin"===a._3._3.ctor&&"Red"===a._3._3._0.ctor)break g;else if("RBNode_elm_builtin"===a._3._4.ctor&&"Red"===
a._3._4._0.ctor)break f;else break a;case "NBlack":if("BBlack"===a._0.ctor&&"RBNode_elm_builtin"===a._3._3.ctor&&"Black"===a._3._3._0.ctor&&"RBNode_elm_builtin"===a._3._4.ctor&&"Black"===a._3._4._0.ctor)break b;else break a;default:break a}else if("RBNode_elm_builtin"===a._4.ctor)switch(a._4._0.ctor){case "Red":if("RBNode_elm_builtin"===a._4._3.ctor&&"Red"===a._4._3._0.ctor)break e;else if("RBNode_elm_builtin"===a._4._4.ctor&&"Red"===a._4._4._0.ctor)break d;else break a;case "NBlack":if("BBlack"===
a._0.ctor&&"RBNode_elm_builtin"===a._4._3.ctor&&"Black"===a._4._3._0.ctor&&"RBNode_elm_builtin"===a._4._4.ctor&&"Black"===a._4._4._0.ctor)break c;else break a;default:break a}else break a;else break a;while(0);return Aa(a._0)(a._3._3._1)(a._3._3._2)(a._3._1)(a._3._2)(a._1)(a._2)(a._3._3._3)(a._3._3._4)(a._3._4)(a._4)}while(0);return Aa(a._0)(a._3._1)(a._3._2)(a._3._4._1)(a._3._4._2)(a._1)(a._2)(a._3._3)(a._3._4._3)(a._3._4._4)(a._4)}while(0);return Aa(a._0)(a._1)(a._2)(a._4._3._1)(a._4._3._2)(a._4._1)(a._4._2)(a._3)(a._4._3._3)(a._4._3._4)(a._4._4)}while(0);
return Aa(a._0)(a._1)(a._2)(a._4._1)(a._4._2)(a._4._4._1)(a._4._4._2)(a._3)(a._4._3)(a._4._4._3)(a._4._4._4)}while(0);return x(D,J,a._4._3._1,a._4._3._2,x(D,J,a._1,a._2,a._3,a._4._3._3),x(pa,J,a._4._1,a._4._2,a._4._3._4,ub(a._4._4)))}while(0);return x(D,J,a._3._4._1,a._3._4._2,x(pa,J,a._3._1,a._3._2,ub(a._3._3),a._3._4._3),x(D,J,a._1,a._2,a._3._4._4,a._4))}while(0);return a},pa=y(function(a,b,c,d,e){a=x(D,a,b,c,d,e);"RBNode_elm_builtin"===a.ctor?(b=a._0,b=n.eq(b,J)||n.eq(b,rb)):b=!0;return b?yc(a):
a}),Ba=y(function(a,b,c,d,e){return qb(d)||qb(e)?x(pa,uc(a),b,c,tb(d),tb(e)):x(D,a,b,c,d,e)}),wb=y(function(a,b,c,d,e){return"RBEmpty_elm_builtin"===e.ctor?r(vb,a,d,e):x(Ba,a,b,c,d,x(wb,e._0,e._1,e._2,e._3,e._4))}),vb=t(function(a,b,c){if("RBEmpty_elm_builtin"===b.ctor)if("RBEmpty_elm_builtin"===c.ctor)switch(a.ctor){case "Red":return ja(oa);case "Black":return ja(vc);default:return na.crash("cannot have bblack or nblack nodes at this point")}else{var d=c._0;b=b._0;return"Black"===a.ctor&&"LBlack"===
b.ctor&&"Red"===d.ctor?x(D,J,c._1,c._2,c._3,c._4):S(pb,"Black/LBlack/Red",a,ea(b),ea(d))}else{if("RBEmpty_elm_builtin"===c.ctor)return c=c._0,d=b._0,"Black"===a.ctor&&"Red"===d.ctor&&"LBlack"===c.ctor?x(D,J,b._1,b._2,b._3,b._4):S(pb,"Black/Red/LBlack",a,ea(d),ea(c));var d=b._2,e=b._4,f=b._1;b=x(wb,b._0,f,d,b._3,e);d=r(sc,f,d,e);return x(Ba,a,d._0,d._1,b,c)}}),xb=e(function(a,b){if("RBEmpty_elm_builtin"===b.ctor)return ja(oa);var c=b._1;return x(D,b._0,c,f(a,c,b._2),f(xb,a,b._3),f(xb,a,b._4))}),Ca=
{ctor:"Same"},Qa={ctor:"Remove"},Ra={ctor:"Insert"},yb=t(function(a,b,c){var d=function(c){if("RBEmpty_elm_builtin"===c.ctor){var e=b(K);return"Nothing"===e.ctor?{ctor:"_Tuple2",_0:Ca,_1:Z}:{ctor:"_Tuple2",_0:Ra,_1:x(D,za,a,e._0,Z,Z)}}var g=c._2,h=c._4,k=c._3,e=c._1;c=c._0;switch(f($a,a,e).ctor){case "EQ":return g=b(L(g)),"Nothing"===g.ctor?{ctor:"_Tuple2",_0:Qa,_1:r(vb,c,k,h)}:{ctor:"_Tuple2",_0:Ca,_1:x(D,c,e,g._0,k,h)};case "LT":var k=d(k),m=k._0,k=k._1;switch(m.ctor){case "Same":return{ctor:"_Tuple2",
_0:Ca,_1:x(D,c,e,g,k,h)};case "Insert":return{ctor:"_Tuple2",_0:Ra,_1:x(pa,c,e,g,k,h)};default:return{ctor:"_Tuple2",_0:Qa,_1:x(Ba,c,e,g,k,h)}}default:switch(h=d(h),m=h._0,h=h._1,m.ctor){case "Same":return{ctor:"_Tuple2",_0:Ca,_1:x(D,c,e,g,k,h)};case "Insert":return{ctor:"_Tuple2",_0:Ra,_1:x(pa,c,e,g,k,h)};default:return{ctor:"_Tuple2",_0:Qa,_1:x(Ba,c,e,g,k,h)}}}};c=d(c);var e=c._1;switch(c._0.ctor){case "Same":return e;case "Insert":return wc(e);default:return xc(e)}}),qa=t(function(a,b,c){return r(yb,
a,ba(L(b)),c)});e(function(a,b){return r(qa,a,b,Z)});e(function(a,b){return r(ia,qa,b,a)});var zc=e(function(a,b){var c=t(function(b,c,e){return f(a,b,c)?r(qa,b,c,e):e});return r(ia,c,Z,b)});e(function(a,b){return f(zc,e(function(a,d){return f(rc,a,b)}),a)});e(function(a,b){var c=t(function(b,c,e){var d=e._1;e=e._0;return f(a,b,c)?{ctor:"_Tuple2",_0:r(qa,b,c,e),_1:d}:{ctor:"_Tuple2",_0:e,_1:r(qa,b,c,d)}});return r(ia,c,{ctor:"_Tuple2",_0:Z,_1:Z},b)});var Ac=e(function(a,b){return r(yb,a,ba(K),b)});
e(function(a,b){return r(ia,t(function(a,b,e){return f(Ac,a,e)}),a,b)});var M=function(){function a(a,b){return{ctor:"\x3cdecoder\x3e",tag:"map-many",func:a,decoders:b}}function b(a){return{tag:"ok",value:a}}function c(a,b){return{tag:"primitive",type:a,value:b}}function d(a,b){return{tag:"index",index:a,rest:b}}function d(a,b){return{tag:"index",index:a,rest:b}}function g(a){for(var b="_";a;)switch(a.tag){case "primitive":return b="Expecting "+a.type+("_"===b?"":" at "+b)+" but instead got: ",a=
a.value,a=void 0===a?"undefined":JSON.stringify(a),b+a;case "index":b+="["+a.index+"]";a=a.rest;break;case "field":b+="."+a.field;a=a.rest;break;case "oneOf":a=a.problems;for(var d=0;d<a.length;d++)a[d]=g(a[d]);return"I ran into the following problems"+("_"===b?"":" at "+b)+":\n\n"+a.join("\n");case "fail":return"I ran into a `fail` decoder"+("_"===b?"":" at "+b)+": "+a.msg}}function f(a,b){a=h(a,b);return"ok"===a.tag?N(a.value):A(g(a))}function h(a,e){switch(a.tag){case "bool":return"boolean"===
typeof e?b(e):c("a Bool",e);case "int":return"number"!==typeof e?c("an Int",e):-2147483647<e&&2147483647>e&&(e|0)===e||isFinite(e)&&!(e%1)?b(e):c("an Int",e);case "float":return"number"===typeof e?b(e):c("a Float",e);case "string":return"string"===typeof e?b(e):e instanceof String?b(e+""):c("a String",e);case "null":return null===e?b(a.value):c("null",e);case "value":return b(e);case "list":if(!(e instanceof Array))return c("a List",e);for(var g=B.Nil,k=e.length;k--;){var f=h(a.decoder,e[k]);if("ok"!==
f.tag)return d(k,f);g=B.Cons(f.value,g)}return b(g);case "array":if(!(e instanceof Array))return c("an Array",e);f=e.length;g=Array(f);for(k=f;k--;){f=h(a.decoder,e[k]);if("ok"!==f.tag)return d(k,f);g[k]=f.value}return b(P.fromJSArray(g));case "maybe":return f=h(a.decoder,e),"ok"===f.tag?b(L(f.value)):b(K);case "field":k=a.field;if("object"!==typeof e||null===e||!(k in e))return c("an object with a field named `"+k+"`",e);f=h(a.decoder,e[k]);return"ok"===f.tag?f:{tag:"field",field:k,rest:f};case "index":k=
a.index;if(!(e instanceof Array))return c("an array",e);if(k>=e.length)return c("a longer array. Need index "+k+" but there are only "+e.length+" entries",e);f=h(a.decoder,e[k]);return"ok"===f.tag?f:d(k,f);case "key-value":if("object"!==typeof e||null===e||e instanceof Array)return c("an object",e);k=B.Nil;for(g in e){f=h(a.decoder,e[g]);if("ok"!==f.tag)return{tag:"field",field:g,rest:f};f=n.Tuple2(g,f.value);k=B.Cons(f,k)}return b(k);case "map-many":g=a.func;a=a.decoders;for(k=0;k<a.length;k++){f=
h(a[k],e);if("ok"!==f.tag)return f;g=g(f.value)}return b(g);case "andThen":return f=h(a.decoder,e),"ok"!==f.tag?f:h(a.callback(f.value),e);case "oneOf":k=[];for(a=a.decoders;"[]"!==a.ctor;){f=h(a._0,e);if("ok"===f.tag)return f;k.push(f);a=a._1}return{tag:"oneOf",problems:k};case "fail":return{tag:"fail",msg:a.msg};case "succeed":return b(a.msg)}}function p(a,b){if(a===b)return!0;if(a.tag!==b.tag)return!1;switch(a.tag){case "succeed":case "fail":return a.msg===b.msg;case "bool":case "int":case "float":case "string":case "value":return!0;
case "null":return a.value===b.value;case "list":case "array":case "maybe":case "key-value":return p(a.decoder,b.decoder);case "field":return a.field===b.field&&p(a.decoder,b.decoder);case "index":return a.index===b.index&&p(a.decoder,b.decoder);case "map-many":return a.func!==b.func?!1:q(a.decoders,b.decoders);case "andThen":return a.callback===b.callback&&p(a.decoder,b.decoder);case "oneOf":return q(a.decoders,b.decoders)}}function q(a,b){var d=a.length;if(d!==b.length)return!1;for(var c=0;c<d;c++)if(!p(a[c],
b[c]))return!1;return!0}return{encode:e(function(a,b){return JSON.stringify(b,null,a)}),runOnString:e(function(a,b){try{var d=JSON.parse(b)}catch(Ia){return A("Given an invalid JSON: "+Ia.message)}return f(a,d)}),run:e(f),decodeNull:function(a){return{ctor:"\x3cdecoder\x3e",tag:"null",value:a}},decodePrimitive:function(a){return{ctor:"\x3cdecoder\x3e",tag:a}},decodeContainer:e(function(a,b){return{ctor:"\x3cdecoder\x3e",tag:a,decoder:b}}),decodeField:e(function(a,b){return{ctor:"\x3cdecoder\x3e",
tag:"field",field:a,decoder:b}}),decodeIndex:e(function(a,b){return{ctor:"\x3cdecoder\x3e",tag:"index",index:a,decoder:b}}),map1:e(function(b,d){return a(b,[d])}),map2:t(function(b,d,c){return a(b,[d,c])}),map3:w(function(b,d,c,e){return a(b,[d,c,e])}),map4:y(function(b,d,c,e,f){return a(b,[d,c,e,f])}),map5:F(function(b,d,c,e,f,g){return a(b,[d,c,e,f,g])}),map6:ta(function(b,d,c,e,f,g,h){return a(b,[d,c,e,f,g,h])}),map7:ka(function(b,d,c,e,f,g,h,p){return a(b,[d,c,e,f,g,h,p])}),map8:Ib(function(b,
d,c,e,f,g,h,p,v){return a(b,[d,c,e,f,g,h,p,v])}),decodeKeyValuePairs:function(a){return{ctor:"\x3cdecoder\x3e",tag:"key-value",decoder:a}},andThen:e(function(a,b){return{ctor:"\x3cdecoder\x3e",tag:"andThen",decoder:b,callback:a}}),fail:function(a){return{ctor:"\x3cdecoder\x3e",tag:"fail",msg:a}},succeed:function(a){return{ctor:"\x3cdecoder\x3e",tag:"succeed",msg:a}},oneOf:function(a){return{ctor:"\x3cdecoder\x3e",tag:"oneOf",decoders:a}},identity:function(a){return a},encodeNull:null,encodeArray:P.toJSArray,
encodeList:B.toArray,encodeObject:function(a){for(var b={};"[]"!==a.ctor;){var d=a._0;b[d._0]=d._1;a=a._1}return b},equality:p}}(),Bc=M.identity,Cc=M.identity,Dc=M.decodePrimitive("value"),Ec=M.succeed,Na=M.run,Fc=M.map2,zb=M.map1,ra=M.decodeField,Ab=e(function(a,b){return r(U,ra,b,a)}),Gc=M.decodePrimitive("float"),Hc=M.decodePrimitive("int"),Ic=M.decodePrimitive("bool"),Bb=M.decodePrimitive("string");e(function(a,b){return{ctor:"_Tuple2",_0:b._0,_1:a(b._1)}});e(function(a,b){return{ctor:"_Tuple2",
_0:a(b._0),_1:b._1}});var Jc=function(){function a(a){return function(b,d,c){return z.nativeBinding(function(e){function g(a){a=f(Na,d,a);"Ok"===a.ctor&&z.rawSpawn(c(a._0))}a.addEventListener(b,g);return function(){a.removeEventListener(b,g)}})}}function b(a,b){return z.nativeBinding(function(d){g(function(){var c=document.getElementById(a);null===c?d(z.fail({ctor:"NotFound",_0:a})):d(z.succeed(b(c)))})})}var c={addEventListener:function(){},removeEventListener:function(){}},d=a("undefined"!==typeof document?
document:c),c=a("undefined"!==typeof window?window:c),g="undefined"!==typeof requestAnimationFrame?requestAnimationFrame:function(a){a()};return{onDocument:t(d),onWindow:t(c),focus:function(a){return b(a,function(a){a.focus();return n.Tuple0})},blur:function(a){return b(a,function(a){a.blur();return n.Tuple0})},getScrollTop:function(a){return b(a,function(a){return a.scrollTop})},setScrollTop:e(function(a,d){return b(a,function(a){a.scrollTop=d;return n.Tuple0})}),getScrollLeft:function(a){return b(a,
function(a){return a.scrollLeft})},setScrollLeft:e(function(a,d){return b(a,function(a){a.scrollLeft=d;return n.Tuple0})}),toBottom:function(a){return b(a,function(a){a.scrollTop=a.scrollHeight;return n.Tuple0})},toRight:function(a){return b(a,function(a){a.scrollLeft=a.scrollWidth;return n.Tuple0})},height:e(function(a,d){return b(d,function(b){switch(a.ctor){case "Content":return b.scrollHeight;case "VisibleContent":return b.clientHeight;case "VisibleContentWithBorders":return b.offsetHeight;case "VisibleContentWithBordersAndMargins":return b=
b.getBoundingClientRect(),b.bottom-b.top}})}),width:e(function(a,d){return b(d,function(b){switch(a.ctor){case "Content":return b.scrollWidth;case "VisibleContent":return b.clientWidth;case "VisibleContentWithBorders":return b.offsetWidth;case "VisibleContentWithBordersAndMargins":return b=b.getBoundingClientRect(),b.right-b.left}})})}}().focus,fb,Y=function(){function a(a,b,d){return{type:"thunk",func:a,args:b,thunk:d,node:void 0}}function b(a){for(var b,d={};"[]"!==a.ctor;){var c=a._0,e=c.key;if("ATTR"===
e||"ATTR_NS"===e||"EVENT"===e){var l=d[e]||{};l[c.realKey]=c.value;d[e]=l}else if("STYLE"===e){l=d[e]||{};for(c=c.value;"[]"!==c.ctor;){var f=c._0;l[f._0]=f._1;c=c._1}d[e]=l}else"namespace"===e?b=c.value:"className"===e?(l=d[e],d[e]="undefined"===typeof l?c.value:l+" "+c.value):d[e]=c.value;a=a._1}return{facts:d,namespace:b}}function c(a,b,d){return{key:"EVENT",realKey:a,value:{options:b,decoder:d}}}function d(a,b){switch(a.type){case "thunk":return a.node||(a.node=a.thunk()),d(a.node,b);case "tagger":var c=
a.node;for(a=a.tagger;"tagger"===c.type;)"object"!==typeof a?a=[a,c.tagger]:a.push(c.tagger),c=c.node;b={tagger:a,parent:b};c=d(c,b);c.elm_event_node_ref=b;return c;case "text":return E.createTextNode(a.text);case "node":c=a.namespace?E.createElementNS(a.namespace,a.tag):E.createElement(a.tag);g(c,b,a.facts);a=a.children;for(var e=0;e<a.length;e++)c.appendChild(d(a[e],b));return c;case "keyed-node":c=a.namespace?E.createElementNS(a.namespace,a.tag):E.createElement(a.tag);g(c,b,a.facts);a=a.children;
for(e=0;e<a.length;e++)c.appendChild(d(a[e]._1,b));return c;case "custom":return c=a.impl.render(a.model),g(c,b,a.facts),c}}function g(a,b,d){for(var c in d){var e=d[c];switch(c){case "STYLE":var f=void 0,g=a.style;for(f in e)g[f]=e[f];break;case "EVENT":var f=void 0,g=a,l=b,u=e,k=g.elm_handlers||{};for(f in u){var e=k[f],G=u[f];"undefined"===typeof G?(g.removeEventListener(f,e),k[f]=void 0):"undefined"===typeof e?(e=h(l,G),g.addEventListener(f,e),k[f]=e):e.info=G}g.elm_handlers=k;break;case "ATTR":f=
void 0;g=a;for(f in e)l=e[f],"undefined"===typeof l?g.removeAttribute(f):g.setAttribute(f,l);break;case "ATTR_NS":f=void 0;g=a;for(f in e)u=e[f],l=u.namespace,u=u.value,"undefined"===typeof u?g.removeAttributeNS(l,f):g.setAttributeNS(l,f,u);break;case "value":a[c]!==e&&(a[c]=e);break;default:a[c]=e}}}function h(a,b){function c(b){var d=c.info,e=f(M.run,d.decoder,b);if("Ok"===e.ctor)for(d=d.options,d.stopPropagation&&b.stopPropagation(),d.preventDefault&&b.preventDefault(),b=e._0,e=a;e;){d=e.tagger;
if("function"===typeof d)b=d(b);else for(var g=d.length;g--;)b=d[g](b);e=e.parent}}c.info=b;return c}function q(a,b){var d=[];x(a,b,d,0);return d}function p(a,b,d){return{index:b,type:a,data:d,domNode:void 0,eventNode:void 0}}function x(a,b,d,c){if(a!==b){var e=b.type;if(a.type!==e)d.push(p("p-redraw",c,b));else switch(e){case "thunk":for(var f=a.args,g=b.args,l=f.length,u=a.func===b.func&&l===g.length;u&&l--;)u=f[l]===g[l];if(u){b.node=a.node;break}b.node=b.thunk();f=[];x(a.node,b.node,f,0);0<f.length&&
d.push(p("p-thunk",c,f));break;case "tagger":for(var u=a.tagger,f=b.tagger,h=!1,g=a.node;"tagger"===g.type;)h=!0,"object"!==typeof u?u=[u,g.tagger]:u.push(g.tagger),g=g.node;for(l=b.node;"tagger"===l.type;)h=!0,"object"!==typeof f?f=[f,l.tagger]:f.push(l.tagger),l=l.node;if(h&&u.length!==f.length){d.push(p("p-redraw",c,b));break}if(h){a:{for(h=0;h<u.length;h++)if(u[h]!==f[h]){u=!1;break a}u=!0}u=!u}else u=u!==f;u&&d.push(p("p-tagger",c,f));x(g,l,d,c+1);break;case "text":a.text!==b.text&&d.push(p("p-text",
c,b.text));break;case "node":if(a.tag!==b.tag||a.namespace!==b.namespace){d.push(p("p-redraw",c,b));break}e=k(a.facts,b.facts);"undefined"!==typeof e&&d.push(p("p-facts",c,e));f=a.children;g=b.children;l=f.length;u=g.length;l>u?d.push(p("p-remove-last",c,l-u)):l<u&&d.push(p("p-append",c,g.slice(l)));l=l<u?l:u;for(u=0;u<l;u++)c++,h=f[u],x(h,g[u],d,c),c+=h.descendantsCount||0;break;case "keyed-node":if(a.tag!==b.tag||a.namespace!==b.namespace){d.push(p("p-redraw",c,b));break}e=k(a.facts,b.facts);"undefined"!==
typeof e&&d.push(p("p-facts",c,e));var e=[],G={},la=[];a=a.children;for(var n=b.children,q=a.length,t=n.length,v=0,r=0,w=c;v<q&&r<t;){var y=a[v];var z=n[r];var A=y._0,C=z._0;b=y._1;z=z._1;if(A===C)w++,x(b,z,e,w),w+=b.descendantsCount||0,v++,r++;else{y=v+1<q;var D=r+1<t;if(y){var F=a[v+1];g=F._0;var E=F._1;F=C===g}D&&(u=n[r+1],f=u._0,h=u._1,u=A===f);if(y&&D&&u&&F)w++,x(b,h,e,w),m(G,e,A,z,r,la),w+=b.descendantsCount||0,w++,B(G,e,A,E,w),w+=E.descendantsCount||0,v+=2,r+=2;else if(D&&u)w++,m(G,e,C,z,r,
la),x(b,h,e,w),w+=b.descendantsCount||0,v+=1,r+=2;else if(y&&F)w++,B(G,e,A,b,w),w+=b.descendantsCount||0,w++,x(E,z,e,w),w+=E.descendantsCount||0,v+=2,r+=1;else if(y&&D&&g===f)w++,B(G,e,A,b,w),m(G,e,C,z,r,la),w+=b.descendantsCount||0,w++,x(E,h,e,w),w+=E.descendantsCount||0,v+=2,r+=2;else break}}for(;v<q;)w++,y=a[v],b=y._1,B(G,e,y._0,b,w),w+=b.descendantsCount||0,v++;for(;r<t;)l=l||[],z=n[r],m(G,e,z._0,z._1,void 0,l),r++;(0<e.length||0<la.length||"undefined"!==typeof l)&&d.push(p("p-reorder",c,{patches:e,
inserts:la,endInserts:l}));break;case "custom":a.impl!==b.impl?d.push(p("p-redraw",c,b)):(e=k(a.facts,b.facts),"undefined"!==typeof e&&d.push(p("p-facts",c,e)),(f=b.impl.diff(a,b))&&d.push(p("p-custom",c,f)))}}}function k(a,b,d){var c;for(c in a)if("STYLE"===c||"EVENT"===c||"ATTR"===c||"ATTR_NS"===c){var e=k(a[c],b[c]||{},c);if(e){var f=f||{};f[c]=e}}else if(c in b){var e=a[c],g=b[c],l;!(l=e===g&&"value"!==c)&&(l="EVENT"===d)&&(l=e.options===g.options||e.options.stopPropagation===g.options.stopPropagation&&
e.options.preventDefault===g.options.preventDefault?M.equality(e.decoder,g.decoder):!1);l||(f=f||{},f[c]=g)}else f=f||{},f[c]="undefined"===typeof d?"string"===typeof a[c]?"":null:"STYLE"===d?"":"EVENT"===d||"ATTR"===d?void 0:{namespace:a[c].namespace,value:void 0};for(var u in b)u in a||(f=f||{},f[u]=b[u]);return f}function m(a,b,c,d,e,f){var g=a[c];"undefined"===typeof g?(g={tag:"insert",vnode:d,index:e,data:void 0},f.push({index:e,entry:g}),a[c]=g):"remove"===g.tag?(f.push({index:e,entry:g}),g.tag=
"move",a=[],x(g.vnode,d,a,g.index),g.index=e,g.data.data={patches:a,entry:g}):m(a,b,c+W,d,e,f)}function B(a,b,c,d,e){var f=a[c];"undefined"===typeof f?(f=p("p-remove",e,void 0),b.push(f),a[c]={tag:"remove",vnode:d,index:e,data:f}):"insert"===f.tag?(f.tag="move",a=[],x(d,f.vnode,a,e),f=p("p-remove",e,{patches:a,entry:f}),b.push(f)):B(a,b,c+W,d,e)}function y(a,b,c,d,e,f,g){for(var l,u=c[d],h=u.index;h===e;)if(l=u.type,"p-thunk"===l?(l=b.node,y(a,l,u.data,0,0,l.descendantsCount,g)):"p-reorder"===l?(u.domNode=
a,u.eventNode=g,l=u.data.patches,0<l.length&&y(a,b,l,0,e,f,g)):"p-remove"===l?(u.domNode=a,u.eventNode=g,l=u.data,"undefined"!==typeof l&&(l.entry.data=a,l=l.patches,0<l.length&&y(a,b,l,0,e,f,g))):(u.domNode=a,u.eventNode=g),d++,!(u=c[d])||(h=u.index)>f)return d;switch(b.type){case "tagger":for(g=b.node;"tagger"===g.type;)g=g.node;return y(a,g,c,d,e+1,f,a.elm_event_node_ref);case "node":b=b.children;for(var k=a.childNodes,G=0;G<b.length;G++){e++;l=b[G];a=e+(l.descendantsCount||0);if(e<=h&&h<=a&&(d=
y(k[G],l,c,d,e,a,g),!(u=c[d])||(h=u.index)>f))break;e=a}return d;case "keyed-node":b=b.children;k=a.childNodes;for(G=0;G<b.length;G++){e++;l=b[G]._1;a=e+(l.descendantsCount||0);if(e<=h&&h<=a&&(d=y(k[G],l,c,d,e,a,g),!(u=c[d])||(h=u.index)>f))break;e=a}return d;case "text":case "thunk":throw Error("should never traverse `text` or `thunk` nodes like this");}}function A(a,b,d,c){if(0===d.length)return a;y(a,b,d,0,0,b.descendantsCount,c);return D(a,d)}function D(a,b){for(var d=0;d<b.length;d++){var c=
b[d],e=c.domNode,c=H(e,c);e===a&&(a=c)}return a}function H(a,b){switch(b.type){case "p-redraw":var c=a.parentNode;b=d(b.data,b.eventNode);"undefined"===typeof b.elm_event_node_ref&&(b.elm_event_node_ref=a.elm_event_node_ref);c&&b!==a&&c.replaceChild(b,a);return b;case "p-facts":return g(a,b.eventNode,b.data),a;case "p-text":return a.replaceData(0,a.length,b.data),a;case "p-thunk":return D(a,b.data);case "p-tagger":return"undefined"!==typeof a.elm_event_node_ref?a.elm_event_node_ref.tagger=b.data:
a.elm_event_node_ref={tagger:b.data,parent:b.eventNode},a;case "p-remove-last":for(c=b.data;c--;)a.removeChild(a.lastChild);return a;case "p-append":for(var e=b.data,c=0;c<e.length;c++)a.appendChild(d(e[c],b.eventNode));return a;case "p-remove":b=b.data;if("undefined"===typeof b)return a.parentNode.removeChild(a),a;c=b.entry;"undefined"!==typeof c.index&&a.parentNode.removeChild(a);c.data=D(a,b.patches);return a;case "p-reorder":e=b.data;c=e.endInserts;if("undefined"!==typeof c){for(var f=E.createDocumentFragment(),
h=0;h<c.length;h++){var l=c[h].entry;f.appendChild("move"===l.tag?l.data:d(l.vnode,b.eventNode))}c=f}else c=void 0;a=D(a,e.patches);e=e.inserts;for(f=0;f<e.length;f++)h=e[f],l=h.entry,l="move"===l.tag?l.data:d(l.vnode,b.eventNode),a.insertBefore(l,a.childNodes[h.index]);"undefined"!==typeof c&&a.appendChild(c);return a;case "p-custom":return b=b.data,b.applyPatch(a,b.data);default:throw Error("Ran into an unknown patch!");}}function I(a){return e(function(b,c){return function(d){return function(e,
g,h){var l=a(d,g);"undefined"===typeof h?K(c,e,g,l):C(f(b,h,c),e,g,l)}}})}function F(a,b){b&&(b.innerHTML='\x3cdiv style\x3d"padding-left:1em;"\x3e\x3ch2 style\x3d"font-weight:normal;"\x3e\x3cb\x3eOops!\x3c/b\x3e Something went wrong when starting your Elm program.\x3c/h2\x3e\x3cpre style\x3d"padding-left:1em;"\x3e'+a+"\x3c/pre\x3e\x3c/div\x3e");throw Error(a);}function K(a,b,c,d){b.embed=function(b,c){for(;b.lastChild;)b.removeChild(b.lastChild);return V.initialize(d(a.init,c,b),a.update,a.subscriptions,
J(b,a.view))};b.fullscreen=function(b){return V.initialize(d(a.init,b,document.body),a.update,a.subscriptions,J(document.body,a.view))}}function J(a,b){return function(c,e){c={tagger:c,parent:void 0};e=b(e);var f=d(e,c);a.appendChild(f);return L(f,b,e,c)}}function L(a,b,c,d){function e(){switch(f){case "NO_REQUEST":throw Error("Unexpected draw callback.\nPlease report this to \x3chttps://github.com/elm-lang/virtual-dom/issues\x3e.");case "PENDING_REQUEST":Y(e);f="EXTRA_REQUEST";var c=b(h),k=q(g,c);
a=A(a,g,k,d);g=c;break;case "EXTRA_REQUEST":f="NO_REQUEST"}}var f="NO_REQUEST",g=c,h;return function(a){"NO_REQUEST"===f&&Y(e);f="PENDING_REQUEST";h=a}}function C(a,b,c,d){b.fullscreen=function(b){var e={doc:void 0};return V.initialize(d(a.init,b,document.body),a.update(N(e)),a.subscriptions,P(c,document.body,e,a.view,a.viewIn,a.viewOut))};b.embed=function(b,e){var f={doc:void 0};return V.initialize(d(a.init,e,b),a.update(N(f)),a.subscriptions,P(c,b,f,a.view,a.viewIn,a.viewOut))}}function N(a){return z.nativeBinding(function(b){var c=
a.doc;c&&(c=c.getElementsByClassName("debugger-sidebar-messages")[0])&&(c.scrollTop=c.scrollHeight);b(z.succeed(n.Tuple0))})}function P(a,b,c,e,f,g){return function(h,k){var l={tagger:h,parent:void 0};h={tagger:h,parent:void 0};var u=e(k),m=d(u,l);b.appendChild(m);var n=L(m,e,u,l),u=f(k)._1,m=d(u,h);b.appendChild(m);var l=U(l,m,f),p=L(m,l,u,h),q=Q(k,g,h,b,a,c);return function(a){n(a);p(a);q(a)}}}function Q(a,b,c,d,e,f){var g,h;return function(a){if(a.isDebuggerOpen)if(f.doc){E=f.doc;a=b(a);var d=
q(g,a);h=A(h,g,d,c);g=a;E=document}else g=b(a),h=R(e,f,g,c)}}function R(a,b,c,e){function f(){b.doc=void 0;g.close()}var g=window.open("","","width\x3d900,height\x3d360,left\x3d"+(screen.width-900)+",top\x3d"+(screen.height-360));E=g.document;b.doc=E;E.title="Debugger - "+a;E.body.style.margin="0";E.body.style.padding="0";a=d(c,e);E.body.appendChild(a);E.addEventListener("keydown",function(a){a.metaKey&&82===a.which&&window.location.reload();38===a.which&&(e.tagger({ctor:"Up"}),a.preventDefault());
40===a.which&&(e.tagger({ctor:"Down"}),a.preventDefault())});window.addEventListener("unload",f);g.addEventListener("unload",function(){b.doc=void 0;window.removeEventListener("unload",f);e.tagger({ctor:"Close"})});E=document;return a}function U(a,b,c){var d=aa(b),e="Normal",f,g=a.tagger,h=function(){};return function(b){b=c(b);var k=b._0.ctor;a.tagger="Normal"===k?g:h;e!==k&&(S("removeEventListener",d,e),S("addEventListener",d,k),"Normal"===e&&(f=document.body.style.overflow,document.body.style.overflow=
"hidden"),"Normal"===k&&(document.body.style.overflow=f),e=k);return b._1}}function S(a,b,c){switch(c){case "Pause":return T(a,b,Z);case "Message":return T(a,b,ea)}}function T(a,b,c){for(var d=0;d<c.length;d++)document.body[a](c[d],b,!0)}function aa(a){return function(b){if("keydown"!==b.type||!b.metaKey||82!==b.which){for(var c="scroll"===b.type||"wheel"===b.type,d=b.target;null!==d;){if("elm-overlay-message-details"===d.className&&c||d===a&&!c)return;d=d.parentNode}b.stopPropagation();b.preventDefault()}}}
var E="undefined"!==typeof document?document:{},W="_elmW6BL",X=I(function(a,b){return function(a,c,d){if("undefined"===typeof c)return a;F("The `"+b+"` module does not need flags.\nInitialize it with no arguments and you should be all set!",d)}}),ba=I(function(a,b){return function(c,d,e){if("undefined"===typeof a){var g="Are you trying to sneak a Never value into Elm? Trickster!\nIt looks like "+b+".main is defined with `programWithFlags` but has type `Program Never`.\nUse `program` instead if you do not want flags.";
F(g,e)}d=f(M.run,a,d);if("Ok"===d.ctor)return c(d._0);g="Trying to initialize the `"+b+"` module with an unexpected flag.\nI tried to convert it to an Elm value, but ran into this problem:\n\n"+d._0;F(g,e)}}),Y="undefined"!==typeof requestAnimationFrame?requestAnimationFrame:function(a){setTimeout(a,1E3/60)},Z="click dblclick mousemove mouseup mousedown mouseenter mouseleave touchstart touchend touchcancel touchmove pointerdown pointerup pointerover pointerout pointerenter pointerleave pointermove pointercancel dragstart drag dragend dragenter dragover dragleave drop keyup keydown keypress input change focus blur".split(" "),
ea=Z.concat("wheel","scroll");return{node:function(a){return e(function(c,d){var e=b(c);c=e.namespace;for(var e=e.facts,f=[],g=0;"[]"!==d.ctor;){var h=d._0,g=g+(h.descendantsCount||0);f.push(h);d=d._1}g+=f.length;return{type:"node",tag:a,facts:e,children:f,namespace:c,descendantsCount:g}})},text:function(a){return{type:"text",text:a}},custom:function(a,c,d){return{type:"custom",facts:b(a).facts,model:c,impl:d}},map:e(function(a,b){return{type:"tagger",tagger:a,node:b,descendantsCount:1+(b.descendantsCount||
0)}}),on:t(c),style:function(a){return{key:"STYLE",value:a}},property:e(function(a,b){return{key:a,value:b}}),attribute:e(function(a,b){return{key:"ATTR",realKey:a,value:b}}),attributeNS:t(function(a,b,c){return{key:"ATTR_NS",realKey:b,value:{value:c,namespace:a}}}),mapProperty:e(function(a,b){return"EVENT"!==b.key?b:c(b.realKey,b.value.options,f(zb,a,b.value.decoder))}),lazy:e(function(b,c){return a(b,[c],function(){return b(c)})}),lazy2:t(function(b,c,d){return a(b,[c,d],function(){return f(b,c,
d)})}),lazy3:w(function(b,c,d,e){return a(b,[c,d,e],function(){return r(b,c,d,e)})}),keyedNode:t(function(a,c,d){var e=b(c);c=e.namespace;for(var e=e.facts,f=[],g=0;"[]"!==d.ctor;){var h=d._0,g=g+(h._1.descendantsCount||0);f.push(h);d=d._1}g+=f.length;return{type:"keyed-node",tag:a,facts:e,children:f,namespace:c,descendantsCount:g}}),program:X,programWithFlags:ba,staticProgram:function(a){var b=n.Tuple2(n.Tuple0,ca);return f(X,fb,{init:b,view:function(){return a},update:e(function(){return b}),subscriptions:function(){return ib}})()}}}(),
Cb={stopPropagation:!1,preventDefault:!1},Kc=Y.on,Db=e(function(a,b){return r(Kc,a,Cb,b)}),Sa=Y.style,Eb=Y.property,aa=Y.text,h=Y.node;e(function(a,b){return{stopPropagation:a,preventDefault:b}});h("body");h("section");h("nav");h("article");h("aside");h("h1");h("h2");h("h3");h("h4");h("h5");h("h6");h("header");h("footer");h("address");h("main");h("p");h("hr");h("pre");h("blockquote");h("ol");var Lc=h("ul"),Mc=h("li");h("dl");h("dt");h("dd");h("figure");h("figcaption");var sa=h("div");h("a");h("em");
h("strong");h("small");h("s");h("cite");h("q");h("dfn");h("abbr");h("time");h("code");h("var");h("samp");h("kbd");h("sub");h("sup");h("i");h("b");h("u");h("mark");h("ruby");h("rt");h("rp");h("bdi");h("bdo");h("span");h("br");h("wbr");h("ins");h("del");h("img");h("iframe");h("embed");h("object");h("param");h("video");h("audio");h("source");h("track");h("canvas");h("math");var Nc=h("table");h("caption");h("colgroup");h("col");var Oc=h("tbody"),Pc=h("thead"),Qc=h("tfoot"),Da=h("tr"),Ea=h("td"),Fa=h("th");
h("form");h("fieldset");h("legend");h("label");var Ta=h("input"),Rc=h("button");h("select");h("datalist");h("optgroup");h("option");h("textarea");h("keygen");h("output");h("progress");h("meter");h("details");h("summary");h("menuitem");h("menu");var W=e(function(a,b){return f(Eb,a,Cc(b))}),R=function(a){return f(W,"className",a)};e(function(a,b){return f(Eb,a,Bc(b))});f(ra,"keyCode",Hc);f(Ab,{ctor:"::",_0:"target",_1:{ctor:"::",_0:"checked",_1:{ctor:"[]"}}},Ic);var Sc=f(Ab,{ctor:"::",_0:"target",_1:{ctor:"::",
_0:"value",_1:{ctor:"[]"}}},Bb);n.update(Cb,{preventDefault:!0});var Ua=function(a){return f(Db,"input",f(zb,a,Sc))},Ga=function(a){return f(Db,"click",Ec(a))};e(function(a,b){return{stopPropagation:a,preventDefault:b}});var Tc=function(a){var b=e(function(b,d){b=a(b);return"Nothing"===b.ctor?K:f(T,e(function(a,b){return{ctor:"::",_0:a,_1:b}})(b._0),d)});return f(U,b,L({ctor:"[]"}))},Uc=e(function(a,b){return f(lc,nb(a),nb(b.name))});V.outgoingPort("remember",function(a){return[a._0,a._1]});V.outgoingPort("forget",
function(a){return a});var Fb=y(function(a,b,c,d,e){return{foods:a,ingredients:b,input:c,sidebarOpen:d,customCarbs:e}}),Vc=e(function(a,b){return{name:a,carbs:b}}),Wc=r(Fc,Vc,f(ra,"name",Bb),f(ra,"carbs",Gc)),Xc=function(a){return{ctor:"UpdateCustomCarbs",_0:a}},Yc=e(function(a,b){return{ctor:"UpdateIngredient",_0:a,_1:b}}),Zc=e(function(a,b){return f(Da,{ctor:"[]"},{ctor:"::",_0:f(Ea,{ctor:"::",_0:Ga({ctor:"RemoveIngredient",_0:a}),_1:{ctor:"[]"}},{ctor:"::",_0:aa(b._0.name),_1:{ctor:"[]"}}),_1:{ctor:"::",
_0:f(Ea,{ctor:"[]"},{ctor:"::",_0:f(sa,{ctor:"::",_0:R(f(Ka,"has-error",f(T,ba(""),b._2))),_1:{ctor:"[]"}},{ctor:"::",_0:f(Ta,{ctor:"::",_0:f(W,"type","number"),_1:{ctor:"::",_0:R("form-control"),_1:{ctor:"::",_0:f(W,"value",b._1),_1:{ctor:"::",_0:Ua(Yc(a)),_1:{ctor:"[]"}}}}},{ctor:"[]"}),_1:{ctor:"[]"}}),_1:{ctor:"[]"}}),_1:{ctor:"[]"}}})}),$c=e(function(a,b){var c=f(Ka,"Nepp",f(T,function(a){return r(Kb,oc,"g",ea(a))},f(T,function(a){return a+f(cc,0,Pa(b))},f(T,function(a){return Lb(Mb(10*a))/10},
f(T,Qb,f(Tc,function(a){return f(T,function(b){return a._0.carbs*b/100},a._2)},a))))));return f(Nc,{ctor:"::",_0:R("table"),_1:{ctor:"[]"}},{ctor:"::",_0:f(Pc,{ctor:"[]"},{ctor:"::",_0:f(Da,{ctor:"[]"},{ctor:"::",_0:f(Fa,{ctor:"[]"},{ctor:"::",_0:aa("Ingredienser"),_1:{ctor:"[]"}}),_1:{ctor:"::",_0:f(Fa,{ctor:"::",_0:Sa({ctor:"::",_0:{ctor:"_Tuple2",_0:"width",_1:"100px"},_1:{ctor:"[]"}}),_1:{ctor:"[]"}},{ctor:"::",_0:aa("Vikt (g)"),_1:{ctor:"[]"}}),_1:{ctor:"[]"}}}),_1:{ctor:"[]"}}),_1:{ctor:"::",
_0:f(Oc,{ctor:"[]"},f(q["++"],f(eb,Zc,a),{ctor:"::",_0:f(Da,{ctor:"[]"},{ctor:"::",_0:f(Ea,{ctor:"[]"},{ctor:"::",_0:aa("Egna kolhydrater"),_1:{ctor:"[]"}}),_1:{ctor:"::",_0:f(Ea,{ctor:"::",_0:R(f(Ka,"has-error",f(T,ba(""),jb(Pa(b))))),_1:{ctor:"[]"}},{ctor:"::",_0:f(Ta,{ctor:"::",_0:R("form-control"),_1:{ctor:"::",_0:f(W,"type","number"),_1:{ctor:"::",_0:f(W,"value",b),_1:{ctor:"::",_0:Ua(Xc),_1:{ctor:"[]"}}}}},{ctor:"[]"}),_1:{ctor:"[]"}}),_1:{ctor:"[]"}}}),_1:{ctor:"[]"}})),_1:{ctor:"::",_0:f(Qc,
{ctor:"[]"},{ctor:"::",_0:f(Da,{ctor:"[]"},{ctor:"::",_0:f(Fa,{ctor:"[]"},{ctor:"::",_0:aa("Kolhydrater"),_1:{ctor:"[]"}}),_1:{ctor:"::",_0:f(Fa,{ctor:"[]"},{ctor:"::",_0:aa(c),_1:{ctor:"[]"}}),_1:{ctor:"[]"}}}),_1:{ctor:"[]"}}),_1:{ctor:"[]"}}}})}),Gb={ctor:"ToggleSidebar"},ad=function(a){return{ctor:"UpdateInput",_0:a}},bd=function(a){var b=a.sidebarOpen,c=a.input,d=function(a){return f(Mc,{ctor:"::",_0:R("list-group-item"),_1:{ctor:"::",_0:Ga({ctor:"AddIngredient",_0:{ctor:"_Tuple3",_0:a,_1:"",
_2:K}}),_1:{ctor:"[]"}}},{ctor:"::",_0:aa(a.name),_1:{ctor:"[]"}})};return f(sa,{ctor:"[]"},{ctor:"::",_0:f(sa,{ctor:"::",_0:Sa({ctor:"::",_0:{ctor:"_Tuple2",_0:"position",_1:"fixed"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"top",_1:"0"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"left",_1:"0"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"right",_1:"0"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"bottom",_1:b?"0":"auto"},_1:{ctor:"[]"}}}}}}),_1:{ctor:"::",_0:Ga(Gb),_1:{ctor:"[]"}}},{ctor:"[]"}),_1:{ctor:"::",_0:f(sa,{ctor:"::",
_0:Sa({ctor:"::",_0:{ctor:"_Tuple2",_0:"position",_1:"fixed"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"top",_1:"0"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"right",_1:"0"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"bottom",_1:"0"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"width",_1:"200px"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"margin-bottom",_1:"0"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"overflow-y",_1:"scroll"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"transform",_1:b?"none":"translateX(200px)"},_1:{ctor:"[]"}}}}}}}}}),_1:{ctor:"::",
_0:R("panel panel-default"),_1:{ctor:"[]"}}},{ctor:"::",_0:f(Ta,{ctor:"::",_0:R("form-control"),_1:{ctor:"::",_0:f(W,"id","search"),_1:{ctor:"::",_0:Ua(ad),_1:{ctor:"::",_0:f(W,"placeholder","Skriv f\u00f6r att s\u00f6ka"),_1:{ctor:"::",_0:f(W,"value",c),_1:{ctor:"[]"}}}}}},{ctor:"[]"}),_1:{ctor:"::",_0:f(Lc,{ctor:"::",_0:R("list-group"),_1:{ctor:"[]"}},0<n.cmp(mc(c),1)?f(La,d,f(Rb,Uc(c),a.foods)):{ctor:"[]"}),_1:{ctor:"[]"}}}),_1:{ctor:"[]"}}})},cd={ctor:"Noop"},Hb=f(Y.programWithFlags,void 0,{init:function(a){a=
f(Na,f(ra,"food",f(M.decodeContainer,"list",Wc)),a);return"Ok"===a.ctor?{ctor:"_Tuple2",_0:x(Fb,a._0,{ctor:"[]"},"",!0,"0"),_1:ca}:{ctor:"_Tuple2",_0:x(Fb,{ctor:"[]"},{ctor:"[]"},"",!0,"0"),_1:ca}},update:e(function(a,b){switch(a.ctor){case "Noop":return{ctor:"_Tuple2",_0:b,_1:ca};case "UpdateInput":return{ctor:"_Tuple2",_0:n.update(b,{input:a._0}),_1:ca};case "AddIngredient":return{ctor:"_Tuple2",_0:n.update(b,{input:"",ingredients:{ctor:"::",_0:a._0,_1:b.ingredients}}),_1:f(jc,ba(cd),Jc("search"))};
case "ToggleSidebar":return{ctor:"_Tuple2",_0:n.update(b,{sidebarOpen:!b.sidebarOpen}),_1:ca};case "UpdateIngredient":var c=a._1,d=e(function(b,d){var e=d._0;return n.eq(b,a._0)?{ctor:"_Tuple3",_0:e,_1:c,_2:jb(Pa(c))}:{ctor:"_Tuple3",_0:e,_1:d._1,_2:d._2}}),d=f(eb,d,b.ingredients);return{ctor:"_Tuple2",_0:n.update(b,{ingredients:d}),_1:ca};case "RemoveIngredient":return d=a._0,d=f(q["++"],f(Wb,d,b.ingredients),f(Nb,d+1,b.ingredients)),{ctor:"_Tuple2",_0:n.update(b,{ingredients:d}),_1:ca};default:return{ctor:"_Tuple2",
_0:n.update(b,{customCarbs:a._0}),_1:ca}}}),view:function(a){return f(sa,{ctor:"[]"},{ctor:"::",_0:f($c,a.ingredients,a.customCarbs),_1:{ctor:"::",_0:f(Rc,{ctor:"::",_0:R("btn btn-success btn-lg btn-block"),_1:{ctor:"::",_0:Ga(Gb),_1:{ctor:"[]"}}},{ctor:"::",_0:aa("L\u00e4gg till ingrediens"),_1:{ctor:"[]"}}),_1:{ctor:"::",_0:bd(a),_1:{ctor:"[]"}}}})},subscriptions:ba(ib)})(Dc),X={};X.Main=X.Main||{};"undefined"!==typeof Hb&&Hb(X.Main,"Main",void 0);if("function"===typeof define&&define.amd)define([],
function(){return X});else if("object"===typeof module)module.exports=X;else{var Va=this.Elm;if("undefined"===typeof Va)this.Elm=X;else for(var Ha in X){if(Ha in Va)throw Error("There are two Elm modules called `"+Ha+"` on this page! Rename one of them.");Va[Ha]=X[Ha]}}}).call(this);
